package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * AcademicyearId generated by hbm2java
 */
public class AcademicyearId  implements java.io.Serializable {


     private String instituteid;
     private String academicyear;

    public AcademicyearId() {
    }

    public AcademicyearId(String instituteid, String academicyear) {
       this.instituteid = instituteid;
       this.academicyear = academicyear;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcademicyearId) ) return false;
		 AcademicyearId castOther = ( AcademicyearId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getAcademicyear()==castOther.getAcademicyear()) || ( this.getAcademicyear()!=null && castOther.getAcademicyear()!=null && this.getAcademicyear().equals(castOther.getAcademicyear()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getAcademicyear() == null ? 0 : this.getAcademicyear().hashCode() );
         return result;
   }   


}


