package com.jilit.irp.persistence.dto;
// Generated Mar 23, 2015 3:19:35 PM by Hibernate Tools 3.2.1.GA



/**
 * AttendancefollowupmasterId generated by hbm2java
 */
public class AttendancefollowupmasterId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private byte followupno;

    public AttendancefollowupmasterId() {
    }

    public AttendancefollowupmasterId(String instituteid, String registrationid, byte followupno) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.followupno = followupno;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public byte getFollowupno() {
        return this.followupno;
    }
    
    public void setFollowupno(byte followupno) {
        this.followupno = followupno;
    }
}


