package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * BasketmasterId generated by hbm2java
 */
public class BasketMasterId  implements java.io.Serializable {

    private String instituteid;
    private String basketid;

    public BasketMasterId() {
    }

    public BasketMasterId(String instituteid, String basketid) {
       this.instituteid = instituteid;
       this.basketid = basketid;
    }

    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }

    public String getBasketid() {
        return this.basketid;
    }
    
    public void setBasketid(String basketid) {
        this.basketid = basketid;
    }

/*
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BasketMasterId) ) return false;
		 BasketMasterId castOther = ( BasketMasterId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getBasketid()==castOther.getBasketid()) || ( this.getBasketid()!=null && castOther.getBasketid()!=null && this.getBasketid().equals(castOther.getBasketid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getBasketid() == null ? 0 : this.getBasketid().hashCode() );
         return result;
   }   
*/

}


