package com.jilit.irp.persistence.dto;
// Generated Dec 21, 2009 11:00:34 AM by Hibernate Tools 3.2.1.GA

import com.jilit.irp.persistence.dto.*;

/**
 * BasketMasterdetail generated by hbm2java
 */
public class BasketMasterDetail implements java.io.Serializable {

     private BasketMasterDetailId id;
     private InstituteMaster institutemaster;
     private Academicyear academicyear;
     private ProgramMaster programmaster;
     private SectionMaster sectionmaster;
     private SubjectTypeMaster subjecttypemaster;
     private String basketcode;
     private String basketdesc;
     private String programid;
     private String sectionid;
     private byte stynumber;
     private String subjecttypeid;
     private String optional;
     private Short totalsubject;
     private Short minsubject;
     private Short maxsubject;
     private Short seqid;
     private String deactive;
     private String preferencetype;

    public BasketMasterDetail() {
    }
   
    public BasketMasterDetail(BasketMasterDetail dto, boolean childReqd) {
        this.id = dto.getId();
        // this.institutemaster = dto.getInstitutemaster();
        this.basketcode = dto.getBasketcode();
        this.basketdesc = dto.getBasketdesc();
        //this.academicyear = dto.getAcademicyear();
        this.programid = dto.getProgramid();
        this.sectionid = dto.getSectionid();
        this.stynumber = dto.getStynumber();
        this.subjecttypeid = dto.getSubjecttypeid();
        this.optional = dto.getOptional();
        this.totalsubject = dto.getTotalsubject();
        this.minsubject = dto.getMinsubject();
        this.maxsubject = dto.getMaxsubject();
        this.seqid = dto.getSeqid();
        this.deactive = dto.getDeactive();
        this.preferencetype=dto.getPreferencetype();
    }

    public BasketMasterDetail(BasketMasterDetail dto) {
        this.id = dto.getId();
        // this.institutemaster = dto.getInstitutemaster();
        this.basketcode = dto.getBasketcode();
        this.basketdesc = dto.getBasketdesc();
        //this.academicyear = dto.getAcademicyear();
        this.programid = dto.getProgramid();
        this.sectionid = dto.getSectionid();
        this.stynumber = dto.getStynumber();
        this.subjecttypeid = dto.getSubjecttypeid();
        this.optional = dto.getOptional();
        this.totalsubject = dto.getTotalsubject();
        this.minsubject = dto.getMinsubject();
        this.maxsubject = dto.getMaxsubject();
        this.seqid = dto.getSeqid();
        this.deactive = dto.getDeactive();
        this.preferencetype=dto.getPreferencetype();
    }

    public BasketMasterDetail(BasketMasterDetailId id, InstituteMaster institutemaster, Academicyear academicyear, ProgramMaster programmaster, SectionMaster sectionmaster, SubjectTypeMaster subjecttypemaster, String basketcode, String basketdesc, String programid, String sectionid, byte stynumber, String subjecttypeid) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.academicyear = academicyear;
        this.subjecttypemaster = subjecttypemaster;
        this.basketcode = basketcode;
        this.basketdesc = basketdesc;
        this.programid = programid;
        this.sectionid = sectionid;
        this.stynumber = stynumber;
        this.subjecttypeid = subjecttypeid;
    }
    public BasketMasterDetail(BasketMasterDetailId id, InstituteMaster institutemaster, Academicyear academicyear, ProgramMaster programmaster, SectionMaster sectionmaster, SubjectTypeMaster subjecttypemaster, String basketcode, String basketdesc, String programid, String sectionid, byte stynumber, String subjecttypeid, String optional, Short totalsubject, Short minsubject, Short maxsubject, Short seqid, String deactive, String preferencetype) {
       this.id = id;
       this.institutemaster = institutemaster;
       this.academicyear = academicyear;
       this.subjecttypemaster = subjecttypemaster;
       this.basketcode = basketcode;
       this.basketdesc = basketdesc;
       this.programid = programid;
       this.sectionid = sectionid;
       this.stynumber = stynumber;
       this.subjecttypeid = subjecttypeid;
       this.optional = optional;
       this.totalsubject = totalsubject;
       this.minsubject = minsubject;
       this.maxsubject = maxsubject;
       this.seqid = seqid;
       this.deactive = deactive;
       this.preferencetype = preferencetype;
    }

    /**
     * @return the id
     */
    public BasketMasterDetailId getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(BasketMasterDetailId id) {
        this.id = id;
    }

    public Academicyear getAcademicyear() {
        return academicyear;
    }

    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }


    /**
     * @return the programmaster
     */
    public ProgramMaster getProgrammaster() {
        return programmaster;
    }

    /**
     * @param programmaster the programmaster to set
     */
    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }

    /**
     * @return the sectionmaster
     */
    public SectionMaster getSectionmaster() {
        return sectionmaster;
    }

    /**
     * @param sectionmaster the sectionmaster to set
     */
    public void setSectionmaster(SectionMaster sectionmaster) {
        this.sectionmaster = sectionmaster;
    }

    /**
     * @return the subjecttypemaster
     */
    public SubjectTypeMaster getSubjecttypemaster() {
        return subjecttypemaster;
    }

    /**
     * @param subjecttypemaster the subjecttypemaster to set
     */
    public void setSubjecttypemaster(SubjectTypeMaster subjecttypemaster) {
        this.subjecttypemaster = subjecttypemaster;
    }

    /**
     * @return the basketcode
     */
    public String getBasketcode() {
        return basketcode;
    }

    /**
     * @param basketcode the basketcode to set
     */
    public void setBasketcode(String basketcode) {
        this.basketcode = basketcode;
    }

    /**
     * @return the basketdesc
     */
    public String getBasketdesc() {
        return basketdesc;
    }

    /**
     * @param basketdesc the basketdesc to set
     */
    public void setBasketdesc(String basketdesc) {
        this.basketdesc = basketdesc;
    }

    /**
     * @return the programid
     */
    public String getProgramid() {
        return programid;
    }

    /**
     * @param programid the programid to set
     */
    public void setProgramid(String programid) {
        this.programid = programid;
    }

    /**
     * @return the sectionid
     */
    public String getSectionid() {
        return sectionid;
    }

    /**
     * @param sectionid the sectionid to set
     */
    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * @return the stynumber
     */
    public byte getStynumber() {
        return stynumber;
    }

    /**
     * @param stynumber the stynumber to set
     */
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }

    /**
     * @return the subjecttypeid
     */
    public String getSubjecttypeid() {
        return subjecttypeid;
    }

    /**
     * @param subjecttypeid the subjecttypeid to set
     */
    public void setSubjecttypeid(String subjecttypeid) {
        this.subjecttypeid = subjecttypeid;
    }

    /**
     * @return the optional
     */
    public String getOptional() {
        return optional;
    }

    /**
     * @param optional the optional to set
     */
    public void setOptional(String optional) {
        this.optional = optional;
    }

    /**
     * @return the totalsubject
     */
    public Short getTotalsubject() {
        return totalsubject;
    }

    /**
     * @param totalsubject the totalsubject to set
     */
    public void setTotalsubject(Short totalsubject) {
        this.totalsubject = totalsubject;
    }

    /**
     * @return the minsubject
     */
    public Short getMinsubject() {
        return minsubject;
    }

    /**
     * @param minsubject the minsubject to set
     */
    public void setMinsubject(Short minsubject) {
        this.minsubject = minsubject;
    }

    /**
     * @return the maxsubject
     */
    public Short getMaxsubject() {
        return maxsubject;
    }

    /**
     * @param maxsubject the maxsubject to set
     */
    public void setMaxsubject(Short maxsubject) {
        this.maxsubject = maxsubject;
    }

    /**
     * @return the seqid
     */
    public Short getSeqid() {
        return seqid;
    }

    /**
     * @param seqid the seqid to set
     */
    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }

    /**
     * @return the deactive
     */
    public String getDeactive() {
        return deactive;
    }

    /**
     * @param deactive the deactive to set
     */
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getAcademicyear() + "::" + id.getBasketid() + "::" + id.getProgramid() + "::" + id.getSectionid() + "::" + id.getStynumber();
    }

    /**
     * @return the institutemaster
     */
    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    /**
     * @param institutemaster the institutemaster to set
     */
    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    /**
     * @return the preferencetype
     */
    public String getPreferencetype() {
        return preferencetype;
    }

    /**
     * @param preferencetype the preferencetype to set
     */
    public void setPreferencetype(String preferencetype) {
        this.preferencetype = preferencetype;
    }

}


