package com.jilit.irp.persistence.dto;
// Generated May 5, 2012 11:55:53 AM by Hibernate Tools 3.2.1.GA



/**
 * BranchchangerequestId generated by hbm2java
 */
public class BranchChangeRequestId  implements java.io.Serializable {


     private String instituteid;
     private String studentid;
     private String programid;
     private String branchid;

    public BranchChangeRequestId() {
    }

    public BranchChangeRequestId(String instituteid, String studentid, String programid, String branchid) {
       this.instituteid = instituteid;
       this.studentid = studentid;
       this.programid = programid;
       this.branchid = branchid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getBranchid() {
        return this.branchid;
    }
    
    public void setBranchid(String branchid) {
        this.branchid = branchid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BranchChangeRequestId) ) return false;
		 BranchChangeRequestId castOther = ( BranchChangeRequestId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getStudentid()==castOther.getStudentid()) || ( this.getStudentid()!=null && castOther.getStudentid()!=null && this.getStudentid().equals(castOther.getStudentid()) ) )
 && ( (this.getProgramid()==castOther.getProgramid()) || ( this.getProgramid()!=null && castOther.getProgramid()!=null && this.getProgramid().equals(castOther.getProgramid()) ) )
 && ( (this.getBranchid()==castOther.getBranchid()) || ( this.getBranchid()!=null && castOther.getBranchid()!=null && this.getBranchid().equals(castOther.getBranchid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getStudentid() == null ? 0 : this.getStudentid().hashCode() );
         result = 37 * result + ( getProgramid() == null ? 0 : this.getProgramid().hashCode() );
         result = 37 * result + ( getBranchid() == null ? 0 : this.getBranchid().hashCode() );
         return result;
   }   


}


