package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * CategoryProgramDocumentTaggingId generated by hbm2java
 */
public class CategoryProgramDocumentTaggingId  implements java.io.Serializable {


     private String instituteid;
     private String categoryid;
     private String programid;
     private String documentid;

    public CategoryProgramDocumentTaggingId() {
    }

    public CategoryProgramDocumentTaggingId(String instituteid, String categoryid, String programid, String documentid) {
       this.instituteid = instituteid;
       this.categoryid = categoryid;
       this.programid = programid;
       this.documentid = documentid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getDocumentid() {
        return this.documentid;
    }
    
    public void setDocumentid(String documentid) {
        this.documentid = documentid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryProgramDocumentTaggingId) ) return false;
		 CategoryProgramDocumentTaggingId castOther = ( CategoryProgramDocumentTaggingId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getCategoryid()==castOther.getCategoryid()) || ( this.getCategoryid()!=null && castOther.getCategoryid()!=null && this.getCategoryid().equals(castOther.getCategoryid()) ) )
 && ( (this.getProgramid()==castOther.getProgramid()) || ( this.getProgramid()!=null && castOther.getProgramid()!=null && this.getProgramid().equals(castOther.getProgramid()) ) )
 && ( (this.getDocumentid()==castOther.getDocumentid()) || ( this.getDocumentid()!=null && castOther.getDocumentid()!=null && this.getDocumentid().equals(castOther.getDocumentid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getCategoryid() == null ? 0 : this.getCategoryid().hashCode() );
         result = 37 * result + ( getProgramid() == null ? 0 : this.getProgramid().hashCode() );
         result = 37 * result + ( getDocumentid() == null ? 0 : this.getDocumentid().hashCode() );
         return result;
   }   


}


