package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * CityMasterId generated by hbm2java
 */
public class CityMasterId  implements java.io.Serializable {


     private String countryid;
     private String stateid;
     private String cityid;

    public CityMasterId() {
    }

    public CityMasterId(String countryid, String stateid, String cityid) {
       this.countryid = countryid;
       this.stateid = stateid;
       this.cityid = cityid;
    }
   
    public String getCountryid() {
        return this.countryid;
    }
    
    public void setCountryid(String countryid) {
        this.countryid = countryid;
    }
    public String getStateid() {
        return this.stateid;
    }
    
    public void setStateid(String stateid) {
        this.stateid = stateid;
    }
    public String getCityid() {
        return this.cityid;
    }
    
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CityMasterId) ) return false;
		 CityMasterId castOther = ( CityMasterId ) other; 
         
		 return ( (this.getCountryid()==castOther.getCountryid()) || ( this.getCountryid()!=null && castOther.getCountryid()!=null && this.getCountryid().equals(castOther.getCountryid()) ) )
 && ( (this.getStateid()==castOther.getStateid()) || ( this.getStateid()!=null && castOther.getStateid()!=null && this.getStateid().equals(castOther.getStateid()) ) )
 && ( (this.getCityid()==castOther.getCityid()) || ( this.getCityid()!=null && castOther.getCityid()!=null && this.getCityid().equals(castOther.getCityid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountryid() == null ? 0 : this.getCountryid().hashCode() );
         result = 37 * result + ( getStateid() == null ? 0 : this.getStateid().hashCode() );
         result = 37 * result + ( getCityid() == null ? 0 : this.getCityid().hashCode() );
         return result;
   }   


}


