package com.jilit.irp.persistence.dto;
// Generated Oct 12, 2010 11:07:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CommitteeMembers generated by hbm2java
 */
public class CommitteeMembers  implements java.io.Serializable
{
     private CommitteeMembersId id;
     private CommitteeMaster committeemaster;
     private CommitteeFormation committeeformation;
     private DesignationMaster designationmaster;


     private Date formationdate;
     private Date activetilldate;
     private String designationid;
     private String deactive;
     private Set <CommitteeMeetingParticipents> committeemeetingparticipentses = new HashSet <CommitteeMeetingParticipents>(0);

    public CommitteeMembers(CommitteeMembers dto)
        {
        this.id=dto.getId();
        //this.committeemaster=dto.getCommitteemaster();
        //this.committeeformation=dto.getCommitteeformation();
        this.formationdate=dto.getFormationdate();
        this.activetilldate=dto.getActivetilldate();
        this.designationid=dto.getDesignationid();
        this.deactive=dto.getDeactive();
          }

    public Set<CommitteeMeetingParticipents> getCommitteemeetingparticipentses() {
        return committeemeetingparticipentses;
    }

    public void setCommitteemeetingparticipentses(Set<CommitteeMeetingParticipents> committeemeetingparticipentses) {
        this.committeemeetingparticipentses = committeemeetingparticipentses;
    }

     public CommitteeMembers()
     {
     }

    public CommitteeMembers(CommitteeMembersId id, CommitteeMaster committeemaster, Date formationdate) {
        this.id = id;
        this.committeemaster = committeemaster;
        this.formationdate = formationdate;
    }
    public CommitteeMembers(CommitteeMembersId id, CommitteeMaster committeemaster, Date formationdate, Date activetilldate, String designationid, String deactive, Set committeemeetingparticipentses) {
       this.id = id;
       this.committeemaster = committeemaster;
       this.formationdate = formationdate;
       this.activetilldate = activetilldate;
       this.designationid = designationid;
       this.deactive = deactive;
       this.committeemeetingparticipentses = committeemeetingparticipentses;
    }

    public CommitteeMembersId getId() {
        return this.id;
    }

    public void setId(CommitteeMembersId id) {
        this.id = id;
    }
    public CommitteeMaster getCommitteemaster() {
        return this.committeemaster;
    }

    public void setCommitteemaster(CommitteeMaster committeemaster) {
        this.committeemaster = committeemaster;
    }
    public Date getFormationdate() {
        return this.formationdate;
    }

    public void setFormationdate(Date formationdate) {
        this.formationdate = formationdate;
    }
    public Date getActivetilldate() {
        return this.activetilldate;
    }

    public void setActivetilldate(Date activetilldate) {
        this.activetilldate = activetilldate;
    }
    public String getDesignationid() {
        return this.designationid;
    }

    public void setDesignationid(String designationid) {
        this.designationid = designationid;
    }
    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }



    public CommitteeFormation getCommitteeformation() {
        return committeeformation;
    }

    public void setCommitteeformation(CommitteeFormation committeeformation) {
        this.committeeformation = committeeformation;
    }


public String getIdStr() {
        return id.getInstituteid()+":"+id.getCommitteeid()+":"+id.getFormationid()+":"+id.getStafftype()+":"+id.getStaffid();
    }
 public DesignationMaster getDesignationmaster() {
        return designationmaster;
    }

    public void setDesignationmaster(DesignationMaster designationmaster) {
        this.designationmaster = designationmaster;
    }
}