package com.jilit.irp.persistence.dto;
// Generated Oct 12, 2010 11:07:25 AM by Hibernate Tools 3.2.1.GA



/**
 * CommitteeMembersId generated by hbm2java
 */
public class CommitteeMembersId  implements java.io.Serializable {


     private String instituteid;
     private String committeeid;
     private String formationid;
     private String stafftype;
     private String staffid;

    public CommitteeMembersId() {
    }

    public CommitteeMembersId(String instituteid, String committeeid, String formationid, String stafftype, String staffid) {
       this.instituteid = instituteid;
       this.committeeid = committeeid;
       this.formationid = formationid;
       this.stafftype = stafftype;
       this.staffid = staffid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getCommitteeid() {
        return this.committeeid;
    }
    
    public void setCommitteeid(String committeeid) {
        this.committeeid = committeeid;
    }
    public String getFormationid() {
        return this.formationid;
    }
    
    public void setFormationid(String formationid) {
        this.formationid = formationid;
    }
    public String getStafftype() {
        return this.stafftype;
    }
    
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }



}


