package com.jilit.irp.persistence.dto;
// Generated Oct 12, 2010 11:07:25 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CommitteeActionType generated by hbm2java
 */
public class CommitteeActionType  implements java.io.Serializable {


     private CommitteeActionTypeId id;
     private InstituteMaster institutemaster;
     private String actiondesc;
     private String deactive;
     private String actiontypeflag;
     private Set <CommitteeActionDetail> committeeactiondetails = new HashSet <CommitteeActionDetail>(0);
     private Set <CommitteeFormation> committeeformations = new HashSet <CommitteeFormation>(0);
     private Set <CommitteeActionDetail> committeeactiondetails1 = new HashSet <CommitteeActionDetail>(0);

         public CommitteeActionType() {
    }

     public CommitteeActionType(CommitteeActionType dto) {
        this.id=dto.getId();
        this.actiondesc=dto.getActiondesc();
        this.deactive=dto.getDeactive();
    }

    public CommitteeActionType(CommitteeActionType dto, boolean childReqd) {
        this.id=dto.getId();
        this.actiondesc=dto.getActiondesc();
        this.deactive=dto.getDeactive();
    }


    public CommitteeActionType(CommitteeActionTypeId id, InstituteMaster institutemaster, String actiondesc) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.actiondesc = actiondesc;
    }

    public CommitteeActionType(CommitteeActionTypeId id, InstituteMaster institutemaster, String actiondesc, String deactive, Set committeeactiondetails) {
       this.id = id;
       this.institutemaster = institutemaster;
       this.actiondesc = actiondesc;
       this.deactive = deactive;
       this.committeeactiondetails = committeeactiondetails;
    }

    /**
     * @return the id
     */
    public CommitteeActionTypeId getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(CommitteeActionTypeId id) {
        this.id = id;
    }

    /**
     * @return the institutemaster
     */
    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    /**
     * @param institutemaster the institutemaster to set
     */
    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    /**
     * @return the actiondesc
     */
    public String getActiondesc() {
        return actiondesc;
    }

    /**
     * @param actiondesc the actiondesc to set
     */
    public void setActiondesc(String actiondesc) {
        this.actiondesc = actiondesc;
    }

    /**
     * @return the deactive
     */
    public String getDeactive() {
        return deactive;
    }

    /**
     * @param deactive the deactive to set
     */
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    /**
     * @return the committeeactiondetails
     */
    public Set<CommitteeActionDetail> getCommitteeactiondetails() {
        return committeeactiondetails;
    }

    /**
     * @param committeeactiondetails the committeeactiondetails to set
     */
    public void setCommitteeactiondetails(Set<CommitteeActionDetail> committeeactiondetails) {
        this.committeeactiondetails = committeeactiondetails;
    }
   public String getIdStr() {
        return id.getInstituteid()+":"+id.getActiontypeid();
    }
     

    public Set<CommitteeFormation> getCommitteeformations() {
        return committeeformations;
    }

    public void setCommitteeformations(Set<CommitteeFormation> committeeformations) {
        this.committeeformations = committeeformations;
    }
   public Set<CommitteeActionDetail> getCommitteeactiondetails1() {
        return committeeactiondetails1;
    }

    public void setCommitteeactiondetails1(Set<CommitteeActionDetail> committeeactiondetails1) {
        this.committeeactiondetails1 = committeeactiondetails1;
    }

    public String getActiontypeflag() {
        return actiontypeflag;
    }

    public void setActiontypeflag(String actiontypeflag) {
        this.actiontypeflag = actiontypeflag;
    }

}

