package com.jilit.irp.persistence.dto;
// Generated 24 Jan, 2014 2:25:22 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Complainticketreply generated by hbm2java
 */
public class ComplainTicketReply  implements java.io.Serializable {


     private ComplainTicketReplyId id;
     private ComplainTicketMaster complainticketmaster;
     private String replyno;
     private String modeofreply;
     private String replybypersonid;
     private String tomailid;
     private String replydesc;
     private String replyattachementfile;
     private Date replydatetime;
     private String ipaddress;
     private String deactive;

    public ComplainTicketReply() {
    }

    public ComplainTicketReply(ComplainTicketReply dto) {
        this.id=dto.getId();
        this.deactive=dto.getDeactive();
        this.ipaddress=dto.getIpaddress();
        this.modeofreply=dto.getModeofreply();
        this.replyattachementfile=dto.getReplyattachementfile();
        this.replybypersonid=dto.getReplybypersonid();
        this.replydatetime=dto.getReplydatetime();
        this.replydesc=dto.getReplydesc();
        this.replyno=dto.getReplyno();
        this.tomailid=dto.getTomailid();
    }

	
    public ComplainTicketReply(ComplainTicketReplyId id, ComplainTicketMaster complainticketmaster, String modeofreply, String replybypersonid, String replydesc, Date replydatetime) {
        this.id = id;
        this.complainticketmaster = complainticketmaster;
        this.modeofreply = modeofreply;
        this.replybypersonid = replybypersonid;
        this.replydesc = replydesc;
        this.replydatetime = replydatetime;
    }
    public ComplainTicketReply(ComplainTicketReplyId id, ComplainTicketMaster complainticketmaster, String modeofreply, String replybypersonid, String tomailid, String replydesc, String replyattachementfile, Date replydatetime, String ipaddress, String deactive) {
       this.id = id;
       this.complainticketmaster = complainticketmaster;
       this.modeofreply = modeofreply;
       this.replybypersonid = replybypersonid;
       this.tomailid = tomailid;
       this.replydesc = replydesc;
       this.replyattachementfile = replyattachementfile;
       this.replydatetime = replydatetime;
       this.ipaddress = ipaddress;
       this.deactive = deactive;
    }
   
    public ComplainTicketReplyId getId() {
        return this.id;
    }

    public String getIdStr() {
       return id.getCtreplyid()+":"+id.getCtid();
    }
    
    public void setId(ComplainTicketReplyId id) {
        this.id = id;
    }
    public ComplainTicketMaster getComplainticketmaster() {
        return this.complainticketmaster;
    }
    
    public void setComplainticketmaster(ComplainTicketMaster complainticketmaster) {
        this.complainticketmaster = complainticketmaster;
    }
    public String getModeofreply() {
        return this.modeofreply;
    }
    
    public void setModeofreply(String modeofreply) {
        this.modeofreply = modeofreply;
    }
    public String getReplybypersonid() {
        return this.replybypersonid;
    }
    
    public void setReplybypersonid(String replybypersonid) {
        this.replybypersonid = replybypersonid;
    }
    public String getTomailid() {
        return this.tomailid;
    }
    
    public void setTomailid(String tomailid) {
        this.tomailid = tomailid;
    }
    public String getReplydesc() {
        return this.replydesc;
    }
    
    public void setReplydesc(String replydesc) {
        this.replydesc = replydesc;
    }
    public String getReplyattachementfile() {
        return this.replyattachementfile;
    }
    
    public void setReplyattachementfile(String replyattachementfile) {
        this.replyattachementfile = replyattachementfile;
    }
    public Date getReplydatetime() {
        return this.replydatetime;
    }
    
    public void setReplydatetime(Date replydatetime) {
        this.replydatetime = replydatetime;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getReplyno() {
        return replyno;
    }

    public void setReplyno(String replyno) {
        this.replyno = replyno;
    }
    


}


