package com.jilit.irp.persistence.dto;
// Generated Apr 21, 2011 3:02:39 PM by Hibernate Tools 3.2.1.GA

import java.sql.Blob;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import org.hibernate.Hibernate;

/**
 * CurrencyMaster generated by hbm2java this is DTO for CurrencyMaster
 */
public class CurrencyMaster implements java.io.Serializable {

    private String currencyid;
    private String currencycode;
    private String currencydesc;
    private Blob currencyimage;
    private String accountingcurrency;
    private Short seqid;
    private String deactive;
    private Set<FeeStructureIndividual> feestructureindividuals = new HashSet<FeeStructureIndividual>(0);

    @Override
    public String toString() {
        return "CurrencyMaster{" + "currencyid=" + currencyid + ", currencycode=" + currencycode + ", currencydesc=" + currencydesc + ", currencyimage=" + currencyimage + ", accountingcurrency=" + accountingcurrency + ", seqid=" + seqid + ", deactive=" + deactive + ", feestructureindividuals=" + feestructureindividuals + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.currencyid);
        hash = 11 * hash + Objects.hashCode(this.currencycode);
        hash = 11 * hash + Objects.hashCode(this.currencydesc);
        hash = 11 * hash + Objects.hashCode(this.currencyimage);
        hash = 11 * hash + Objects.hashCode(this.accountingcurrency);
        hash = 11 * hash + Objects.hashCode(this.seqid);
        hash = 11 * hash + Objects.hashCode(this.deactive);
        hash = 11 * hash + Objects.hashCode(this.feestructureindividuals);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CurrencyMaster other = (CurrencyMaster) obj;
        if (!Objects.equals(this.currencyid, other.currencyid)) {
            return false;
        }
        if (!Objects.equals(this.currencycode, other.currencycode)) {
            return false;
        }
        if (!Objects.equals(this.currencydesc, other.currencydesc)) {
            return false;
        }
        if (!Objects.equals(this.accountingcurrency, other.accountingcurrency)) {
            return false;
        }
        if (!Objects.equals(this.deactive, other.deactive)) {
            return false;
        }
        if (!Objects.equals(this.currencyimage, other.currencyimage)) {
            return false;
        }
        if (!Objects.equals(this.seqid, other.seqid)) {
            return false;
        }
        if (!Objects.equals(this.feestructureindividuals, other.feestructureindividuals)) {
            return false;
        }
        return true;
    }

    public CurrencyMaster() {
    }

    public CurrencyMaster(CurrencyMaster currencyMaster) {
        this.currencyid = currencyMaster.getCurrencyid();
        this.currencycode = currencyMaster.getCurrencycode();
        this.currencydesc = currencyMaster.getCurrencydesc();
        this.accountingcurrency = currencyMaster.getAccountingcurrency();
        this.seqid = currencyMaster.getSeqid();
        this.deactive = currencyMaster.getDeactive();
        this.currencyimage = currencyMaster.getCurrencyimage();
    }

    public CurrencyMaster(String currencyid, String currencycode, String currencydesc) {
        this.currencyid = currencyid;
        this.currencycode = currencycode;
        this.currencydesc = currencydesc;
    }

    public CurrencyMaster(String currencyid, String currencycode, String currencydesc, Blob currencyimage, String accountingcurrency, Short seqid, String deactive, Set feestructureindividuals) {
        this.currencyid = currencyid;
        this.currencycode = currencycode;
        this.currencydesc = currencydesc;
        this.currencyimage = currencyimage;
        this.accountingcurrency = accountingcurrency;
        this.seqid = seqid;
        this.deactive = deactive;
        this.feestructureindividuals = feestructureindividuals;
    }

    public String getCurrencyid() {
        return this.currencyid;
    }

    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid;
    }

    public String getCurrencycode() {
        return this.currencycode;
    }

    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    public String getCurrencydesc() {
        return this.currencydesc;
    }

    public void setCurrencydesc(String currencydesc) {
        this.currencydesc = currencydesc;
    }

    public Blob getCurrencyimage() {
        return this.currencyimage;
    }

    public void setCurrencyimage(Blob currencyimage) {
        this.currencyimage = currencyimage;
    }

    public String getAccountingcurrency() {
        return this.accountingcurrency;
    }

    public void setAccountingcurrency(String accountingcurrency) {
        this.accountingcurrency = accountingcurrency;
    }

    public Short getSeqid() {
        return this.seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<FeeStructureIndividual> getFeestructureindividuals() {
        return feestructureindividuals;
    }

    public void setFeestructureindividuals(Set<FeeStructureIndividual> feestructureindividuals) {
        this.feestructureindividuals = feestructureindividuals;
    }

    public CurrencyMaster(String currencyid, String currencycode) {
        this.currencyid = currencyid;
        this.currencycode = currencycode;

    }


    public void setCurrencyimage(byte[] currencyimage) {
        this.currencyimage = Hibernate.createBlob(currencyimage);
    }
    
}


