package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * DepartmentWiseHodId generated by hbm2java
 */
public class DepartmentWiseHodId  implements java.io.Serializable {


   
     private String stafftype;
     private String staffid;
     private String instituteid;
     private String departmentid;
     private Date formdate;
    public DepartmentWiseHodId() {
    }

    public DepartmentWiseHodId( String stafftype, String staffid, String instituteid, String departmentid, Date formdate) {
       
       this.stafftype = stafftype;
       this.staffid = staffid;
       this.instituteid = instituteid;
       this.departmentid = departmentid;
       this.formdate = formdate;
    }
   
    
    public String getStafftype() {
        return this.stafftype;
    }
    
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

     /**
     * @return the formdate
     */
    public Date getFormdate() {
        return this.formdate;
    }

    /**
     * @param formdate the formdate to set
     */
    public void setFormdate(Date formdate) {
        this.formdate = formdate;
    }


 /*  public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepartmentWiseHodId) ) return false;
		 DepartmentWiseHodId castOther = ( DepartmentWiseHodId ) other; 
         
		 return  ( (this.getStafftype()==castOther.getStafftype()) || ( this.getStafftype()!=null && castOther.getStafftype()!=null && this.getStafftype().equals(castOther.getStafftype()) ) )
 && ( (this.getStaffid()==castOther.getStaffid()) || ( this.getStaffid()!=null && castOther.getStaffid()!=null && this.getStaffid().equals(castOther.getStaffid()) ) )
 && ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getDepartmentid()==castOther.getDepartmentid()) || ( this.getDepartmentid()!=null && castOther.getDepartmentid()!=null && this.getDepartmentid().equals(castOther.getDepartmentid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getStafftype() == null ? 0 : this.getStafftype().hashCode() );
         result = 37 * result + ( getStaffid() == null ? 0 : this.getStaffid().hashCode() );
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getDepartmentid() == null ? 0 : this.getDepartmentid().hashCode() );
         return result;
   }*/

   


}


