package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * DepartmentBranchTaggingId generated by hbm2java
 */
public class DepartmentBranchTaggingId  implements java.io.Serializable {


     private String instituteid;
     private String departmentid;
     private String programid;
     private String branchid;

    public DepartmentBranchTaggingId() {
    }

    public DepartmentBranchTaggingId(String instituteid, String departmentid, String programid, String branchid) {
       this.instituteid = instituteid;     
       this.departmentid = departmentid;
       this.programid = programid;
       this.branchid = branchid;
    }
   
    public DepartmentBranchTaggingId(DepartmentBranchTaggingId dto) {
        this.instituteid = dto.getInstituteid();
        this.departmentid = dto.getDepartmentid();
        this.programid = dto.getProgramid();
        this.branchid = dto.getBranchid();
    }

    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    
    public String getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getBranchid() {
        return this.branchid;
    }
    
    public void setBranchid(String branchid) {
        this.branchid = branchid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepartmentBranchTaggingId) ) return false;
		 DepartmentBranchTaggingId castOther = ( DepartmentBranchTaggingId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getDepartmentid()==castOther.getDepartmentid()) || ( this.getDepartmentid()!=null && castOther.getDepartmentid()!=null && this.getDepartmentid().equals(castOther.getDepartmentid()) ) )
 && ( (this.getProgramid()==castOther.getProgramid()) || ( this.getProgramid()!=null && castOther.getProgramid()!=null && this.getProgramid().equals(castOther.getProgramid()) ) )
 && ( (this.getBranchid()==castOther.getBranchid()) || ( this.getBranchid()!=null && castOther.getBranchid()!=null && this.getBranchid().equals(castOther.getBranchid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getDepartmentid() == null ? 0 : this.getDepartmentid().hashCode() );
         result = 37 * result + ( getProgramid() == null ? 0 : this.getProgramid().hashCode() );
         result = 37 * result + ( getBranchid() == null ? 0 : this.getBranchid().hashCode() );
         return result;
   }   


}


