package com.jilit.irp.persistence.dto;
// Generated Jan 7, 2017 10:17:58 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Eligibilityexaminfodetail generated by hbm2java
 */
public class EligibilityExamInfoDetail  implements java.io.Serializable {


     private EligibilityExamInfoDetailId id;
     private EligibilityExamInfo eligibilityexaminfo;
     private String eeinfoshortname;
     private String eeinfoname;
     private String eeetypeofinfo;
     private Short seqid;
     private Set studenteligibilityexaminfos = new HashSet(0);

    public EligibilityExamInfoDetail() {
    }

    public EligibilityExamInfoDetail(EligibilityExamInfoDetail master) {
          this.id = id;
           this.eeinfoshortname = master.eeinfoshortname;
           this.eeinfoname = master.eeinfoname;
           this.eeetypeofinfo = master.eeetypeofinfo;
           this.seqid = master.seqid;
    }


    public EligibilityExamInfoDetail(EligibilityExamInfoDetailId id, EligibilityExamInfo eligibilityexaminfo, String eeinfoshortname, String eeinfoname) {
        this.id = id;
        this.eligibilityexaminfo = eligibilityexaminfo;
        this.eeinfoshortname = eeinfoshortname;
        this.eeinfoname = eeinfoname;
    }
    public EligibilityExamInfoDetail(EligibilityExamInfoDetailId id, EligibilityExamInfo eligibilityexaminfo, String eeinfoshortname, String eeinfoname, String eeetypeofinfo, Short seqid, Set studenteligibilityexaminfos) {
       this.id = id;
       this.eligibilityexaminfo = eligibilityexaminfo;
       this.eeinfoshortname = eeinfoshortname;
       this.eeinfoname = eeinfoname;
       this.eeetypeofinfo = eeetypeofinfo;
       this.seqid = seqid;
       this.studenteligibilityexaminfos = studenteligibilityexaminfos;
    }

    public EligibilityExamInfoDetailId getId() {
        return this.id;
    }

    public void setId(EligibilityExamInfoDetailId id) {
        this.id = id;
    }
    public EligibilityExamInfo getEligibilityexaminfo() {
        return this.eligibilityexaminfo;
    }

    public void setEligibilityexaminfo(EligibilityExamInfo eligibilityexaminfo) {
        this.eligibilityexaminfo = eligibilityexaminfo;
    }
    public String getEeinfoshortname() {
        return this.eeinfoshortname;
    }

    public void setEeinfoshortname(String eeinfoshortname) {
        this.eeinfoshortname = eeinfoshortname;
    }
    public String getEeinfoname() {
        return this.eeinfoname;
    }

    public void setEeinfoname(String eeinfoname) {
        this.eeinfoname = eeinfoname;
    }
    public String getEeetypeofinfo() {
        return this.eeetypeofinfo;
    }

    public void setEeetypeofinfo(String eeetypeofinfo) {
        this.eeetypeofinfo = eeetypeofinfo;
    }

    public Short getSeqid() {
        return seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }
 
    public Set getStudenteligibilityexaminfos() {
        return this.studenteligibilityexaminfos;
    }

    public void setStudenteligibilityexaminfos(Set studenteligibilityexaminfos) {
        this.studenteligibilityexaminfos = studenteligibilityexaminfos;
    }
    public String getIdStr() {
        return (id.getInstituteid() + "::" + id.getEeexamid()+ "::" +id.getEeinfoid());
    }




}


