package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeType generated by hbm2java
 */
public class EmployeeType  implements java.io.Serializable {
     private String companyid;
     private String employeetypeid;
     private String employeetype;
     private String employeetypedesc;
     private Short seqid;
     private String deactive;
     


    public EmployeeType() {
    }

    public EmployeeType(EmployeeType dto) {
       this.employeetypeid = dto.getEmployeetypeid();
       this.employeetype = dto.getEmployeetype();
       this.employeetypedesc = dto.getEmployeetypedesc();
       this.seqid = dto.getSeqid();
       this.deactive = dto.getDeactive();
    }

	
    public EmployeeType(String employeetypeid, String employeetype,  String employeetypedesc) {
        this.employeetypeid = employeetypeid;
       
    }
    public EmployeeType(String employeetypeid, String employeetype, String employeetypedesc, Short seqid, String deactive ) {
       this.employeetypeid = employeetypeid;
       this.employeetype = employeetype;
       this.employeetypedesc = employeetypedesc;
       this.seqid = seqid;
       this.deactive = deactive;
      
    }
   
  
 
  
    public Short getSeqid() {
        return this.seqid;
    }
    
    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
 

    public String getEmployeetype() {
        return employeetype;
    }

    public void setEmployeetype(String employeetype) {
        this.employeetype = employeetype;
    }

    public String getEmployeetypedesc() {
        return employeetypedesc;
    }

    public void setEmployeetypedesc(String employeetypedesc) {
        this.employeetypedesc = employeetypedesc;
    }

    public String getEmployeetypeid() {
        return employeetypeid;
    }

    public void setEmployeetypeid(String employeetypeid) {
        this.employeetypeid = employeetypeid;
    }

    public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
 
    



}


