package com.jilit.irp.persistence.dto;
// Generated 31 Oct, 2011 5:41:27 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Examgrademasterdetail generated by hbm2java
 */
public class ExamGradeMasterDetail  implements java.io.Serializable {


     private ExamGradeMasterDetailId id;
     private ProgramMaster programmaster;
     private Academicyear academicyear;
     private ExamGradeMaster examgrademaster;
     private RegistrationMaster registrationmaster;
     private BigDecimal highgradecalclimit;
     private BigDecimal lowgradecalclimit;
     private String hideingradesheet;
     private String eccalculation;
     private String cccalculation;
     private String sgpacalculationbasedon;
     private String cgpacalculationbasedon;
     private String deactive;
     private BigDecimal gradepoints;
     private String failtype;
     private BigDecimal calculationvalue;
     private String calculationtype;
     private Date entrydate;

    public ExamGradeMasterDetail() {
    }
public ExamGradeMasterDetail(ExamGradeMasterDetail dto) {
       this.id = dto.getId();
       this.highgradecalclimit=dto.getHighgradecalclimit();
       this.lowgradecalclimit=dto.getLowgradecalclimit();
       this.hideingradesheet=dto.getHideingradesheet();
       this.deactive=dto.getDeactive();
       this.eccalculation=dto.getEccalculation();
       this.cccalculation=dto.getCccalculation();
       this.sgpacalculationbasedon=dto.getSgpacalculationbasedon();
       this.cgpacalculationbasedon=dto.getCgpacalculationbasedon();
       this.gradepoints = dto.getGradepoints();
       this.failtype = dto.getFailtype();
       this.calculationvalue = dto.getCalculationvalue();
       this.calculationtype = dto.getCalculationtype();
    }
	
    public ExamGradeMasterDetail(ExamGradeMasterDetailId id, ProgramMaster programmaster, Academicyear academicyear, ExamGradeMaster examgrademaster, RegistrationMaster registrationmaster, String sgpacalculationbasedon, String cgpacalculationbasedon) {
        this.id = id;
        this.programmaster = programmaster;
        this.academicyear = academicyear;
        this.examgrademaster = examgrademaster;
        this.registrationmaster = registrationmaster;
        this.sgpacalculationbasedon = sgpacalculationbasedon;
        this.cgpacalculationbasedon = cgpacalculationbasedon;
        
    }
    public ExamGradeMasterDetail(ExamGradeMasterDetailId id, ProgramMaster programmaster, Academicyear academicyear, ExamGradeMaster examgrademaster, RegistrationMaster registrationmaster, BigDecimal highgradecalclimit, BigDecimal lowgradecalclimit, String hideingradesheet, String eccalculation, String cccalculation, String sgpacalculationbasedon, String cgpacalculationbasedon, String deactive) {
       this.id = id;
       this.programmaster = programmaster;
       this.academicyear = academicyear;
       this.examgrademaster = examgrademaster;
       this.registrationmaster = registrationmaster;
       this.highgradecalclimit = highgradecalclimit;
       this.lowgradecalclimit = lowgradecalclimit;
       this.hideingradesheet = hideingradesheet;
       this.eccalculation = eccalculation;
       this.cccalculation = cccalculation;
       this.sgpacalculationbasedon = sgpacalculationbasedon;
       this.cgpacalculationbasedon = cgpacalculationbasedon;
       this.deactive = deactive;
       
    }
   
    public ExamGradeMasterDetailId getId() {
        return this.id;
    }
    
    public void setId(ExamGradeMasterDetailId id) {
        this.id = id;
    }
    public ProgramMaster getProgrammaster() {
        return this.programmaster;
    }
    
    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }
    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }
    public ExamGradeMaster getExamgrademaster() {
        return this.examgrademaster;
    }
    
    public void setExamgrademaster(ExamGradeMaster examgrademaster) {
        this.examgrademaster = examgrademaster;
    }
    public RegistrationMaster getRegistrationmaster() {
        return this.registrationmaster;
    }
    
    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }
    public BigDecimal getHighgradecalclimit() {
        return this.highgradecalclimit;
    }
    
    public void setHighgradecalclimit(BigDecimal highgradecalclimit) {
        this.highgradecalclimit = highgradecalclimit;
    }
    public BigDecimal getLowgradecalclimit() {
        return this.lowgradecalclimit;
    }
    
    public void setLowgradecalclimit(BigDecimal lowgradecalclimit) {
        this.lowgradecalclimit = lowgradecalclimit;
    }
    public String getHideingradesheet() {
        return this.hideingradesheet;
    }
    
    public void setHideingradesheet(String hideingradesheet) {
        this.hideingradesheet = hideingradesheet;
    }
    public String getEccalculation() {
        return this.eccalculation;
    }
    
    public void setEccalculation(String eccalculation) {
        this.eccalculation = eccalculation;
    }
    public String getCccalculation() {
        return this.cccalculation;
    }
    
    public void setCccalculation(String cccalculation) {
        this.cccalculation = cccalculation;
    }
    public String getSgpacalculationbasedon() {
        return this.sgpacalculationbasedon;
    }
    
    public void setSgpacalculationbasedon(String sgpacalculationbasedon) {
        this.sgpacalculationbasedon = sgpacalculationbasedon;
    }
    public String getCgpacalculationbasedon() {
        return this.cgpacalculationbasedon;
    }
    
    public void setCgpacalculationbasedon(String cgpacalculationbasedon) {
        this.cgpacalculationbasedon = cgpacalculationbasedon;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    
    public String getCalculationtype() {
        return calculationtype;
    }

    public void setCalculationtype(String calculationtype) {
        this.calculationtype = calculationtype;
    }

    public BigDecimal getCalculationvalue() {
        return calculationvalue;
    }

    public void setCalculationvalue(BigDecimal calculationvalue) {
        this.calculationvalue = calculationvalue;
    }

    public String getFailtype() {
        return failtype;
    }

    public void setFailtype(String failtype) {
        this.failtype = failtype;
    }

    public BigDecimal getGradepoints() {
        return gradepoints;
    }

    public void setGradepoints(BigDecimal gradepoints) {
        this.gradepoints = gradepoints;
    }

     public String getIdStr() {
     return id.getInstituteid()+":"+id.getAcademicyear()+":"+id.getProgramid()+":"+id.getGradeid()+":"+id.getRegistrationid();
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }


}


