/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jilit.irp.persistence.dto;
// Generated Oct 3, 2010 8:28:34 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.Date;

/**
 * Examgrademaster generated by hbm2java
 */
public class ExamGradeMaster implements java.io.Serializable {

    private ExamGradeMasterId id;
    private InstituteMaster institutemaster;
    private String grade;
    private String gradedesc;
    private Short graderank;
    private String deactive;
    private Short sqno;
    private Date entrybydate;
    private Set<Setup_GIPCriteriaDetail> setup_GIPCriteriaDetail = new HashSet<Setup_GIPCriteriaDetail>(0);

    public ExamGradeMaster() {
    }

    public ExamGradeMaster(ExamGradeMasterId id, InstituteMaster institutemaster, String grade, String gradedesc, Short graderank, String deactive, Short sqno, Date entrybydate) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.grade = grade;
        this.gradedesc = gradedesc;
        this.graderank = graderank;
        this.deactive = deactive;
        this.sqno = sqno;
        this.entrybydate = entrybydate;
    }

    public ExamGradeMasterId getId() {
        return id;
    }

    public void setId(ExamGradeMasterId id) {
        this.id = id;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getGradedesc() {
        return gradedesc;
    }

    public void setGradedesc(String gradedesc) {
        this.gradedesc = gradedesc;
    }

    public Short getGraderank() {
        return graderank;
    }

    public void setGraderank(Short graderank) {
        this.graderank = graderank;
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Short getSqno() {
        return sqno;
    }

    public void setSqno(Short sqno) {
        this.sqno = sqno;
    }

    public Date getEntrybydate() {
        return entrybydate;
    }

    public void setEntrybydate(Date entrybydate) {
        this.entrybydate = entrybydate;
    }

    public String getIdStr() {
        return id.getInstituteid() + ":" + id.getGradeid();
    }

    public Set<Setup_GIPCriteriaDetail> getSetup_GIPCriteriaDetail() {
        return setup_GIPCriteriaDetail;
    }

    public void setSetup_GIPCriteriaDetail(Set<Setup_GIPCriteriaDetail> setup_GIPCriteriaDetail) {
        this.setup_GIPCriteriaDetail = setup_GIPCriteriaDetail;
    }

}
