package com.jilit.irp.persistence.dto;
// Generated Sep 5, 2012 3:03:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Holidaymaster generated by hbm2java
 */
public class HolidayMaster  implements java.io.Serializable {


     private Date holidaydate;
     private String holidaytype;
     private String holidaydesc;
     private String holidayremarks;
     private String deactive;

    public HolidayMaster() {
    }

    public HolidayMaster(HolidayMaster dto ) {
        this.holidaydate=dto.getHolidaydate();
        this.holidaytype=dto.getHolidaytype();
        this.holidaydesc=dto.getHolidaydesc();
        this.holidayremarks=dto.getHolidayremarks();
        this.deactive=dto.getDeactive();

    }
	
    public HolidayMaster(Date holidaydate, String holidaytype) {
        this.holidaydate = holidaydate;
        this.holidaytype = holidaytype;
    }
       public HolidayMaster(Date holidaydate, String holidaytype, String holidaydesc, String holidayremarks, String deactive) {
       this.holidaydate = holidaydate;
       this.holidaytype = holidaytype;
       this.holidaydesc = holidaydesc;
       this.holidayremarks = holidayremarks;
       this.deactive = deactive;
    }
   
    public Date getHolidaydate() {
        return this.holidaydate;
    }
    
    public void setHolidaydate(Date holidaydate) {
        this.holidaydate = holidaydate;
    }
    public String getHolidaytype() {
        return this.holidaytype;
    }
    
    public void setHolidaytype(String holidaytype) {
        this.holidaytype = holidaytype;
    }
    public String getHolidaydesc() {
        return this.holidaydesc;
    }
    
    public void setHolidaydesc(String holidaydesc) {
        this.holidaydesc = holidaydesc;
    }
    public String getHolidayremarks() {
        return this.holidayremarks;
    }
    
    public void setHolidayremarks(String holidayremarks) {
        this.holidayremarks = holidayremarks;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


