package com.jilit.irp.persistence.dto;
// Generated Nov 4, 2016 3:38:16 PM by Hibernate Tools 3.2.1.GA

/**
 * Hostelauthorities generated by hbm2java
 */
public class HostelAuthorities implements java.io.Serializable {

    private HostelAuthoritiesId id;
    private HostelMaster hostelmaster;
    private String authoritytype;
    private String staffid;
    private String stafftype;
    private Byte authoritylevel;
    private String remarks;
    private String checkoutsmsrequired;
    private String checkoutemailrequired;
    private String deactive;
     private String HostelAuthorityid;

    public HostelAuthorities() {
    }

    public HostelAuthorities(HostelAuthorities master) {
        this.id = id;
        // this.hostelmaster = master.hostelmaster;
        this.authoritytype = master.authoritytype;
        this.staffid = master.staffid;
        this.stafftype = master.stafftype;
        this.authoritylevel = master.authoritylevel;
        this.remarks = master.remarks;
        this.checkoutsmsrequired = master.checkoutsmsrequired;
        this.checkoutemailrequired = master.checkoutemailrequired;
        this.deactive = master.deactive;
        this.HostelAuthorityid = master.HostelAuthorityid;
    }

    public HostelAuthorities(HostelAuthoritiesId id, HostelMaster hostelmaster, String authoritytype, String staffid, String stafftype) {
        this.id = id;
        this.hostelmaster = hostelmaster;
        this.authoritytype = authoritytype;
        this.staffid = staffid;
        this.stafftype = stafftype;
    }

    public HostelAuthorities(HostelAuthoritiesId id, HostelMaster hostelmaster, String authoritytype, String staffid, String stafftype, Byte authoritylevel, String remarks, String checkoutsmsrequired, String checkoutemailrequired, String deactive, String HostelAuthorityid) {
        this.id = id;
        this.hostelmaster = hostelmaster;
        this.authoritytype = authoritytype;
        this.staffid = staffid;
        this.stafftype = stafftype;
        this.authoritylevel = authoritylevel;
        this.remarks = remarks;
        this.checkoutsmsrequired = checkoutsmsrequired;
        this.checkoutemailrequired = checkoutemailrequired;
        this.deactive = deactive;
        this.HostelAuthorityid = HostelAuthorityid;
    }

    public HostelAuthoritiesId getId() {
        return this.id;
    }

    public void setId(HostelAuthoritiesId id) {
        this.id = id;
    }

    public HostelMaster getHostelmaster() {
        return this.hostelmaster;
    }

    public void setHostelmaster(HostelMaster hostelmaster) {
        this.hostelmaster = hostelmaster;
    }

    public String getAuthoritytype() {
        return this.authoritytype;
    }

    public void setAuthoritytype(String authoritytype) {
        this.authoritytype = authoritytype;
    }

    public String getStaffid() {
        return this.staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    public String getStafftype() {
        return this.stafftype;
    }

    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }

    public Byte getAuthoritylevel() {
        return this.authoritylevel;
    }

    public void setAuthoritylevel(Byte authoritylevel) {
        this.authoritylevel = authoritylevel;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCheckoutsmsrequired() {
        return this.checkoutsmsrequired;
    }

    public void setCheckoutsmsrequired(String checkoutsmsrequired) {
        this.checkoutsmsrequired = checkoutsmsrequired;
    }

    public String getCheckoutemailrequired() {
        return this.checkoutemailrequired;
    }

    public void setCheckoutemailrequired(String checkoutemailrequired) {
        this.checkoutemailrequired = checkoutemailrequired;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getIdStr() {
        return (id.getHostelid() + "::" + id.getSlno());
    }

    public String getHostelAuthorityid() {
        return HostelAuthorityid;
    }

    public void setHostelAuthorityid(String HostelAuthorityid) {
        this.HostelAuthorityid = HostelAuthorityid;
    }


// public HostelAuthorities(HostelAuthorities master) {
//
//    }
}


