package com.jilit.irp.persistence.dto;
// Generated Oct 30, 2009 1:34:49 PM by Hibernate Tools 3.2.1.GA



/**
 * IdGenerationControlId generated by hbm2java
 */
public class IdGenerationControlId  implements java.io.Serializable {


     private String icid;
     private String idcode;
     private String year;
     private String month;
     private char alpha;

    public IdGenerationControlId() {
    }

    public IdGenerationControlId(String icid, String idcode, String year, String month, char alpha) {
       this.icid = icid;
       this.idcode = idcode;
       this.year = year;
       this.month = month;
       this.alpha = alpha;
    }
   
    public String getIcid() {
        return this.icid;
    }
    
    public void setIcid(String icid) {
        this.icid = icid;
    }
    public String getIdcode() {
        return this.idcode;
    }
    
    public void setIdcode(String idcode) {
        this.idcode = idcode;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public char getAlpha() {
        return this.alpha;
    }
    
    public void setAlpha(char alpha) {
        this.alpha = alpha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IdGenerationControlId) ) return false;
		 IdGenerationControlId castOther = ( IdGenerationControlId ) other;
         
		 return ( (this.getIcid()==castOther.getIcid()) || ( this.getIcid()!=null && castOther.getIcid()!=null && this.getIcid().equals(castOther.getIcid()) ) )
 && ( (this.getIdcode()==castOther.getIdcode()) || ( this.getIdcode()!=null && castOther.getIdcode()!=null && this.getIdcode().equals(castOther.getIdcode()) ) )
 && ( (this.getYear()==castOther.getYear()) || ( this.getYear()!=null && castOther.getYear()!=null && this.getYear().equals(castOther.getYear()) ) )
 && ( (this.getMonth()==castOther.getMonth()) || ( this.getMonth()!=null && castOther.getMonth()!=null && this.getMonth().equals(castOther.getMonth()) ) )
 && (this.getAlpha()==castOther.getAlpha());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIcid() == null ? 0 : this.getIcid().hashCode() );
         result = 37 * result + ( getIdcode() == null ? 0 : this.getIdcode().hashCode() );
         result = 37 * result + ( getYear() == null ? 0 : this.getYear().hashCode() );
         result = 37 * result + ( getMonth() == null ? 0 : this.getMonth().hashCode() );
         result = 37 * result + this.getAlpha();
         return result;
   }   


}


