package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * InstituteIdControlId generated by hbm2java
 */
public class InstituteIdControlId  implements java.io.Serializable {


     private String instituteid;
     private String idcharacter;

    public InstituteIdControlId() {
    }

    public InstituteIdControlId(String instituteid, String idcharacter) {
       this.instituteid = instituteid;
       this.idcharacter = idcharacter;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getIdcharacter() {
        return this.idcharacter;
    }
    
    public void setIdcharacter(String idcharacter) {
        this.idcharacter = idcharacter;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InstituteIdControlId) ) return false;
		 InstituteIdControlId castOther = ( InstituteIdControlId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getIdcharacter()==castOther.getIdcharacter()) || ( this.getIdcharacter()!=null && castOther.getIdcharacter()!=null && this.getIdcharacter().equals(castOther.getIdcharacter()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getIdcharacter() == null ? 0 : this.getIdcharacter().hashCode() );
         return result;
   }   


}


