package com.jilit.irp.persistence.dto;
// Generated Oct 12, 2010 11:07:25 AM by Hibernate Tools 3.2.1.GA



/**
 * MeetingAgendaMasterId generated by hbm2java
 */
public class MeetingAgendaMasterId  implements java.io.Serializable {

     private String instituteid;
     private String committeeid;
     private String agendaid;

    public MeetingAgendaMasterId() {
    }

    public MeetingAgendaMasterId(MeetingAgendaMasterId dto) {
       this.instituteid = dto.getInstituteid();
       this.committeeid = dto.getCommitteeid();
       this.agendaid = dto.getAgendaid();
    }

    public MeetingAgendaMasterId(String instituteid, String committeeid, String agendaid) {
       this.instituteid = instituteid;
       this.committeeid = committeeid;
       this.agendaid = agendaid;
    }

    /**
     * @return the instituteid
     */
    public String getInstituteid() {
        return instituteid;
    }

    /**
     * @param instituteid the instituteid to set
     */
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }

    /**
     * @return the committeeid
     */
    public String getCommitteeid() {
        return committeeid;
    }

    /**
     * @param committeeid the committeeid to set
     */
    public void setCommitteeid(String committeeid) {
        this.committeeid = committeeid;
    }

    /**
     * @return the agendaid
     */
    public String getAgendaid() {
        return agendaid;
    }

    /**
     * @param agendaid the agendaid to set
     */
    public void setAgendaid(String agendaid) {
        this.agendaid = agendaid;
    }
   }


