package com.jilit.irp.persistence.dto;
// Generated Nov 10, 2010 7:35:01 PM by Hibernate Tools 3.2.1.GA



/**
 * MentormasterId generated by hbm2java
 */
public class MentorMasterId  implements java.io.Serializable {


     private String instituteid;
     private String mentortype;
     private String mentorid;
     private String programid;
     private String branchid;
     private String stynumber;

    public MentorMasterId() {
    }

    public MentorMasterId(String instituteid, String mentortype, String mentorid, String programid, String branchid, String stynumber) {
       this.instituteid = instituteid;
       this.mentortype = mentortype;
       this.mentorid = mentorid;
       this.programid = programid;
       this.branchid = branchid;
       this.stynumber = stynumber;
    }

    public String getInstituteid() {
        return this.instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getMentortype() {
        return this.mentortype;
    }

    public void setMentortype(String mentortype) {
        this.mentortype = mentortype;
    }
    public String getMentorid() {
        return this.mentorid;
    }

    public void setMentorid(String mentorid) {
        this.mentorid = mentorid;
    }
    public String getProgramid() {
        return this.programid;
    }

    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getBranchid() {
        return this.branchid;
    }

    public void setBranchid(String branchid) {
        this.branchid = branchid;
    }
    public String getStynumber() {
        return this.stynumber;
    }

    public void setStynumber(String stynumber) {
        this.stynumber = stynumber;
    }


}


