package com.jilit.irp.persistence.dto;
// Generated Nov 10, 2010 7:35:01 PM by Hibernate Tools 3.2.1.GA



/**
 * Mentormaster generated by hbm2java
 */
public class MentorMaster  implements java.io.Serializable {


     private MentorMasterId id;
     private ProgramMaster programmaster;
     private BranchMaster branchmaster;
     private String remarks;
     private String deactive;

    public MentorMaster() {
    }

    public MentorMaster(MentorMaster dto) {
        this.id=dto.getId();
        this.remarks=dto.getRemarks();
        this.deactive=dto.getDeactive();
    }

    public MentorMaster(MentorMasterId id, ProgramMaster programMaster, BranchMaster branchmaster) {
        this.id = id;
        this.programmaster = programmaster;
        this.branchmaster = branchmaster;
    }
    public MentorMaster(MentorMasterId id, ProgramMaster programMaster, BranchMaster branchmaster, String remarks, String deactive) {
       this.id = id;
       this.programmaster = programmaster;
       this.branchmaster = branchmaster;
       this.remarks = remarks;
       this.deactive = deactive;
    }

    public MentorMasterId getId() {
        return this.id;
    }

    public void setId(MentorMasterId id) {
        this.id = id;
    }
    public ProgramMaster getProgrammaster() {
        return this.programmaster;
    }

    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }
    public BranchMaster getBranchmaster() {
        return this.branchmaster;
    }

    public void setBranchmaster(BranchMaster branchmaster) {
        this.branchmaster = branchmaster;
    }
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


