package com.jilit.irp.persistence.dto;
// Generated 14 Dec, 2011 11:27:05 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Srs#eventmasterId generated by hbm2java
 */
public class MercyAppealId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String studentid;

    public MercyAppealId() {
    }

    public MercyAppealId(String instituteid, String registrationid, String studentid) {
        this.instituteid = instituteid;
        this.registrationid = registrationid;
        this.studentid = studentid;
    }

    public String getInstituteid() {
        return instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }

    public String getRegistrationid() {
        return registrationid;
    }

    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    
}


