package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Multifacultysubjecttagging generated by hbm2java
 */
public class MultiFacultySubjectTagging  implements java.io.Serializable {


     private MultiFacultySubjectTaggingId id;
     private FacultySubjectTagging facultysubjecttagging;
     private BigDecimal noofhours;
     private BigDecimal classinaweek;
     private String deactive;

    public MultiFacultySubjectTagging() {
    }

	
    public MultiFacultySubjectTagging(MultiFacultySubjectTaggingId id, FacultySubjectTagging facultysubjecttagging, BigDecimal noofhours, BigDecimal classinaweek) {
        this.id = id;
        this.facultysubjecttagging = facultysubjecttagging;
        this.noofhours = noofhours;
        this.classinaweek = classinaweek;
    }
    public MultiFacultySubjectTagging(MultiFacultySubjectTaggingId id, FacultySubjectTagging facultysubjecttagging, BigDecimal noofhours, BigDecimal classinaweek, String deactive) {
       this.id = id;
       this.facultysubjecttagging = facultysubjecttagging;
       this.noofhours = noofhours;
       this.classinaweek = classinaweek;
       this.deactive = deactive;
    }
   
    public MultiFacultySubjectTaggingId getId() {
        return this.id;
    }
    
    public void setId(MultiFacultySubjectTaggingId id) {
        this.id = id;
    }
    public FacultySubjectTagging getFacultysubjecttagging() {
        return this.facultysubjecttagging;
    }
    
    public void setFacultysubjecttagging(FacultySubjectTagging facultysubjecttagging) {
        this.facultysubjecttagging = facultysubjecttagging;
    }
   
    public BigDecimal getNoofhours() {
        return this.noofhours;
    }
    
    public void setNoofhours(BigDecimal noofhours) {
        this.noofhours = noofhours;
    }
    public BigDecimal getClassinaweek() {
        return this.classinaweek;
    }
    
    public void setClassinaweek(BigDecimal classinaweek) {
        this.classinaweek = classinaweek;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


