package com.jilit.irp.persistence.dto;
// Generated 5 Nov, 2013 4:13:13 PM by Hibernate Tools 3.2.1.GA



/**
 * Noteligibleforregistration generated by hbm2java
 */
public class NotEligibleForRegistration  implements java.io.Serializable {


     private NotEligibleForRegistrationId id;
     private StudentRegistration studentregistration;
     private byte tostynumber;
     private String reason;
     private String eligiblitystatus;
     private String deactive;

    public NotEligibleForRegistration() {
    }

	
    public NotEligibleForRegistration(NotEligibleForRegistrationId id, StudentRegistration studentregistration, byte tostynumber) {
        this.id = id;
        this.studentregistration = studentregistration;
        this.tostynumber = tostynumber;
    }
    public NotEligibleForRegistration(NotEligibleForRegistrationId id, StudentRegistration studentregistration, byte tostynumber, String reason, String eligiblitystatus, String deactive) {
       this.id = id;
       this.studentregistration = studentregistration;
       this.tostynumber = tostynumber;
       this.reason = reason;
       this.eligiblitystatus = eligiblitystatus;
       this.deactive = deactive;
    }
   
    public NotEligibleForRegistrationId getId() {
        return this.id;
    }
    
    public void setId(NotEligibleForRegistrationId id) {
        this.id = id;
    }
    public StudentRegistration getStudentregistration() {
        return this.studentregistration;
    }
    
    public void setStudentregistration(StudentRegistration studentregistration) {
        this.studentregistration = studentregistration;
    }
    public byte getTostynumber() {
        return this.tostynumber;
    }
    
    public void setTostynumber(byte tostynumber) {
        this.tostynumber = tostynumber;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getEligiblitystatus() {
        return this.eligiblitystatus;
    }
    
    public void setEligiblitystatus(String eligiblitystatus) {
        this.eligiblitystatus = eligiblitystatus;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


