package com.jilit.irp.persistence.dto;
// Generated Mar 12, 2014 10:18:20 AM by Hibernate Tools 3.2.1.GA



/**
 * Notify#parametersId generated by hbm2java
 */
public class Notify_ParametersId  implements java.io.Serializable {


     private String instituteid;
     private String parameterid;

    public Notify_ParametersId() {
    }

    public Notify_ParametersId(String instituteid, String parameterid) {
       this.instituteid = instituteid;
       this.parameterid = parameterid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getParameterid() {
        return this.parameterid;
    }
    
    public void setParameterid(String parameterid) {
        this.parameterid = parameterid;
    }


   


}


