package com.jilit.irp.persistence.dto;
// Generated Jan 5, 2014 3:06:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notify_notificationalertmaster generated by hbm2java
 */
public class Notify_NotificationAlertMaster  implements java.io.Serializable {


     private String notificationid;
     private Notification_SmsSetup notification_smssetup;
     private InstituteMaster institutemaster;
     private String notificationvia;
     private Date notificationdatetime;
     private String notificationsentstatus;
     private String notificationfor;
     private String notoficationsubject;
     private String notoficationpriority;
     private String notificationtext;
     private String attachmentrequired;
     private String notificationmode;
     private String notificationfrom;
     private String notificationipaddress;
     private String notificationmacaddress;
     private String notificationby;
     private String deactive;
     private String companyid;
     private String templatecode;
     private Set<Notify_NotificationTo> notify_notificationtos = new HashSet<Notify_NotificationTo>(0);

    public Notify_NotificationAlertMaster() {
    }

	
    public Notify_NotificationAlertMaster(String notificationid, Notification_SmsSetup notification_smssetup, String notificationvia, Date notificationdatetime, String notificationsentstatus, String notificationfor, String notificationmode) {
        this.notificationid = notificationid;
        this.notification_smssetup = notification_smssetup;
        this.notificationvia = notificationvia;
        this.notificationdatetime = notificationdatetime;
        this.notificationsentstatus = notificationsentstatus;
        this.notificationfor = notificationfor;
        this.notificationmode = notificationmode;
    }
    public Notify_NotificationAlertMaster(String notificationid, Notification_SmsSetup notification_smssetup, InstituteMaster institutemaster, String notificationvia, Date notificationdatetime, String notificationsentstatus, String notificationfor, String notoficationsubject, String notoficationpriority, String notificationtext, String attachmentrequired, String notificationmode, String notificationfrom, String notificationipaddress, String notificationmacaddress, String notificationby, String deactive, Set<Notify_NotificationTo> notify_notificationtos) {
       this.notificationid = notificationid;
       this.notification_smssetup = notification_smssetup;
       this.institutemaster = institutemaster;
       this.notificationvia = notificationvia;
       this.notificationdatetime = notificationdatetime;
       this.notificationsentstatus = notificationsentstatus;
       this.notificationfor = notificationfor;
       this.notoficationsubject = notoficationsubject;
       this.notoficationpriority = notoficationpriority;
       this.notificationtext = notificationtext;
       this.attachmentrequired = attachmentrequired;
       this.notificationmode = notificationmode;
       this.notificationfrom = notificationfrom;
       this.notificationipaddress = notificationipaddress;
       this.notificationmacaddress = notificationmacaddress;
       this.notificationby = notificationby;
       this.deactive = deactive;
       this.notify_notificationtos = notify_notificationtos;
    }
   
    public String getNotificationid() {
        return this.notificationid;
    }
    
    public void setNotificationid(String notificationid) {
        this.notificationid = notificationid;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    public Notification_SmsSetup getNotification_smssetup() {
        return notification_smssetup;
    }

    public void setNotification_smssetup(Notification_SmsSetup notification_smssetup) {
        this.notification_smssetup = notification_smssetup;
    }
    
    public String getNotificationvia() {
        return this.notificationvia;
    }
    
    public void setNotificationvia(String notificationvia) {
        this.notificationvia = notificationvia;
    }
    public Date getNotificationdatetime() {
        return this.notificationdatetime;
    }
    
    public void setNotificationdatetime(Date notificationdatetime) {
        this.notificationdatetime = notificationdatetime;
    }
    public String getNotificationsentstatus() {
        return this.notificationsentstatus;
    }
    
    public void setNotificationsentstatus(String notificationsentstatus) {
        this.notificationsentstatus = notificationsentstatus;
    }
    public String getNotificationfor() {
        return this.notificationfor;
    }
    
    public void setNotificationfor(String notificationfor) {
        this.notificationfor = notificationfor;
    }
    public String getNotoficationsubject() {
        return this.notoficationsubject;
    }
    
    public void setNotoficationsubject(String notoficationsubject) {
        this.notoficationsubject = notoficationsubject;
    }
    public String getNotoficationpriority() {
        return this.notoficationpriority;
    }
    
    public void setNotoficationpriority(String notoficationpriority) {
        this.notoficationpriority = notoficationpriority;
    }
    public String getNotificationtext() {
        return this.notificationtext;
    }
    
    public void setNotificationtext(String notificationtext) {
        this.notificationtext = notificationtext;
    }
    public String getAttachmentrequired() {
        return this.attachmentrequired;
    }
    
    public void setAttachmentrequired(String attachmentrequired) {
        this.attachmentrequired = attachmentrequired;
    }
    public String getNotificationmode() {
        return this.notificationmode;
    }
    
    public void setNotificationmode(String notificationmode) {
        this.notificationmode = notificationmode;
    }
    public String getNotificationfrom() {
        return this.notificationfrom;
    }
    
    public void setNotificationfrom(String notificationfrom) {
        this.notificationfrom = notificationfrom;
    }
    public String getNotificationipaddress() {
        return this.notificationipaddress;
    }
    
    public void setNotificationipaddress(String notificationipaddress) {
        this.notificationipaddress = notificationipaddress;
    }
    public String getNotificationmacaddress() {
        return this.notificationmacaddress;
    }
    
    public void setNotificationmacaddress(String notificationmacaddress) {
        this.notificationmacaddress = notificationmacaddress;
    }
    public String getNotificationby() {
        return this.notificationby;
    }
    
    public void setNotificationby(String notificationby) {
        this.notificationby = notificationby;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<Notify_NotificationTo> getNotify_notificationtos() {
        return notify_notificationtos;
    }

    public void setNotify_notificationtos(Set<Notify_NotificationTo> notify_notificationtos) {
        this.notify_notificationtos = notify_notificationtos;
    }

    public String getTemplatecode() {
        return templatecode;
    }

    public void setTemplatecode(String templatecode) {
        this.templatecode = templatecode;
    }

    public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    
}

