package com.jilit.irp.persistence.dto;
// Generated 4 Feb, 2012 11:20:57 AM by Hibernate Tools 3.2.1.GA



/**
 * NumberingcontrolothersId generated by hbm2java
 */
public class NumberingControlOthersId  implements java.io.Serializable {


     private String groupid;
     private String ymd;

    public NumberingControlOthersId() {
    }

    public NumberingControlOthersId(String groupid, String ymd) {
       this.groupid = groupid;
       this.ymd = ymd;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getYmd() {
        return this.ymd;
    }
    
    public void setYmd(String ymd) {
        this.ymd = ymd;
    }


   

}


