package com.jilit.irp.persistence.dto;
// Generated 4 Feb, 2012 11:20:57 AM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;

/**
 * Numberingsetupothers generated by hbm2java
 */
public class NumberingSetupOthers  implements java.io.Serializable {


     private String groupid;
     private String companyinstid;
     private String companyinstitute;
     private String prefix;
     private String ymd;
     private int totalwidth;
     private Set<NumberingControlOthers> numberingcontrolotherses = new HashSet<NumberingControlOthers>(0);

    public NumberingSetupOthers()
    {
    }

	public NumberingSetupOthers(NumberingSetupOthers dto) {
        this.groupid = dto.groupid;
        this.companyinstid = dto.companyinstid;
        this.companyinstitute = dto.companyinstitute;
        this.prefix = dto.prefix;
        this.ymd = dto.ymd;
        this.totalwidth = dto.totalwidth;
    }
	
    public NumberingSetupOthers(String groupid) {
       this.groupid = groupid;
    }

    public NumberingSetupOthers(String groupid, String companyinstid, String companyinstitute, String ymd) {
        this.groupid = groupid;
        this.companyinstid = companyinstid;
        this.companyinstitute = companyinstitute;
        this.ymd = ymd;
    }
    public NumberingSetupOthers(String groupid, String companyinstid, String companyinstitute, String prefix, String ymd, int totalwidth, Set numberingcontrolotherses) {
       this.groupid = groupid;
       this.companyinstid = companyinstid;
       this.companyinstitute = companyinstitute;
       this.prefix = prefix;
       this.ymd = ymd;
       this.totalwidth = totalwidth;
       this.numberingcontrolotherses = numberingcontrolotherses;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getCompanyinstid() {
        return this.companyinstid;
    }
    
    public void setCompanyinstid(String companyinstid) {
        this.companyinstid = companyinstid;
    }
    public String getCompanyinstitute() {
        return this.companyinstitute;
    }
    
    public void setCompanyinstitute(String companyinstitute) {
        this.companyinstitute = companyinstitute;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public String getYmd() {
        return this.ymd;
    }
    
    public void setYmd(String ymd) {
        this.ymd = ymd;
    }
    public int getTotalwidth() {
        return this.totalwidth;
    }
    
    public void setTotalwidth(int totalwidth) {
        this.totalwidth = totalwidth;
    }

    public Set<NumberingControlOthers> getNumberingcontrolotherses() {
        return numberingcontrolotherses;
    }

    public void setNumberingcontrolotherses(Set<NumberingControlOthers> numberingcontrolotherses) {
        this.numberingcontrolotherses = numberingcontrolotherses;
    }
    


    

}


