package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * OfferedodsubjecttaggingId generated by hbm2java
 */
public class OfferedODSubjectTaggingId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String offersubjectid;

    public OfferedODSubjectTaggingId() {
    }

    public OfferedODSubjectTaggingId(String instituteid, String registrationid, String offersubjectid) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.offersubjectid = offersubjectid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getOffersubjectid() {
        return this.offersubjectid;
    }
    
    public void setOffersubjectid(String offersubjectid) {
        this.offersubjectid = offersubjectid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfferedODSubjectTaggingId) ) return false;
		 OfferedODSubjectTaggingId castOther = ( OfferedODSubjectTaggingId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && ( (this.getOffersubjectid()==castOther.getOffersubjectid()) || ( this.getOffersubjectid()!=null && castOther.getOffersubjectid()!=null && this.getOffersubjectid().equals(castOther.getOffersubjectid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + ( getOffersubjectid() == null ? 0 : this.getOffersubjectid().hashCode() );
         return result;
   }   


}


