package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Offeredodsubjecttaggingdetail generated by hbm2java
 */
public class OfferedODSubjectTaggingDetail implements java.io.Serializable {


    private OfferedODSubjectTaggingDetailId id;
    private SubjectComponent subjectcomponent;
    private OfferedODSubjectTagging offeredodsubjecttagging;
    private BigDecimal ltppassingmarks;
    private BigDecimal totalccpmarks;
    private BigDecimal noofhours;
    private BigDecimal noofclassinaweek;
    private BigDecimal totalclasses;
    private BigDecimal byltp;
    private String deactive;
    private String staffid;
    private String stafftype;

    public OfferedODSubjectTaggingDetail() {
    }

    public OfferedODSubjectTaggingDetail(OfferedODSubjectTaggingDetail dto, boolean childReqd) {
        this.id = dto.getId();
        this.ltppassingmarks = dto.getLtppassingmarks();
        this.totalccpmarks = dto.getTotalccpmarks();
        this.noofhours = dto.getNoofhours();
        this.noofclassinaweek = dto.getNoofclassinaweek();
        this.byltp = dto.getByltp();
        this.deactive = dto.getDeactive();

    }

    public OfferedODSubjectTaggingDetail(OfferedODSubjectTaggingDetailId id, SubjectComponent subjectcomponent, OfferedODSubjectTagging offeredodsubjecttagging, BigDecimal ltppassingmarks, BigDecimal totalccpmarks, BigDecimal byltp) {
        this.id = id;
        this.subjectcomponent = subjectcomponent;
        this.offeredodsubjecttagging = offeredodsubjecttagging;
        this.ltppassingmarks = ltppassingmarks;
        this.totalccpmarks = totalccpmarks;
        this.byltp = byltp;
    }

    public OfferedODSubjectTaggingDetail(OfferedODSubjectTaggingDetailId id, SubjectComponent subjectcomponent, OfferedODSubjectTagging offeredodsubjecttagging, BigDecimal ltppassingmarks, BigDecimal totalccpmarks, BigDecimal noofhours, BigDecimal noofclassinaweek, BigDecimal byltp, String deactive) {
        this.id = id;
        this.subjectcomponent = subjectcomponent;
        this.offeredodsubjecttagging = offeredodsubjecttagging;
        this.ltppassingmarks = ltppassingmarks;
        this.totalccpmarks = totalccpmarks;
        this.noofhours = noofhours;
        this.noofclassinaweek = noofclassinaweek;
        this.byltp = byltp;
        this.deactive = deactive;
    }

    public OfferedODSubjectTaggingDetailId getId() {
        return this.id;
    }

    public void setId(OfferedODSubjectTaggingDetailId id) {
        this.id = id;
    }

    public SubjectComponent getSubjectcomponent() {
        return this.subjectcomponent;
    }

    public void setSubjectcomponent(SubjectComponent subjectcomponent) {
        this.subjectcomponent = subjectcomponent;
    }

    public OfferedODSubjectTagging getOfferedodsubjecttagging() {
        return this.offeredodsubjecttagging;
    }

    public void setOfferedodsubjecttagging(OfferedODSubjectTagging offeredodsubjecttagging) {
        this.offeredodsubjecttagging = offeredodsubjecttagging;
    }

    public BigDecimal getLtppassingmarks() {
        return this.ltppassingmarks;
    }

    public void setLtppassingmarks(BigDecimal ltppassingmarks) {
        this.ltppassingmarks = ltppassingmarks;
    }

    public BigDecimal getTotalccpmarks() {
        return this.totalccpmarks;
    }

    public void setTotalccpmarks(BigDecimal totalccpmarks) {
        this.totalccpmarks = totalccpmarks;
    }

    public BigDecimal getNoofhours() {
        return this.noofhours;
    }

    public void setNoofhours(BigDecimal noofhours) {
        this.noofhours = noofhours;
    }

    public BigDecimal getNoofclassinaweek() {
        return this.noofclassinaweek;
    }

    public void setNoofclassinaweek(BigDecimal noofclassinaweek) {
        this.noofclassinaweek = noofclassinaweek;
    }

    public BigDecimal getByltp() {
        return byltp;
    }

    public void setByltp(BigDecimal byltp) {
        this.byltp = byltp;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public BigDecimal getTotalclasses() {
        return totalclasses;
    }

    public void setTotalclasses(BigDecimal totalclasses) {
        this.totalclasses = totalclasses;
    }

    public String getStaffid() {
        return staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    public String getStafftype() {
        return stafftype;
    }

    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }

}
