package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * OtherStaffMaster generated by hbm2java
 */
public class OtherStaffMaster implements java.io.Serializable {

    private String ostype;
    private String orig_instituteorcompany;
    private String orig_instituteidcompanyid;
    private String orig_empvfstudentid;
    private String remarks;
    private String deactive;
    private String osid;
    private String companyid;
  
    private String employeetypeid;
    private Set<OtherStaffMasterDetail> otherstaffmasterdetails = new HashSet<OtherStaffMasterDetail>(0);
  //  private Set<Srs_TopicEvents> srs_topiceventses = new HashSet<Srs_TopicEvents>(0);

    public OtherStaffMaster() {
    }

    public OtherStaffMaster(OtherStaffMaster dto) {
        this.osid = dto.getOsid();
        this.orig_empvfstudentid = dto.getOrig_empvfstudentid();
        this.orig_instituteidcompanyid = dto.getOrig_instituteidcompanyid();
        this.orig_instituteorcompany = dto.getOrig_instituteorcompany();
        this.companyid = dto.getCompanyid();
        this.employeetypeid = dto.getEmployeetypeid();
        this.ostype = dto.getOstype();
        this.remarks = dto.getRemarks();
        this.deactive = dto.getDeactive();


    }

    public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
 

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
 

    public String getEmployeetypeid() {
        return employeetypeid;
    }

    public void setEmployeetypeid(String employeetypeid) {
        this.employeetypeid = employeetypeid;
    }

    public String getOrig_empvfstudentid() {
        return orig_empvfstudentid;
    }

    public void setOrig_empvfstudentid(String orig_empvfstudentid) {
        this.orig_empvfstudentid = orig_empvfstudentid;
    }

    public String getOrig_instituteidcompanyid() {
        return orig_instituteidcompanyid;
    }

    public void setOrig_instituteidcompanyid(String orig_instituteidcompanyid) {
        this.orig_instituteidcompanyid = orig_instituteidcompanyid;
    }

    public String getOrig_instituteorcompany() {
        return orig_instituteorcompany;
    }

    public void setOrig_instituteorcompany(String orig_instituteorcompany) {
        this.orig_instituteorcompany = orig_instituteorcompany;
    }

    public String getOsid() {
        return osid;
    }

    public void setOsid(String osid) {
        this.osid = osid;
    }

    public String getOstype() {
        return ostype;
    }

    public void setOstype(String ostype) {
        this.ostype = ostype;
    }

    public Set<OtherStaffMasterDetail> getOtherstaffmasterdetails() {
        return otherstaffmasterdetails;
    }

    public void setOtherstaffmasterdetails(Set<OtherStaffMasterDetail> otherstaffmasterdetails) {
        this.otherstaffmasterdetails = otherstaffmasterdetails;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

//    public Set<Srs_TopicEvents> getSrs_topiceventses() {
//        return srs_topiceventses;
//    }
//
//    public void setSrs_topiceventses(Set<Srs_TopicEvents> srs_topiceventses) {
//        this.srs_topiceventses = srs_topiceventses;
//    }
//    public String getIdStr(){
//        return id.getCompanyid()+":"+id.getOsid();
//    }
    
}


