package com.jilit.irp.persistence.dto;
// Generated Feb 11, 2014 2:04:24 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Otherstaffspectagging generated by hbm2java
 */
public class OtherStaffSpecTagging  implements java.io.Serializable { 

     private String instituteid;
     private OtherStaffSpecTaggingId id;
     private SpecializationMaster specializationmaster;
     private SubjectMaster subjectmaster;
     private String deactive;
     private String entryby;
     private Date entrydate;

    public OtherStaffSpecTagging() {
    }

    public OtherStaffSpecTagging(OtherStaffSpecTagging dto) {
      this.id = dto.getId();
      this.instituteid = dto.getInstituteid();
      this.entryby = dto.getEntryby();
      this.entrydate = dto.getEntrydate();
      this.deactive = dto.getDeactive();
    }

	
    public OtherStaffSpecTagging(OtherStaffSpecTaggingId id, SpecializationMaster specializationmaster, SubjectMaster subjectmaster) {
        this.id = id;
        this.specializationmaster = specializationmaster;
        this.subjectmaster = subjectmaster;
    }
    public OtherStaffSpecTagging(OtherStaffSpecTaggingId id, SpecializationMaster specializationmaster, SubjectMaster subjectmaster, String deactive, String entryby, Date entrydate)
    {
       this.id = id;
       this.specializationmaster = specializationmaster;
       this.subjectmaster = subjectmaster;
       this.deactive = deactive;
       this.entryby = entryby;
       this.entrydate = entrydate;
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getEntryby() {
        return entryby;
    }

    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public OtherStaffSpecTaggingId getId() {
        return id;
    }

    public void setId(OtherStaffSpecTaggingId id) {
        this.id = id;
    }

    public SpecializationMaster getSpecializationmaster() {
        return specializationmaster;
    }

    public void setSpecializationmaster(SpecializationMaster specializationmaster) {
        this.specializationmaster = specializationmaster;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    public String getInstituteid() {
        return instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }



     public String getIdStr() {
            return (id.getOsid() + "::" + id.getSubjectid()+"::"+ id.getSpecializationcategoryid() +"::"+ id.getSpecializationid());
        }
   
}


