package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * ParameterValueMasterId generated by hbm2java
 */
public class ParameterValueMasterId  implements java.io.Serializable {


     private String parameterid;
     private Short seqid;

    public ParameterValueMasterId() {
    }

    public ParameterValueMasterId(String parameterid, Short seqid) {
       this.parameterid = parameterid;
       this.seqid = seqid;
    }
   
    public String getParameterid() {
        return this.parameterid;
    }
    
    public void setParameterid(String parameterid) {
        this.parameterid = parameterid;
    }
    public Short getSeqid() {
        return this.seqid;
    }
    
    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParameterValueMasterId) ) return false;
		 ParameterValueMasterId castOther = ( ParameterValueMasterId ) other; 
         
		 return ( (this.getParameterid()==castOther.getParameterid()) || ( this.getParameterid()!=null && castOther.getParameterid()!=null && this.getParameterid().equals(castOther.getParameterid()) ) )
 && (this.getSeqid()==castOther.getSeqid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getParameterid() == null ? 0 : this.getParameterid().hashCode() );
         result = 37 * result + this.getSeqid();
         return result;
   }   


}


