package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parameters generated by hbm2java
 */
public class Parameters  implements java.io.Serializable {


     private ParametersId id; 
     private Sct_IrpModules sct_irpmodules;
     private InstituteMaster institutemaster;
     private String parameter;
     private String parametervalue;
     private Short seqid;
     private String datatype;
     private String entryfield;
     private String width;
     private String minrange;
     private String maxrange;
     private String deactive;
      

    public Parameters() {
    }

	
    public Parameters(ParametersId id,  Sct_IrpModules sct_irpmodules, InstituteMaster institutemaster, String parameter) {
        this.id = id;
        
        this.sct_irpmodules = sct_irpmodules;
        this.institutemaster = institutemaster;
        this.parameter = parameter;
    }
    public Parameters(ParametersId id,   Sct_IrpModules sct_irpmodules, InstituteMaster institutemaster, String parameter, String parametervalue, Short seqid, String datatype, String entryfield, String width, String minrange, String maxrange, String deactive ) {
       this.id = id;
       
       this.sct_irpmodules = sct_irpmodules;
       this.institutemaster = institutemaster;
       this.parameter = parameter;
       this.parametervalue = parametervalue;
       this.seqid = seqid;
       this.datatype = datatype;
       this.entryfield = entryfield;
       this.width = width;
       this.minrange = minrange;
       this.maxrange = maxrange;
       this.deactive = deactive;
       
    }
   
    public ParametersId getId() {
        return this.id;
    }
    
    public void setId(ParametersId id) {
        this.id = id;
    }
 
    public String getParameter() {
        return this.parameter;
    }
    
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }
    public String getParametervalue() {
        return this.parametervalue;
    }
    
    public void setParametervalue(String parametervalue) {
        this.parametervalue = parametervalue;
    }
    public Short getSeqid() {
        return this.seqid;
    }
    
    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }
    public String getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }
    public String getEntryfield() {
        return this.entryfield;
    }
    
    public void setEntryfield(String entryfield) {
        this.entryfield = entryfield;
    }
    public String getWidth() {
        return this.width;
    }
    
    public void setWidth(String width) {
        this.width = width;
    }
    public String getMinrange() {
        return this.minrange;
    }
    
    public void setMinrange(String minrange) {
        this.minrange = minrange;
    }
    public String getMaxrange() {
        return this.maxrange;
    }
    
    public void setMaxrange(String maxrange) {
        this.maxrange = maxrange;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
 

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

     

    public Sct_IrpModules getSct_irpmodules() {
        return sct_irpmodules;
    }

    public void setSct_irpmodules(Sct_IrpModules sct_irpmodules) {
        this.sct_irpmodules = sct_irpmodules;
    }





}


