package com.jilit.irp.persistence.dto;
// Generated 12 Jan, 2019 1:03:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Pr_ElectiveSets#electivesetsId generated by hbm2java
 */
public class Pr_ElectiveSetsId  implements java.io.Serializable {


     private String instituteid;
     private String programid;
     private String subjectid;
     private String groupid;
     

    public Pr_ElectiveSetsId() {
    }

    public Pr_ElectiveSetsId(String instituteid, String programid, String subjectid) {
       this.instituteid = instituteid;
       this.programid = programid;
       this.subjectid = subjectid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    public String getGroupid() {
        return groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }


  


}


