package com.jilit.irp.persistence.dto;
// Generated 12 Jan, 2019 1:03:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Pr_electivesets generated by hbm2java
 */
public class Pr_ElectiveSets implements java.io.Serializable {

    private Pr_ElectiveSetsId id;
//     private ProgramMaster programmaster;
//     private SubjectMaster subjectmaster;
    private String deactive;
    private String enrtyby;
    private Date entrydate;
    private String updateby;
    private Date updatedate;

    public Pr_ElectiveSets() {
    }

    public Pr_ElectiveSetsId getId() {
        return id;
    }

    public void setId(Pr_ElectiveSetsId id) {
        this.id = id;
    }

//    public ProgramMaster getProgrammaster() {
//        return programmaster;
//    }
//
//    public void setProgrammaster(ProgramMaster programmaster) {
//        this.programmaster = programmaster;
//    }
//
//    public SubjectMaster getSubjectmaster() {
//        return subjectmaster;
//    }
//
//    public void setSubjectmaster(SubjectMaster subjectmaster) {
//        this.subjectmaster = subjectmaster;
//    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getEnrtyby() {
        return enrtyby;
    }

    public void setEnrtyby(String enrtyby) {
        this.enrtyby = enrtyby;
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

}
