package com.jilit.irp.persistence.dto;
// Generated Jul 2, 2010 10:47:07 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PreRequisitForRegistration generated by hbm2java
 */
public class PreRequisitForRegistration implements java.io.Serializable {

    private PreRequisitForRegistrationId id;
    private ProgramMaster programmaster;
    private InstituteMaster institutemaster;
    private BranchMaster branchmaster;
    private Long maxfailsubject;
    private BigDecimal minsgpa;
    private BigDecimal mincgpa;
    private BigDecimal mincredits;
    private BigDecimal minattendancepercent;
    private BigDecimal maxdeciplinary;
    private String deactive;
    private BigDecimal minearnedpoints;
    private Long maxnoattempts;
    private BigDecimal lateralentrymincredit;

    private Set<PreRequisitForRegSubjDetail> prerequisitforregsubjdetail = new HashSet<PreRequisitForRegSubjDetail>(0);

    public PreRequisitForRegistration() {
    }

    public PreRequisitForRegistration(PreRequisitForRegistrationId id, ProgramMaster programmaster, InstituteMaster institutemaster, BranchMaster branchmaster) {
        this.id = id;
        this.programmaster = programmaster;
        this.institutemaster = institutemaster;
        this.branchmaster = branchmaster;
    }

    public PreRequisitForRegistration(PreRequisitForRegistrationId id, ProgramMaster programmaster, InstituteMaster institutemaster, BranchMaster branchmaster, Long maxfailsubject, BigDecimal minsgpa, BigDecimal mincgpa, BigDecimal minattendancepercent, BigDecimal maxdeciplinary, String deactive, BigDecimal minearnedpoints) {
        this.id = id;
        this.programmaster = programmaster;
        this.institutemaster = institutemaster;
        this.branchmaster = branchmaster;
        this.maxfailsubject = maxfailsubject;
        this.minsgpa = minsgpa;
        this.mincgpa = mincgpa;
        this.minattendancepercent = minattendancepercent;
        this.maxdeciplinary = maxdeciplinary;
        this.deactive = deactive;
        this.minearnedpoints = minearnedpoints;
    }

    public PreRequisitForRegistration(PreRequisitForRegistrationId id, ProgramMaster programmaster, InstituteMaster institutemaster, BranchMaster branchmaster, Long maxfailsubject, BigDecimal minsgpa, BigDecimal mincgpa, BigDecimal mincredits, BigDecimal minattendancepercent, BigDecimal maxdeciplinary, String deactive, BigDecimal minearnedpoints, Long maxnoattempts) {
        this.id = id;
        this.programmaster = programmaster;
        this.institutemaster = institutemaster;
        this.branchmaster = branchmaster;
        this.maxfailsubject = maxfailsubject;
        this.minsgpa = minsgpa;
        this.mincgpa = mincgpa;
        this.mincredits = mincredits;
        this.minattendancepercent = minattendancepercent;
        this.maxdeciplinary = maxdeciplinary;
        this.deactive = deactive;
        this.minearnedpoints = minearnedpoints;
        this.maxnoattempts = maxnoattempts;
    }

    public PreRequisitForRegistration(PreRequisitForRegistration dto) {
        this.id = dto.getId();
        this.maxfailsubject = dto.getMaxfailsubject();
        this.minsgpa = dto.getMinsgpa();
        this.mincgpa = dto.getMincgpa();
        this.mincredits = dto.getMincredits();
        this.minattendancepercent = dto.getMinattendancepercent();
        this.maxdeciplinary = dto.getMaxdeciplinary();
        this.deactive = dto.getDeactive();
        this.maxnoattempts = dto.getMaxnoattempts();
    }

    public BigDecimal getLateralentrymincredit() {
        return lateralentrymincredit;
    }

    public void setLateralentrymincredit(BigDecimal lateralentrymincredit) {
        this.lateralentrymincredit = lateralentrymincredit;
    }

    public PreRequisitForRegistrationId getId() {
        return this.id;
    }

    public void setId(PreRequisitForRegistrationId id) {
        this.id = id;
    }

    public BranchMaster getBranchmaster() {
        return branchmaster;
    }

    public void setBranchmaster(BranchMaster branchmaster) {
        this.branchmaster = branchmaster;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    public ProgramMaster getProgrammaster() {
        return programmaster;
    }

    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }

    public Long getMaxfailsubject() {
        return maxfailsubject;
    }

    public void setMaxfailsubject(Long maxfailsubject) {
        this.maxfailsubject = maxfailsubject;
    }

    public BigDecimal getMinsgpa() {
        return this.minsgpa;
    }

    public void setMinsgpa(BigDecimal minsgpa) {
        this.minsgpa = minsgpa;
    }

    public BigDecimal getMincgpa() {
        return this.mincgpa;
    }

    public void setMincgpa(BigDecimal mincgpa) {
        this.mincgpa = mincgpa;
    }

    public BigDecimal getMinattendancepercent() {
        return this.minattendancepercent;
    }

    public BigDecimal getMincredits() {
        return mincredits;
    }

    public void setMincredits(BigDecimal mincredits) {
        this.mincredits = mincredits;
    }

    public void setMinattendancepercent(BigDecimal minattendancepercent) {
        this.minattendancepercent = minattendancepercent;
    }

    public BigDecimal getMaxdeciplinary() {
        return this.maxdeciplinary;
    }

    public void setMaxdeciplinary(BigDecimal maxdeciplinary) {
        this.maxdeciplinary = maxdeciplinary;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public BigDecimal getMinearnedpoints() {
        return minearnedpoints;
    }

    public void setMinearnedpoints(BigDecimal minearnedpoints) {
        this.minearnedpoints = minearnedpoints;
    }

    public Long getMaxnoattempts() {
        return this.maxnoattempts;
    }

    public void setMaxnoattempts(Long maxnoattempts) {
        this.maxnoattempts = maxnoattempts;
    }

    public Set<PreRequisitForRegSubjDetail> getPrerequisitforregsubjdetail() {
        return prerequisitforregsubjdetail;
    }

    public void setPrerequisitforregsubjdetail(Set<PreRequisitForRegSubjDetail> prerequisitforregsubjdetail) {
        this.prerequisitforregsubjdetail = prerequisitforregsubjdetail;
    }

    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getAcademicyear() + "::" + id.getProgramid() + "::" + id.getBranchid() + "::" + id.getStynumber();
    }
}
