package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Prerequisitmasterrequired generated by hbm2java
 */
public class PreRequisitMasterRequired  implements java.io.Serializable {


     private PreRequisitMasterRequiredId id;
     private SubjectMaster subjectmaster;
     private PreRequisitMaster prerequisitmaster;   

    public PreRequisitMasterRequired() {
    }

     public PreRequisitMasterRequired(PreRequisitMasterRequired dto)
    {
        this.id = dto.getId();
    }
	
    public PreRequisitMasterRequired(PreRequisitMasterRequiredId id, SubjectMaster subjectmaster, PreRequisitMaster prerequisitmaster) {
        this.id = id;
        this.subjectmaster = subjectmaster;
        this.prerequisitmaster = prerequisitmaster;
    }  
   
    public PreRequisitMasterRequiredId getId() {
        return this.id;
    }
    
    public void setId(PreRequisitMasterRequiredId id) {
        this.id = id;
    }
    public SubjectMaster getSubjectmaster() {
        return this.subjectmaster;
    }
    
    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }
    public PreRequisitMaster getPrerequisitmaster() {
        return this.prerequisitmaster;
    }
    
    public void setPrerequisitmaster(PreRequisitMaster prerequisitmaster) {
        this.prerequisitmaster = prerequisitmaster;
    }

    public String getIdStr()
    {
        return id.getInstituteid()+":"+id.getPrereqsubjectid()+":"+id.getSubjectsetid();
    }
}


