package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA

/**
 * Prerequisitacadwiserequired generated by hbm2java
 */
public class PreRequisitAcadWiseRequired implements java.io.Serializable {

    private PreRequisitAcadWiseRequiredId id;
    private SubjectMaster subjectmaster;
    private PreRequisitAcademicYearwise prerequisitacademicyearwise;

    public PreRequisitAcadWiseRequired() {
    }

    public PreRequisitAcadWiseRequired(PreRequisitAcadWiseRequiredId id, SubjectMaster subjectmaster, PreRequisitAcademicYearwise prerequisitacademicyearwise) {
        this.id = id;
        this.subjectmaster = subjectmaster;
        this.prerequisitacademicyearwise = prerequisitacademicyearwise;
    }

    public PreRequisitAcadWiseRequiredId getId() {
        return this.id;
    }

    public void setId(PreRequisitAcadWiseRequiredId id) {
        this.id = id;
    }

    public SubjectMaster getSubjectmaster() {
        return this.subjectmaster;
    }
 

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    public PreRequisitAcademicYearwise getPrerequisitacademicyearwise() {
        return this.prerequisitacademicyearwise;
    }

    public void setPrerequisitacademicyearwise(PreRequisitAcademicYearwise prerequisitacademicyearwise) {
        this.prerequisitacademicyearwise = prerequisitacademicyearwise;
    }

    public String getIdStr() {
        return id.getInstituteid() + ":" + id.getPrereqsubjectid() + ":" + id.getSubjectsetid();
    }
}


