package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA

/**
 * Prfacultysubjecttimepreference generated by hbm2java
 */
public class PRFacultySubjectTimePreference  implements java.io.Serializable {


     private PRFacultySubjectTimePreferenceId id;
     private PRFacultySubjectChoices prfacultysubjectchoices;
     private SubjectComponent subjectcomponent;
     private RoomTypeMaster roomtypemaster;
     private String preffromtime;
     private String preftotime;
     private String reqroomtype;
     private String deactive;

    public PRFacultySubjectTimePreference() {
    }
   public PRFacultySubjectTimePreference(PRFacultySubjectTimePreference dto) {
       this.id = dto.getId();
       this.preffromtime = dto.getPreffromtime();
       this.preftotime = dto.getPreftotime();
       this.reqroomtype = dto.getReqroomtype();
       this.deactive = dto.getDeactive();
    }
	
    public PRFacultySubjectTimePreference(PRFacultySubjectTimePreferenceId id, PRFacultySubjectChoices prfacultysubjectchoices, SubjectComponent subjectcomponent, RoomTypeMaster roomtypemaster) {
        this.id = id;
        this.prfacultysubjectchoices = prfacultysubjectchoices;
        this.subjectcomponent = subjectcomponent;
        this.roomtypemaster = roomtypemaster;
    }
    public PRFacultySubjectTimePreference(PRFacultySubjectTimePreferenceId id, PRFacultySubjectChoices prfacultysubjectchoices, SubjectComponent subjectcomponent, RoomTypeMaster roomtypemaster, String preffromtime, String preftotime, String deactive) {
       this.id = id;
       this.prfacultysubjectchoices = prfacultysubjectchoices;
       this.subjectcomponent = subjectcomponent;
       this.roomtypemaster = roomtypemaster;
       this.preffromtime = preffromtime;
       this.preftotime = preftotime;
       this.deactive = deactive;
    }
   
    public PRFacultySubjectTimePreferenceId getId() {
        return this.id;
    }
    
    public void setId(PRFacultySubjectTimePreferenceId id) {
        this.id = id;
    }
    public PRFacultySubjectChoices getPrfacultysubjectchoices() {
        return this.prfacultysubjectchoices;
    }
    
    public void setPrfacultysubjectchoices(PRFacultySubjectChoices prfacultysubjectchoices) {
        this.prfacultysubjectchoices = prfacultysubjectchoices;
    }
    public SubjectComponent getSubjectcomponent() {
        return this.subjectcomponent;
    }
    
    public void setSubjectcomponent(SubjectComponent subjectcomponent) {
        this.subjectcomponent = subjectcomponent;
    }
    public RoomTypeMaster getRoomtypemaster() {
        return this.roomtypemaster;
    }
    
    public void setRoomtypemaster(RoomTypeMaster roomtypemaster) {
        this.roomtypemaster = roomtypemaster;
    }

    public String getPreffromtime() {
        return preffromtime;
    }

    public void setPreffromtime(String preffromtime) {
        this.preffromtime = preffromtime;
    }

    public String getPreftotime() {
        return preftotime;
    }

    public void setPreftotime(String preftotime) {
        this.preftotime = preftotime;
    }
    

    public String getReqroomtype() {
        return reqroomtype;
    }

    public void setReqroomtype(String reqroomtype) {
        this.reqroomtype = reqroomtype;
    }

    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }


 public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid() + "::" + id.getStaffid() + "::" + id.getStafftype() + "::" + id.getSubjectid() + "::" + id.getSubjectcomponentid() + "::" + id.getEventno();
    }

}


