package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * PrfacultydaytimepreferenceId generated by hbm2java
 */
public class PRFacultyDayTimePreferenceId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private Short eventno;
     private String stafftype;
     private String staffid;
     private String subjectcomponentid;
     private String daypreference;
     private Short choiceno;

    public PRFacultyDayTimePreferenceId() {
    }

    public PRFacultyDayTimePreferenceId(PRFacultyDayTimePreferenceId dto) {
       this.instituteid = dto.getInstituteid();
       this.registrationid = dto.getRegistrationid();
       this.eventno = dto.getEventno();
       this.stafftype = dto.getStafftype();
       this.staffid = dto.getStaffid();
       this.subjectcomponentid = dto.getSubjectcomponentid();
       this.daypreference = dto.getDaypreference();
       this.choiceno = dto.getChoiceno();
    }
    public PRFacultyDayTimePreferenceId(String instituteid, String registrationid, Short eventno, String stafftype, String staffid, String subjectcomponentid, String daypreference, Short choiceno) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.eventno = eventno;
       this.stafftype = stafftype;
       this.staffid = staffid;
       this.subjectcomponentid = subjectcomponentid;
       this.daypreference = daypreference;
       this.choiceno = choiceno;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public Short getEventno() {
        return this.eventno;
    }
    
    public void setEventno(Short eventno) {
        this.eventno = eventno;
    }
    public String getStafftype() {
        return this.stafftype;
    }
    
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getSubjectcomponentid() {
        return this.subjectcomponentid;
    }
    
    public void setSubjectcomponentid(String subjectcomponentid) {
        this.subjectcomponentid = subjectcomponentid;
    }
    public String getDaypreference() {
        return this.daypreference;
    }
    
    public void setDaypreference(String daypreference) {
        this.daypreference = daypreference;
    }

    public Short getChoiceno() {
        return choiceno;
    }

    public void setChoiceno(Short choiceno) {
        this.choiceno = choiceno;
    }
   


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PRFacultyDayTimePreferenceId) ) return false;
		 PRFacultyDayTimePreferenceId castOther = ( PRFacultyDayTimePreferenceId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && (this.getEventno()==castOther.getEventno())
 && ( (this.getStafftype()==castOther.getStafftype()) || ( this.getStafftype()!=null && castOther.getStafftype()!=null && this.getStafftype().equals(castOther.getStafftype()) ) )
 && ( (this.getStaffid()==castOther.getStaffid()) || ( this.getStaffid()!=null && castOther.getStaffid()!=null && this.getStaffid().equals(castOther.getStaffid()) ) )
 && ( (this.getSubjectcomponentid()==castOther.getSubjectcomponentid()) || ( this.getSubjectcomponentid()!=null && castOther.getSubjectcomponentid()!=null && this.getSubjectcomponentid().equals(castOther.getSubjectcomponentid()) ) )
 && ( (this.getDaypreference()==castOther.getDaypreference()) || ( this.getDaypreference()!=null && castOther.getDaypreference()!=null && this.getDaypreference().equals(castOther.getDaypreference()) ) )
 && (this.getChoiceno()==castOther.getChoiceno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + this.getEventno();
         result = 37 * result + ( getStafftype() == null ? 0 : this.getStafftype().hashCode() );
         result = 37 * result + ( getStaffid() == null ? 0 : this.getStaffid().hashCode() );
         result = 37 * result + ( getSubjectcomponentid() == null ? 0 : this.getSubjectcomponentid().hashCode() );
         result = 37 * result + ( getDaypreference() == null ? 0 : this.getDaypreference().hashCode() );
         result = 37 * result + this.getChoiceno();
         return result;
   }   


}


