package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Prfacultyeventtagging generated by hbm2java
 */
public class PRFacultyEventTagging  implements java.io.Serializable {


     private PRFacultyEventTaggingId id;
     private PRFacultyEvent prfacultyevent;
 
     private Date eventfrom;
     private Date eventto;
     private String sendtohod;
     private String sentby;
     private Date sentdate;
     private String deactive;

    public PRFacultyEventTagging() {
    }

	
    public PRFacultyEventTagging(PRFacultyEventTaggingId id, PRFacultyEvent prfacultyevent,  Date eventfrom, Date eventto) {
        this.id = id;
        this.prfacultyevent = prfacultyevent;
       
        this.eventfrom = eventfrom;
        this.eventto = eventto;
    }
    public PRFacultyEventTagging(PRFacultyEventTaggingId id, PRFacultyEvent prfacultyevent,  Date eventfrom, Date eventto, String sendtohod, String sentby, Date sentdate, String deactive) {
       this.id = id;
       this.prfacultyevent = prfacultyevent;
      
       this.eventfrom = eventfrom;
       this.eventto = eventto;
       this.sendtohod = sendtohod;
       this.sentby = sentby;
       this.sentdate = sentdate;
       this.deactive = deactive;
    }
   public PRFacultyEventTagging(PRFacultyEventTagging dto) {
       this.id = dto.getId();
    
       this.eventfrom = dto.getEventfrom();
       this.eventto = dto.getEventto();
       this.sendtohod = dto.getSendtohod();
       this.sentby = dto.getSentby();
       this.sentdate = dto.getSentdate();
       this.deactive = dto.getDeactive();
    }
    public PRFacultyEventTaggingId getId() {
        return this.id;
    }
    
    public void setId(PRFacultyEventTaggingId id) {
        this.id = id;
    }
    public PRFacultyEvent getPrfacultyevent() {
        return this.prfacultyevent;
    }
    
    public void setPrfacultyevent(PRFacultyEvent prfacultyevent) {
        this.prfacultyevent = prfacultyevent;
    }
  
    public Date getEventfrom() {
        return this.eventfrom;
    }
    
    public void setEventfrom(Date eventfrom) {
        this.eventfrom = eventfrom;
    }
    public Date getEventto() {
        return this.eventto;
    }
    
    public void setEventto(Date eventto) {
        this.eventto = eventto;
    }
    public String getSendtohod() {
        return this.sendtohod;
    }
    
    public void setSendtohod(String sendtohod) {
        this.sendtohod = sendtohod;
    }
    public String getSentby() {
        return this.sentby;
    }
    
    public void setSentby(String sentby) {
        this.sentby = sentby;
    }
    public Date getSentdate() {
        return this.sentdate;
    }
    
    public void setSentdate(Date sentdate) {
        this.sentdate = sentdate;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


