package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Prfacultysubjectchoices generated by hbm2java
 */
public class PRFacultySubjectChoices  implements java.io.Serializable {


     private PRFacultySubjectChoicesId id;
     private SubjectComponent subjectcomponent;
     private RoomTypeMaster roomtypemaster;
     private SubjectMaster subjectmaster;
     private PRFacultyEvent prfacultyevent;
     private Short choiceno;
     private String subjectselected;
     private String reqroomtype;
     private String deactive;
     private Set<PRFacultySubjectTimePreference> prfacultysubjecttimepreferences = new HashSet<PRFacultySubjectTimePreference>(0);

    public PRFacultySubjectChoices() {
    }

	public PRFacultySubjectChoices( PRFacultySubjectChoices dto)
    {
        this.id = dto.getId();
        this.choiceno = dto.getChoiceno();
        this.subjectselected = dto.getSubjectselected();
        this.reqroomtype =dto.getReqroomtype();
        this.deactive = dto.getDeactive();
    }
    public PRFacultySubjectChoices(PRFacultySubjectChoicesId id, SubjectComponent subjectcomponent, RoomTypeMaster roomtypemaster, SubjectMaster subjectmaster, PRFacultyEvent prfacultyevent, Short choiceno) {
        this.id = id;
        this.subjectcomponent = subjectcomponent;
        this.roomtypemaster = roomtypemaster;
        this.subjectmaster = subjectmaster;
        this.prfacultyevent = prfacultyevent;
        this.choiceno = choiceno;
    }
    public PRFacultySubjectChoices(PRFacultySubjectChoicesId id, SubjectComponent subjectcomponent, RoomTypeMaster roomtypemaster, SubjectMaster subjectmaster, PRFacultyEvent prfacultyevent, Short choiceno, String subjectselected, String reqroomtype, String deactive, Set prfacultysubjecttimepreferences) {
       this.id = id;
       this.subjectcomponent = subjectcomponent;
       this.roomtypemaster = roomtypemaster;
       this.subjectmaster = subjectmaster;
       this.prfacultyevent = prfacultyevent;
       this.choiceno = choiceno;
       this.subjectselected = subjectselected;
       this.reqroomtype = reqroomtype;
       this.deactive = deactive;
       this.prfacultysubjecttimepreferences = prfacultysubjecttimepreferences;
    }
   
    public PRFacultySubjectChoicesId getId() {
        return this.id;
    }
    
    public void setId(PRFacultySubjectChoicesId id) {
        this.id = id;
    }
    public SubjectComponent getSubjectcomponent() {
        return this.subjectcomponent;
    }
    
    public void setSubjectcomponent(SubjectComponent subjectcomponent) {
        this.subjectcomponent = subjectcomponent;
    }
    public RoomTypeMaster getRoomtypemaster() {
        return this.roomtypemaster;
    }
    
    public void setRoomtypemaster(RoomTypeMaster roomtypemaster) {
        this.roomtypemaster = roomtypemaster;
    }
    public SubjectMaster getSubjectmaster() {
        return this.subjectmaster;
    }
    
    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }
    public PRFacultyEvent getPrfacultyevent() {
        return this.prfacultyevent;
    }
    
    public void setPrfacultyevent(PRFacultyEvent prfacultyevent) {
        this.prfacultyevent = prfacultyevent;
    }
    public Short getChoiceno() {
        return this.choiceno;
    }
    
    public void setChoiceno(Short choiceno) {
        this.choiceno = choiceno;
    }
    public String getSubjectselected() {
        return this.subjectselected;
    }
    
    public void setSubjectselected(String subjectselected) {
        this.subjectselected = subjectselected;
    }
    public String getReqroomtype() {
        return reqroomtype;
    }

    public void setReqroomtype(String reqroomtype) {
        this.reqroomtype = reqroomtype;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<PRFacultySubjectTimePreference> getPrfacultysubjecttimepreferences() {
        return prfacultysubjecttimepreferences;
    }

    public void setPrfacultysubjecttimepreferences(Set<PRFacultySubjectTimePreference> prfacultysubjecttimepreferences) {
        this.prfacultysubjecttimepreferences = prfacultysubjecttimepreferences;
    }
    
    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid() + "::" + id.getEventno() + "::" + id.getStafftype() + "::" + id.getStaffid() + "::" + id.getSubjectid() + "::" + id.getSubjectcomponentid();
    }
}


