package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * PrfacultyeventId generated by hbm2java
 */
public class PRFacultyEventId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private Integer eventno;

    public PRFacultyEventId() {
    }

    public PRFacultyEventId(String instituteid, String registrationid, Integer eventno) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.eventno = eventno;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public Integer getEventno() {
        return this.eventno;
    }
    
    public void setEventno(Integer eventno) {
        this.eventno = eventno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PRFacultyEventId) ) return false;
		 PRFacultyEventId castOther = ( PRFacultyEventId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && (this.getEventno()==castOther.getEventno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + this.getEventno();
         return result;
   }   


}


