package com.jilit.irp.persistence.dto;
// Generated Jan 7, 2017 10:17:58 AM by Hibernate Tools 3.2.1.GA



/**
 * ProgrameligibilityexamsId generated by hbm2java
 */
public class ProgramEligibilityExamsId  implements java.io.Serializable {


     private String instituteid;
     private String programid;
     private String eeexamid;

    public ProgramEligibilityExamsId() {
    }

    public ProgramEligibilityExamsId(String instituteid, String programid, String eeexamid) {
       this.instituteid = instituteid;
       this.programid = programid;
       this.eeexamid = eeexamid;
    }

    public String getInstituteid() {
        return this.instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getProgramid() {
        return this.programid;
    }

    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getEeexamid() {
        return this.eeexamid;
    }

    public void setEeexamid(String eeexamid) {
        this.eeexamid = eeexamid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgramEligibilityExamsId) ) return false;
		 ProgramEligibilityExamsId castOther = ( ProgramEligibilityExamsId ) other;

		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getProgramid()==castOther.getProgramid()) || ( this.getProgramid()!=null && castOther.getProgramid()!=null && this.getProgramid().equals(castOther.getProgramid()) ) )
 && ( (this.getEeexamid()==castOther.getEeexamid()) || ( this.getEeexamid()!=null && castOther.getEeexamid()!=null && this.getEeexamid().equals(castOther.getEeexamid()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getProgramid() == null ? 0 : this.getProgramid().hashCode() );
         result = 37 * result + ( getEeexamid() == null ? 0 : this.getEeexamid().hashCode() );
         return result;
   }


}


