package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.util.Set;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProgramMaxSty generated by hbm2java
 */
public class ProgramMaxSty implements java.io.Serializable {

    private ProgramMaxStyId id;
    private BranchMaster branchmaster;
    private Academicyear academicyear;
    private String stypattern;
    private byte startsty;
    private byte endsty;
    private Date startdate;
    private Date enddate;
    private String deactive;
    private String exampattern;

    private Set<ProgramMinMaxLimit> programminmaxlimits = new HashSet<ProgramMinMaxLimit>(0);

    public ProgramMaxSty() {
    }

    public ProgramMaxSty( ProgramMaxSty dto) {
        this.id = dto.getId();
        this.stypattern = dto.getStypattern();
        this.startsty = dto.getStartsty();
        this.endsty = dto.getEndsty();
        this.startdate = dto.getStartdate();
        this.enddate = dto.getEnddate();
        this.deactive = dto.getDeactive();
        this.exampattern=dto.getExampattern();
    }


    public ProgramMaxSty(ProgramMaxStyId id, BranchMaster branchmaster, Academicyear academicyear, String stypattern, byte startsty, byte endsty) {
        this.id = id;
        this.branchmaster = branchmaster;
        this.academicyear = academicyear;
        this.stypattern = stypattern;
        this.startsty = startsty;
        this.endsty = endsty;
    }

    public ProgramMaxSty(ProgramMaxStyId id, BranchMaster branchmaster, Academicyear academicyear, String stypattern, byte startsty, byte endsty, Date startdate, Date enddate, String deactive ,String exampattern) {
        this.id = id;
        this.branchmaster = branchmaster;
        this.academicyear = academicyear;
        this.stypattern = stypattern;
        this.startsty = startsty;
        this.endsty = endsty;
        this.startdate = startdate;
        this.enddate = enddate;
        this.deactive = deactive;
        this.exampattern=exampattern;
    }

    public ProgramMaxStyId getId() {
        return this.id;
    }

    public void setId(ProgramMaxStyId id) {
        this.id = id;
    }

    public Academicyear getAcademicyear() {
        return this.academicyear;
    }

    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }

    public String getStypattern() {
        return this.stypattern;
    }

    public void setStypattern(String stypattern) {
        this.stypattern = stypattern;
    }

    public byte getStartsty() {
        return this.startsty;
    }

    public void setStartsty(byte startsty) {
        this.startsty = startsty;
    }

    public byte getEndsty() {
        return this.endsty;
    }

    public void setEndsty(byte endsty) {
        this.endsty = endsty;
    }

    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public BranchMaster getBranchmaster() {
        return branchmaster;
    }

    public void setBranchmaster(BranchMaster branchmaster) {
        this.branchmaster = branchmaster;
    }

    public Set<ProgramMinMaxLimit> getProgramminmaxlimits() {
        return programminmaxlimits;
    }

    public void setProgramminmaxlimits(Set<ProgramMinMaxLimit> programminmaxlimits) {
        this.programminmaxlimits = programminmaxlimits;
    }

    public String getExampattern() {
        return exampattern;
    }

    public void setExampattern(String exampattern) {
        this.exampattern = exampattern;
    }
    public String getIdStr(){
        return id.getInstituteid()+":"+id.getAcademicyear()+":"+id.getProgramid()+":"+id.getBranchid();
    }
}


