package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ProgramSubjectTagging generated by hbm2java
 */
public class ProgramSubjectTagging implements java.io.Serializable {

    private ProgramSubjectTaggingId id;
    private RegistrationMaster registrationmaster;
    // private BasketMaster basketmaster;
    private SubjectMaster subjectmaster;
    private Academicyear academicyearmaster;
    private SectionMaster sectionmaster;
    private DepartmentMaster departmentmaster;
    private ProgramMaster programmaster;
    private String academicyear;
    private String attendanceapproved;
    //private String instituteid; 
    // private String registrationid;

    //private String facultysubjecttaggingunq;
    private String programid;
    private String subjectid;
    private String sectionid;
    private String basketid;
    private String departmentid;
    private String pstpopulated;
    private String subjectrunning;
    private String customfinalized;
    private Short stynumber;
    private String deactive;
    private Double credits;
    private Integer noofstudents;
    private Double totalmarks;
    private Double passingmarks;
    private String tthide;
    private String backpapertype;
    private Integer alloted;
    private String subjecttype;
    private String subjecttypeid;
    private String customauditflag;
    private String auditsubject;

    private Set<ProgramSubjectDetail> programsubjectdetails = new HashSet<ProgramSubjectDetail>(0);
    //private Set<FacultySubjectTagging> facultysubjecttaggings=new HashSet<FacultySubjectTagging>(0);

    public ProgramSubjectTagging() {
    }

    public ProgramSubjectTagging(ProgramSubjectTaggingId id, RegistrationMaster registrationmaster, SubjectMaster subjectmaster, Academicyear academicyear, SectionMaster sectionmaster, DepartmentMaster departmentmaster, ProgramMaster programmaster, String academicyearid, String programid, String subjectid, String sectionid, String pstpopulated, String subjectrunning, String customfinalized, Short stynumber, String deactive, Double credits, int noofstudents) {
        this.id = id;
        this.registrationmaster = registrationmaster;
        this.subjectmaster = subjectmaster;
        //  this.academicyear = academicyear;
        this.sectionmaster = sectionmaster;
        this.departmentmaster = departmentmaster;
        this.programmaster = programmaster;
        //this.academicyearid = academicyearid;
        this.programid = programid;
        this.subjectid = subjectid;
        this.sectionid = sectionid;
        this.pstpopulated = pstpopulated;
        this.subjectrunning = subjectrunning;
        this.customfinalized = customfinalized;
        this.stynumber = stynumber;
        this.deactive = deactive;
        this.credits = credits;
        this.noofstudents = noofstudents;
    }

    public ProgramSubjectTagging(ProgramSubjectTagging dto, boolean childReqd) {
        this.id = dto.getId();
        this.academicyear = dto.getAcademicyear();
        //this.instituteid = dto.getInstituteid();
        // this.registrationid = dto.getRegistrationid();
        this.programid = dto.getProgramid();
        this.subjectid = dto.getSubjectid();
        this.sectionid = dto.getSectionid();
        this.basketid = dto.getBasketid();
        this.departmentid = dto.getDepartmentid();
        this.pstpopulated = dto.getPstpopulated();
        this.subjectrunning = dto.getSubjectrunning();
        this.customfinalized = dto.getCustomfinalized();
        this.stynumber = dto.getStynumber();
        this.deactive = dto.getDeactive();
        this.credits = dto.getCredits();
        this.noofstudents = dto.getNoofstudents();
        this.tthide = dto.getTthide();
        this.auditsubject = dto.getAuditsubject();
        /*  if(childReqd){
         if(!dto.getProgramsubjectdetails().isEmpty()){
               for (Iterator<ProgramSubjectDetail> it = dto.getProgramsubjectdetails().iterator(); it.hasNext();) {
               this.programsubjectdetails.add(new ProgramSubjectDetail(it.next(),true));
               }
            }
          }*/
    }

    public ProgramSubjectTagging(ProgramSubjectTaggingId id, RegistrationMaster registrationmaster, Academicyear academicyear, SectionMaster sectionmaster, ProgramMaster programmaster, DepartmentMaster departmentmaster, SubjectMaster subjectmaster, String programid, String sectionid, Short stynumber, String auditsubject) {
        this.id = id;
        this.registrationmaster = registrationmaster;

        this.subjectmaster = subjectmaster;
        // this.academicyear = academicyear;
        this.sectionmaster = sectionmaster;
        this.programmaster = programmaster;
        this.departmentmaster = departmentmaster;
        this.programid = programid;
        this.sectionid = sectionid;
        this.stynumber = stynumber;
        this.auditsubject = auditsubject;
    }

    public ProgramSubjectTagging(ProgramSubjectTaggingId id, RegistrationMaster registrationmaster, SubjectMaster subjectmaster, Academicyear academicyear, String programid, String sectionid, Short stynumber, String deactive, Set programsubjectdetails, Set facultysubjecttaggings) {
        this.id = id;
        this.registrationmaster = registrationmaster;

        this.subjectmaster = subjectmaster;
        //this.academicyear = academicyear;
        this.programid = programid;
        this.sectionid = sectionid;
        this.stynumber = stynumber;
        this.deactive = deactive;
        this.programsubjectdetails = programsubjectdetails;
        // this.facultysubjecttaggings = facultysubjecttaggings;
    }

    public Integer getAlloted() {
        return alloted;
    }

    public void setAlloted(Integer alloted) {
        this.alloted = alloted;
    }

    public ProgramSubjectTaggingId getId() {
        return this.id;
    }

    public void setId(ProgramSubjectTaggingId id) {
        this.id = id;
    }

    public RegistrationMaster getRegistrationmaster() {
        return this.registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

    public SubjectMaster getSubjectmaster() {
        return this.subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    public String getProgramid() {
        return this.programid;
    }

    public void setProgramid(String programid) {
        this.programid = programid;
    }

    public String getSectionid() {
        return this.sectionid;
    }

    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }

    public Short getStynumber() {
        return stynumber;
    }

    public void setStynumber(Short stynumber) {
        this.stynumber = stynumber;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Double getCredits() {
        return credits;
    }

    public void setCredits(Double credits) {
        this.credits = credits;
    }

    public String getBasketid() {
        return basketid;
    }

    public void setBasketid(String basketid) {
        this.basketid = basketid;
    }

    public Set<ProgramSubjectDetail> getProgramsubjectdetails() {
        return programsubjectdetails;
    }

    public void setProgramsubjectdetails(Set<ProgramSubjectDetail> programsubjectdetails) {
        this.programsubjectdetails = programsubjectdetails;
    }

    public String getSubjectid() {
        return subjectid;
    }

    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    public String getCustomfinalized() {
        return customfinalized;
    }

    public void setCustomfinalized(String customfinalized) {
        this.customfinalized = customfinalized;
    }

    public String getPstpopulated() {
        return pstpopulated;
    }

    public void setPstpopulated(String pstpopulated) {
        this.pstpopulated = pstpopulated;
    }

    public String getSubjectrunning() {
        return subjectrunning;
    }

    public void setSubjectrunning(String subjectrunning) {
        this.subjectrunning = subjectrunning;
    }

    public DepartmentMaster getDepartmentmaster() {
        return departmentmaster;
    }

    public void setDepartmentmaster(DepartmentMaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }

    public ProgramMaster getProgrammaster() {
        return programmaster;
    }

    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }

    public SectionMaster getSectionmaster() {
        return sectionmaster;
    }

    public void setSectionmaster(SectionMaster sectionmaster) {
        this.sectionmaster = sectionmaster;
    }

    /*  public String getInstituteid() {
        return instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }*/
    public Academicyear getAcademicyearmaster() {
        return academicyearmaster;
    }

    public void setAcademicyearmaster(Academicyear academicyearmaster) {
        this.academicyearmaster = academicyearmaster;
    }

    /*  public String getRegistrationid() {
        return registrationid;
    }

    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }*/
    public String getAcademicyear() {
        return academicyear;
    }

    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    public String getDepartmentid() {
        return departmentid;
    }

    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

//     public Set<FacultySubjectTagging> getFacultysubjecttaggings() {
//        return facultysubjecttaggings;
//    }
//
//    public void setFacultysubjecttaggings(Set<FacultySubjectTagging> facultysubjecttaggings) {
//        this.facultysubjecttaggings = facultysubjecttaggings;
//    }
    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid() + "::" + id.getProgramsubjectid();
    }

    public Integer getNoofstudents() {
        return noofstudents;
    }

    public void setNoofstudents(Integer noofstudents) {
        this.noofstudents = noofstudents;
    }

    public Double getPassingmarks() {
        return passingmarks;
    }

    public void setPassingmarks(Double passingmarks) {
        this.passingmarks = passingmarks;
    }

    public Double getTotalmarks() {
        return totalmarks;
    }

    public void setTotalmarks(Double totalmarks) {
        this.totalmarks = totalmarks;
    }

    public String getAttendanceapproved() {
        return attendanceapproved;
    }

    public void setAttendanceapproved(String attendanceapproved) {
        this.attendanceapproved = attendanceapproved;
    }

    public String getTthide() {
        return tthide;
    }

    public void setTthide(String tthide) {
        this.tthide = tthide;
    }

    public String getBackpapertype() {
        return backpapertype;
    }

    public void setBackpapertype(String backpapertype) {
        this.backpapertype = backpapertype;
    }

    public String getSubjecttype() {
        return subjecttype;
    }

    public void setSubjecttype(String subjecttype) {
        this.subjecttype = subjecttype;
    }

    public String getSubjecttypeid() {
        return subjecttypeid;
    }

    public void setSubjecttypeid(String subjecttypeid) {
        this.subjecttypeid = subjecttypeid;
    }

    public String getCustomauditflag() {
        return customauditflag;
    }

    public void setCustomauditflag(String customauditflag) {
        this.customauditflag = customauditflag;
    }

    public String getAuditsubject() {
        return auditsubject;
    }

    public void setAuditsubject(String auditsubject) {
        this.auditsubject = auditsubject;
    }

}
