package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Prstudentsubjectchoicecount generated by hbm2java
 */
public class PRStudentSubjectChoiceCount  implements java.io.Serializable {


     private PRStudentSubjectChoiceCountId id;
     private StudentRegistration studentregistration;
  //   private BasketMaster basketmaster;
     private Byte subjectschoicescount;
     private String remarks;
     private String deactive;

    public PRStudentSubjectChoiceCount(PRStudentSubjectChoiceCount dto) {
        this.subjectschoicescount = dto.getSubjectschoicescount();
        this.id = dto.getId();
        this.remarks = dto.getRemarks();
        this.deactive = dto.getDeactive();
    }

     public PRStudentSubjectChoiceCount() {
    }
	
    public PRStudentSubjectChoiceCount(PRStudentSubjectChoiceCountId id, StudentRegistration studentregistration) {
        this.id = id;
        this.studentregistration = studentregistration;
     
    }
    public PRStudentSubjectChoiceCount(PRStudentSubjectChoiceCountId id, StudentRegistration studentregistration, Byte subjectschoicescount, String remarks, String deactive) {
       this.id = id;
       this.studentregistration = studentregistration;
       
       this.subjectschoicescount = subjectschoicescount;
       this.remarks = remarks;
       this.deactive = deactive;
    }
   
    public PRStudentSubjectChoiceCountId getId() {
        return this.id;
    }
    
    public void setId(PRStudentSubjectChoiceCountId id) {
        this.id = id;
    }
    public StudentRegistration getStudentregistration() {
        return this.studentregistration;
    }
    
    public void setStudentregistration(StudentRegistration studentregistration) {
        this.studentregistration = studentregistration;
    }
  
    public Byte getSubjectschoicescount() {
        return this.subjectschoicescount;
    }
    
    public void setSubjectschoicescount(Byte subjectschoicescount) {
        this.subjectschoicescount = subjectschoicescount;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }




}


