package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * PrsubjectfinalizationcriteriaId generated by hbm2java
 */
public class PRSubjectFinalizationCriteriaId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String academicyear;
     private String programid;
     private String sectionid;
     private byte stynumber;
     private String basketid;
     private String subjectid;

    public PRSubjectFinalizationCriteriaId() {
    }

    public PRSubjectFinalizationCriteriaId(String instituteid, String registrationid, String academicyear, String programid, String sectionid, byte stynumber, String basketid, String subjectid) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.academicyear = academicyear;
       this.programid = programid;
       this.sectionid = sectionid;
       this.stynumber = stynumber;
       this.basketid = basketid;
       this.subjectid = subjectid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getSectionid() {
        return this.sectionid;
    }
    
    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }
    public byte getStynumber() {
        return this.stynumber;
    }
    
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getBasketid() {
        return this.basketid;
    }
    
    public void setBasketid(String basketid) {
        this.basketid = basketid;
    }
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PRSubjectFinalizationCriteriaId) ) return false;
		 PRSubjectFinalizationCriteriaId castOther = ( PRSubjectFinalizationCriteriaId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && ( (this.getAcademicyear()==castOther.getAcademicyear()) || ( this.getAcademicyear()!=null && castOther.getAcademicyear()!=null && this.getAcademicyear().equals(castOther.getAcademicyear()) ) )
 && ( (this.getProgramid()==castOther.getProgramid()) || ( this.getProgramid()!=null && castOther.getProgramid()!=null && this.getProgramid().equals(castOther.getProgramid()) ) )
 && ( (this.getSectionid()==castOther.getSectionid()) || ( this.getSectionid()!=null && castOther.getSectionid()!=null && this.getSectionid().equals(castOther.getSectionid()) ) )
 && (this.getStynumber()==castOther.getStynumber())
 && ( (this.getBasketid()==castOther.getBasketid()) || ( this.getBasketid()!=null && castOther.getBasketid()!=null && this.getBasketid().equals(castOther.getBasketid()) ) )
 && ( (this.getSubjectid()==castOther.getSubjectid()) || ( this.getSubjectid()!=null && castOther.getSubjectid()!=null && this.getSubjectid().equals(castOther.getSubjectid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + ( getAcademicyear() == null ? 0 : this.getAcademicyear().hashCode() );
         result = 37 * result + ( getProgramid() == null ? 0 : this.getProgramid().hashCode() );
         result = 37 * result + ( getSectionid() == null ? 0 : this.getSectionid().hashCode() );
         result = 37 * result + this.getStynumber();
         result = 37 * result + ( getBasketid() == null ? 0 : this.getBasketid().hashCode() );
         result = 37 * result + ( getSubjectid() == null ? 0 : this.getSubjectid().hashCode() );
         return result;
   }   


}


