package com.jilit.irp.persistence.dto;
// Generated Feb 7, 2015 10:44:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Regcoordinatortagging generated by hbm2java
 */
public class RegCoordinatorTagging  implements java.io.Serializable {


     private RegCoordinatorTaggingId id;
     private StudentRegistration studentregistration;
     private CoordinatorType coordinatortype;
     private short stynumber;
     private Date entrydate;
     private String entryby;
     private String deactive;

    public RegCoordinatorTagging() {
    }

    public RegCoordinatorTagging(RegCoordinatorTagging dto) {
        this.id = dto.getId();
        this.stynumber = dto.getStynumber();
        this.entrydate = dto.getEntrydate();
        this.entryby = dto.getEntryby();
        this.deactive = dto.getDeactive();
    }


    public RegCoordinatorTagging(RegCoordinatorTaggingId id, StudentRegistration studentregistration, CoordinatorType coordinatortype, short stynumber) {
        this.id = id;
        this.studentregistration = studentregistration;
        this.coordinatortype = coordinatortype;
        this.stynumber = stynumber;
    }
    public RegCoordinatorTagging(RegCoordinatorTaggingId id, StudentRegistration studentregistration, CoordinatorType coordinatortype, short stynumber, Date entrydate, String entryby, String deactive) {
       this.id = id;
       this.studentregistration = studentregistration;
       this.coordinatortype = coordinatortype;
       this.stynumber = stynumber;
       this.entrydate = entrydate;
       this.entryby = entryby;
       this.deactive = deactive;
    }

    public CoordinatorType getCoordinatortype() {
        return coordinatortype;
    }

    public void setCoordinatortype(CoordinatorType coordinatortype) {
        this.coordinatortype = coordinatortype;
    }

    public RegCoordinatorTaggingId getId() {
        return id;
    }

    public void setId(RegCoordinatorTaggingId id) {
        this.id = id;
    }

    public StudentRegistration getStudentregistration() {
        return studentregistration;
    }

    public void setStudentregistration(StudentRegistration studentregistration) {
        this.studentregistration = studentregistration;
    }

    public short getStynumber() {
        return stynumber;
    }

    public void setStynumber(short stynumber) {
        this.stynumber = stynumber;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public String getEntryby() {
        return this.entryby;
    }

    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }
    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid() +"::"+ id.getCoordinatortypeid() + "::" + id.getGroupid() +"::"+ id.getStaffid() +"::"+ id.getStafftype() +"::"+ id.getStudentid();
    }


}


