package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RegistrationMaster generated by ashutosh1.kumar
 */
public class RegistrationMaster implements java.io.Serializable {

    private RegistrationMasterId id;
    private InstituteMaster institutemaster;
    private String registrationcode;
    private String registrationdesc;
    private Date registrationdatefrom;
    private Date registrationdateto;
    private String registrationcomplete;
    private String feecollection;
    private String finalized;
    private String finalizedby;
    private Date finalizeddate;
    private String placeofregistration;
    private String parentregistrationid;
    private String registrationcaption;
    private String lockregistration;
    private String excludeinprereg;
    private String excludeinsrs;
    private String excludeinattendance;
    private String excludeinclasstimetable;
    private String excludeindatesheet;
    private String excludeininvigdutyseatplan;
    private String preventcompleted;
    private String preventbroadcast;
    private Date preventfromdate;
    private Date preventenddate;
    private String deactive;
    private Date examperiodfrom;
    private String allowbackpaperreg;
    private String academicyear;
    private String gradesheetcaption;
    private Date supplregeventfrom;
    private Date supplregeventupto;
    private String registrationtype;
    private Date attendancefromdate;
    private Date attendancetodate;
    private Date courseregistrationdatefrom;
    private Date courseregistrationdateto;
    private Date hostelallocationfrom;
    private Date hostelallocationupto;
    private byte evenoddflag; 
    private String courseregcompleted;
    private String courseregbroadcast;
    private Date gipregfrom;
    private Date gipregistrationupto;
    private String gipregbroadcast;
    private Set<OfferedODSubjectTagging> offeredodsubjecttaggings = new HashSet<OfferedODSubjectTagging>(0);
    private Set<StudentNRSubjects> studentnrsubjectses = new HashSet<StudentNRSubjects>(0);
    private Set<ProgramSubjectTagging> programsubjecttaggings = new HashSet<ProgramSubjectTagging>(0);
    private Set<PRFacultyEvent> prfacultyevents = new HashSet<PRFacultyEvent>(0);
    private Set<StudentRegistration> studentregistrations = new HashSet<StudentRegistration>(0);
    private Set<PRSubjectFinalizationCriteria> prsubjectfinalizationcriterias = new HashSet<PRSubjectFinalizationCriteria>(0);
    private Set<LoadDistributionGrant> loaddistributiongrants = new HashSet<LoadDistributionGrant>(0);
    private Set<InstituteRegistrationEvents> instituteregistrationeventss = new HashSet<InstituteRegistrationEvents>(0);
    private Set<StudentHostelDetail> studenthosteldetails = new HashSet<StudentHostelDetail>(0);
    private Set<StudentPreviousAttendence> studentpreviousattendences = new HashSet<StudentPreviousAttendence>(0);
    private Set<Temp_DefaulterInPrereg> defaulterInPreregs = new HashSet<Temp_DefaulterInPrereg>(0);
    private Set<StudentShortAttendance> studentshortattendances = new HashSet<StudentShortAttendance>(0);
    private Set<CommitteeActionDetail> committeeactiondetails = new HashSet<CommitteeActionDetail>(0);
    private Set<ElectiveSubjectApproval> electivesubjectapproval = new HashSet<ElectiveSubjectApproval>(0);
    private Set<PRSubjectTypeWiseApproval> prsubjecttypewiseapprovals = new HashSet<PRSubjectTypeWiseApproval>(0);
    private Set<RegistrationFineMaster> registrationfinemasters = new HashSet<RegistrationFineMaster>(0);
    private Set<RegistrationMasterDetail> registrationmasterdetail = new HashSet<RegistrationMasterDetail>(0);
    private Set<StudentSubjectFacultyChoices> studentsubjectfacultychoiceses = new HashSet<StudentSubjectFacultyChoices>(0);
    private Set<ExamCenterWiseRooms> examcenterwiseroomses = new HashSet<ExamCenterWiseRooms>(0);
    private Set<InstituteElectiveTempData> instituteelectivetempdatas = new HashSet<InstituteElectiveTempData>(0);
    private Set<StudentDisciplinaryAction> studentdisciplinaryactions = new HashSet<StudentDisciplinaryAction>(0);
    private Set<TT_TimeTable> tt_timetables = new HashSet<TT_TimeTable>(0);
    private Set<Tmp_StudAttendSummary> tmp_studattendsummaries = new HashSet<Tmp_StudAttendSummary>(0);
    private Set<StudentAllowForExam> studentallowforexams = new HashSet<StudentAllowForExam>(0);
    private Set<SubjectWiseLoad> subjectwiseloads = new HashSet<SubjectWiseLoad>(0);
    private Set<AttendanceCutoffPercentage> attendancecutoffpercentages = new HashSet<AttendanceCutoffPercentage>(0);
    private Set<Attendancefollowupmaster> attendancefollowupmaster = new HashSet<Attendancefollowupmaster>(0);
    private Set<StudentNotOfferSubject> studentnotoffersubject = new HashSet<StudentNotOfferSubject>(0);

    public String getParentregistrationid() {
        return parentregistrationid;
    }

    public void setParentregistrationid(String parentregistrationid) {
        this.parentregistrationid = parentregistrationid;
    }

    
    
    
    
    public String getRegistrationtype() {
        return registrationtype;
    }

    public Set<RegistrationMasterDetail> getRegistrationmasterdetail() {
        return registrationmasterdetail;
    }

    public void setRegistrationmasterdetail(Set<RegistrationMasterDetail> registrationmasterdetail) {
        this.registrationmasterdetail = registrationmasterdetail;
    }

    public void setRegistrationtype(String registrationtype) {
        this.registrationtype = registrationtype;
    }

    public String getAcademicyear() {
        return academicyear;
    }

    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    public String getGradesheetcaption() {
        return gradesheetcaption;
    }

    public void setGradesheetcaption(String gradesheetcaption) {
        this.gradesheetcaption = gradesheetcaption;
    }

    public Date getExamperiodfrom() {
        return examperiodfrom;
    }

    public void setExamperiodfrom(Date examperiodfrom) {
        this.examperiodfrom = examperiodfrom;
    }

    public String getAllowbackpaperreg() {
        return allowbackpaperreg;
    }

    public void setAllowbackpaperreg(String allowbackpaperreg) {
        this.allowbackpaperreg = allowbackpaperreg;
    }

    public Set<StudentAllowForExam> getStudentallowforexams() {
        return studentallowforexams;
    }

    public void setStudentallowforexams(Set<StudentAllowForExam> studentallowforexams) {
        this.studentallowforexams = studentallowforexams;
    }

    public RegistrationMaster() {
    }

    public RegistrationMaster(String registrationcode, String registrationdesc) {
        this.registrationcode = registrationcode;
        this.registrationdesc = registrationdesc;
        //this.id = id.getRegistrationid();
    }

    public RegistrationMaster(RegistrationMasterId id, String registrationcode, String registrationdesc) {
        this.id = id;
        this.registrationcode = registrationcode;
        this.registrationdesc = registrationdesc;
    }

    public RegistrationMaster(RegistrationMaster dto, boolean childReqd) {
        this.id = dto.getId();
        // this.institutemaster = dto.getInstitutemaster();
        this.registrationcode = dto.getRegistrationcode();
        this.registrationdesc = dto.getRegistrationdesc();
        this.registrationdatefrom = dto.getRegistrationdatefrom();
        this.registrationdateto = dto.getRegistrationdateto();
        this.registrationcomplete = dto.getRegistrationcomplete();
        this.feecollection = dto.getFeecollection();
        this.finalized = dto.getFinalized();
        this.finalizedby = dto.getFinalizedby();
        this.finalizeddate = dto.getFinalizeddate();
        this.placeofregistration = dto.getPlaceofregistration();
        this.registrationcaption = dto.getRegistrationcaption();
        this.lockregistration = dto.getLockregistration();
        this.excludeinprereg = dto.getExcludeinprereg();
        this.excludeinsrs = dto.getExcludeinsrs();
        this.excludeinattendance = dto.getExcludeinattendance();
        this.excludeinclasstimetable = dto.getExcludeinclasstimetable();
        this.excludeindatesheet = dto.getExcludeindatesheet();
        this.excludeininvigdutyseatplan = dto.getExcludeininvigdutyseatplan();
        this.preventcompleted = dto.getPreventcompleted();
        this.preventbroadcast = dto.getPreventbroadcast();
        this.preventfromdate = dto.getPreventfromdate();
        this.preventenddate = dto.getPreventenddate();
        this.deactive = dto.getDeactive();
        this.attendancefromdate = dto.getAttendancefromdate();
        this.courseregistrationdatefrom = dto.getCourseregistrationdatefrom();
        this.attendancetodate = dto.getAttendancetodate();
        this.courseregistrationdateto = dto.getCourseregistrationdateto();
        this.evenoddflag = dto.getEvenoddflag();
    }

    public RegistrationMaster(RegistrationMaster dto) {
        this.id = dto.getId();
        this.registrationcode = dto.getRegistrationcode();
        this.registrationdesc = dto.getRegistrationdesc();
        this.registrationdatefrom = dto.getRegistrationdatefrom();
        this.registrationdateto = dto.getRegistrationdateto();
        this.registrationcomplete = dto.getRegistrationcomplete();
        this.feecollection = dto.getFeecollection();
        this.finalized = dto.getFinalized();
        this.finalizedby = dto.getFinalizedby();
        this.finalizeddate = dto.getFinalizeddate();
        this.placeofregistration = dto.getPlaceofregistration();
        this.registrationcaption = dto.getRegistrationcaption();
        this.lockregistration = dto.getLockregistration();
        this.excludeinprereg = dto.getExcludeinprereg();
        this.excludeinsrs = dto.getExcludeinsrs();
        this.excludeinattendance = dto.getExcludeinattendance();
        this.excludeinclasstimetable = dto.getExcludeinclasstimetable();
        this.excludeindatesheet = dto.getExcludeindatesheet();
        this.excludeininvigdutyseatplan = dto.getExcludeininvigdutyseatplan();
        this.preventcompleted = dto.getPreventcompleted();
        this.preventbroadcast = dto.getPreventbroadcast();
        this.preventfromdate = dto.getPreventfromdate();
        this.preventenddate = dto.getPreventenddate();
        this.deactive = dto.getDeactive();
        this.attendancefromdate = dto.getAttendancefromdate();
        this.attendancetodate = dto.getAttendancetodate();
        this.attendancetodate = dto.getAttendancetodate();
        this.courseregistrationdateto = dto.getCourseregistrationdateto();
        this.courseregistrationdatefrom = dto.getCourseregistrationdatefrom();
        this.evenoddflag = dto.getEvenoddflag();
    }

    /**
     * @return the id
     */
    public RegistrationMasterId getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(RegistrationMasterId id) {
        this.id = id;
    }

    /**
     * @return the institutemaster
     */
    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    /**
     * @param institutemaster the institutemaster to set
     */
    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    /**
     * @return the registrationcode
     */
    public String getRegistrationcode() {
        return registrationcode;
    }

    /**
     * @param registrationcode the registrationcode to set
     */
    public void setRegistrationcode(String registrationcode) {
        this.registrationcode = registrationcode;
    }

    /**
     * @return the registrationdesc
     */
    public String getRegistrationdesc() {
        return registrationdesc;
    }

    /**
     * @param registrationdesc the registrationdesc to set
     */
    public void setRegistrationdesc(String registrationdesc) {
        this.registrationdesc = registrationdesc;
    }

    /**
     * @return the registrationdatefrom
     */
    public Date getRegistrationdatefrom() {
        return registrationdatefrom;
    }

    /**
     * @param registrationdatefrom the registrationdatefrom to set
     */
    public void setRegistrationdatefrom(Date registrationdatefrom) {
        this.registrationdatefrom = registrationdatefrom;
    }

    /**
     * @return the registrationdateto
     */
    public Date getRegistrationdateto() {
        return registrationdateto;
    }

    /**
     * @param registrationdateto the registrationdateto to set
     */
    public void setRegistrationdateto(Date registrationdateto) {
        this.registrationdateto = registrationdateto;
    }

    /**
     * @return the registrationcomplete
     */
    public String getRegistrationcomplete() {
        return registrationcomplete;
    }

    /**
     * @param registrationcomplete the registrationcomplete to set
     */
    public void setRegistrationcomplete(String registrationcomplete) {
        this.registrationcomplete = registrationcomplete;
    }

    /**
     * @return the feecollection
     */
    public String getFeecollection() {
        return feecollection;
    }

    /**
     * @param feecollection the feecollection to set
     */
    public void setFeecollection(String feecollection) {
        this.feecollection = feecollection;
    }

    /**
     * @return the finalized
     */
    public String getFinalized() {
        return finalized;
    }

    /**
     * @param finalized the finalized to set
     */
    public void setFinalized(String finalized) {
        this.finalized = finalized;
    }

    /**
     * @return the finalizedby
     */
    public String getFinalizedby() {
        return finalizedby;
    }

    /**
     * @param finalizedby the finalizedby to set
     */
    public void setFinalizedby(String finalizedby) {
        this.finalizedby = finalizedby;
    }

    /**
     * @return the finalizeddate
     */
    public Date getFinalizeddate() {
        return finalizeddate;
    }

    /**
     * @param finalizeddate the finalizeddate to set
     */
    public void setFinalizeddate(Date finalizeddate) {
        this.finalizeddate = finalizeddate;
    }

    /**
     * @return the placeofregistration
     */
    public String getPlaceofregistration() {
        return placeofregistration;
    }

    /**
     * @param placeofregistration the placeofregistration to set
     */
    public void setPlaceofregistration(String placeofregistration) {
        this.placeofregistration = placeofregistration;
    }

    /**
     * @return the registrationcaption
     */
    public String getRegistrationcaption() {
        return registrationcaption;
    }

    /**
     * @param registrationcaption the registrationcaption to set
     */
    public void setRegistrationcaption(String registrationcaption) {
        this.registrationcaption = registrationcaption;
    }

    /**
     * @return the lockregistration
     */
    public String getLockregistration() {
        return lockregistration;
    }

    /**
     * @param lockregistration the lockregistration to set
     */
    public void setLockregistration(String lockregistration) {
        this.lockregistration = lockregistration;
    }

    /**
     * @return the excludeinprereg
     */
    public String getExcludeinprereg() {
        return excludeinprereg;
    }

    /**
     * @param excludeinprereg the excludeinprereg to set
     */
    public void setExcludeinprereg(String excludeinprereg) {
        this.excludeinprereg = excludeinprereg;
    }

    /**
     * @return the excludeinsrs
     */
    public String getExcludeinsrs() {
        return excludeinsrs;
    }

    /**
     * @param excludeinsrs the excludeinsrs to set
     */
    public void setExcludeinsrs(String excludeinsrs) {
        this.excludeinsrs = excludeinsrs;
    }

    /**
     * @return the excludeinattendance
     */
    public String getExcludeinattendance() {
        return excludeinattendance;
    }

    /**
     * @param excludeinattendance the excludeinattendance to set
     */
    public void setExcludeinattendance(String excludeinattendance) {
        this.excludeinattendance = excludeinattendance;
    }

    /**
     * @return the excludeinclasstimetable
     */
    public String getExcludeinclasstimetable() {
        return excludeinclasstimetable;
    }

    /**
     * @param excludeinclasstimetable the excludeinclasstimetable to set
     */
    public void setExcludeinclasstimetable(String excludeinclasstimetable) {
        this.excludeinclasstimetable = excludeinclasstimetable;
    }

    /**
     * @return the excludeindatesheet
     */
    public String getExcludeindatesheet() {
        return excludeindatesheet;
    }

    /**
     * @param excludeindatesheet the excludeindatesheet to set
     */
    public void setExcludeindatesheet(String excludeindatesheet) {
        this.excludeindatesheet = excludeindatesheet;
    }

    /**
     * @return the excludeininvigdutyseatplan
     */
    public String getExcludeininvigdutyseatplan() {
        return excludeininvigdutyseatplan;
    }

    /**
     * @param excludeininvigdutyseatplan the excludeininvigdutyseatplan to set
     */
    public void setExcludeininvigdutyseatplan(String excludeininvigdutyseatplan) {
        this.excludeininvigdutyseatplan = excludeininvigdutyseatplan;
    }

    /**
     * @return the preventcompleted
     */
    public String getPreventcompleted() {
        return preventcompleted;
    }

    /**
     * @param preventcompleted the preventcompleted to set
     */
    public void setPreventcompleted(String preventcompleted) {
        this.preventcompleted = preventcompleted;
    }

    /**
     * @return the preventbroadcast
     */
    public String getPreventbroadcast() {
        return preventbroadcast;
    }

    /**
     * @param preventbroadcast the preventbroadcast to set
     */
    public void setPreventbroadcast(String preventbroadcast) {
        this.preventbroadcast = preventbroadcast;
    }

    /**
     * @return the preventfromdate
     */
    public Date getPreventfromdate() {
        return preventfromdate;
    }

    /**
     * @param preventfromdate the preventfromdate to set
     */
    public void setPreventfromdate(Date preventfromdate) {
        this.preventfromdate = preventfromdate;
    }

    /**
     * @return the preventenddate
     */
    public Date getPreventenddate() {
        return preventenddate;
    }

    /**
     * @param preventenddate the preventenddate to set
     */
    public void setPreventenddate(Date preventenddate) {
        this.preventenddate = preventenddate;
    }

    /**
     * @return the offeredodsubjecttaggings
     */
    public Set<OfferedODSubjectTagging> getOfferedodsubjecttaggings() {
        return offeredodsubjecttaggings;
    }

    /**
     * @param offeredodsubjecttaggings the offeredodsubjecttaggings to set
     */
    public void setOfferedodsubjecttaggings(Set<OfferedODSubjectTagging> offeredodsubjecttaggings) {
        this.offeredodsubjecttaggings = offeredodsubjecttaggings;
    }

    /**
     * @return the studentnrsubjectses
     */
    public Set<StudentNRSubjects> getStudentnrsubjectses() {
        return studentnrsubjectses;
    }

    /**
     * @param studentnrsubjectses the studentnrsubjectses to set
     */
    public void setStudentnrsubjectses(Set<StudentNRSubjects> studentnrsubjectses) {
        this.studentnrsubjectses = studentnrsubjectses;
    }

    /**
     * @return the programsubjecttaggings
     */
    public Set<ProgramSubjectTagging> getProgramsubjecttaggings() {
        return programsubjecttaggings;
    }

    /**
     * @param programsubjecttaggings the programsubjecttaggings to set
     */
    public void setProgramsubjecttaggings(Set<ProgramSubjectTagging> programsubjecttaggings) {
        this.programsubjecttaggings = programsubjecttaggings;
    }

    /**
     * @return the prfacultyevents
     */
    public Set<PRFacultyEvent> getPrfacultyevents() {
        return prfacultyevents;
    }

    /**
     * @param prfacultyevents the prfacultyevents to set
     */
    public void setPrfacultyevents(Set<PRFacultyEvent> prfacultyevents) {
        this.prfacultyevents = prfacultyevents;
    }

    /**
     * @return the studentregistrations
     */
    public Set<StudentRegistration> getStudentregistrations() {
        return studentregistrations;
    }

    /**
     * @param studentregistrations the studentregistrations to set
     */
    public void setStudentregistrations(Set<StudentRegistration> studentregistrations) {
        this.studentregistrations = studentregistrations;
    }

    /**
     * @return the prsubjectfinalizationcriterias
     */
    public Set<PRSubjectFinalizationCriteria> getPrsubjectfinalizationcriterias() {
        return prsubjectfinalizationcriterias;
    }

    /**
     * @param prsubjectfinalizationcriterias the prsubjectfinalizationcriterias
     * to set
     */
    public void setPrsubjectfinalizationcriterias(Set<PRSubjectFinalizationCriteria> prsubjectfinalizationcriterias) {
        this.prsubjectfinalizationcriterias = prsubjectfinalizationcriterias;
    }

    /**
     * @return the loaddistributiongrants
     */
    public Set<LoadDistributionGrant> getLoaddistributiongrants() {
        return loaddistributiongrants;
    }

    /**
     * @param loaddistributiongrants the loaddistributiongrants to set
     */
    public void setLoaddistributiongrants(Set<LoadDistributionGrant> loaddistributiongrants) {
        this.loaddistributiongrants = loaddistributiongrants;
    }

    /**
     * @return the instituteregistrationeventss
     */
    public Set<InstituteRegistrationEvents> getInstituteregistrationeventss() {
        return instituteregistrationeventss;
    }

    public void setInstituteregistrationeventss(Set<InstituteRegistrationEvents> instituteregistrationeventss) {
        this.instituteregistrationeventss = instituteregistrationeventss;
    }

    /**
     * @return the studenthosteldetails
     */
    public Set<StudentHostelDetail> getStudenthosteldetails() {
        return studenthosteldetails;
    }

    /**
     * @param studenthosteldetails the studenthosteldetails to set
     */
    public void setStudenthosteldetails(Set<StudentHostelDetail> studenthosteldetails) {
        this.studenthosteldetails = studenthosteldetails;
    }

    public String getIdStr() {
        return id.getInstituteid() + ":" + id.getRegistrationid();
    }

    /**
     * @return the deactive
     */
    public String getDeactive() {
        return deactive;
    }

    /**
     * @param deactive the deactive to set
     */
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<StudentPreviousAttendence> getStudentpreviousattendences() {
        return studentpreviousattendences;
    }

    public void setStudentpreviousattendences(Set<StudentPreviousAttendence> studentpreviousattendences) {
        this.studentpreviousattendences = studentpreviousattendences;
    }

    public Set<Temp_DefaulterInPrereg> getDefaulterInPreregs() {
        return defaulterInPreregs;
    }

    public void setDefaulterInPreregs(Set<Temp_DefaulterInPrereg> defaulterInPreregs) {
        this.defaulterInPreregs = defaulterInPreregs;
    }

    public Set<StudentShortAttendance> getStudentshortattendances() {
        return studentshortattendances;
    }

    public void setStudentshortattendances(Set<StudentShortAttendance> studentshortattendances) {
        this.studentshortattendances = studentshortattendances;
    }

    public Set<CommitteeActionDetail> getCommitteeactiondetails() {
        return committeeactiondetails;
    }

    public void setCommitteeactiondetails(Set<CommitteeActionDetail> committeeactiondetails) {
        this.committeeactiondetails = committeeactiondetails;
    }

    public Set<ElectiveSubjectApproval> getElectivesubjectapproval() {
        return electivesubjectapproval;
    }

    public void setElectivesubjectapproval(Set<ElectiveSubjectApproval> electivesubjectapproval) {
        this.electivesubjectapproval = electivesubjectapproval;
    }

    public Set<PRSubjectTypeWiseApproval> getPrsubjecttypewiseapprovals() {
        return prsubjecttypewiseapprovals;
    }

    public void setPrsubjecttypewiseapprovals(Set<PRSubjectTypeWiseApproval> prsubjecttypewiseapprovals) {
        this.prsubjecttypewiseapprovals = prsubjecttypewiseapprovals;
    }

    public Set<RegistrationFineMaster> getRegistrationfinemasters() {
        return registrationfinemasters;
    }

    public void setRegistrationfinemasters(Set<RegistrationFineMaster> registrationfinemasters) {
        this.registrationfinemasters = registrationfinemasters;
    }

    public Set<StudentSubjectFacultyChoices> getStudentsubjectfacultychoiceses() {
        return studentsubjectfacultychoiceses;
    }

    public void setStudentsubjectfacultychoiceses(Set<StudentSubjectFacultyChoices> studentsubjectfacultychoiceses) {
        this.studentsubjectfacultychoiceses = studentsubjectfacultychoiceses;
    }

    public Set<ExamCenterWiseRooms> getExamcenterwiseroomses() {
        return examcenterwiseroomses;
    }

    public void setExamcenterwiseroomses(Set<ExamCenterWiseRooms> examcenterwiseroomses) {
        this.examcenterwiseroomses = examcenterwiseroomses;
    }

    public Set<InstituteElectiveTempData> getInstituteelectivetempdatas() {
        return instituteelectivetempdatas;
    }

    public void setInstituteelectivetempdatas(Set<InstituteElectiveTempData> instituteelectivetempdatas) {
        this.instituteelectivetempdatas = instituteelectivetempdatas;
    }

    public Set<StudentDisciplinaryAction> getStudentdisciplinaryactions() {
        return studentdisciplinaryactions;
    }

    public void setStudentdisciplinaryactions(Set<StudentDisciplinaryAction> studentdisciplinaryactions) {
        this.studentdisciplinaryactions = studentdisciplinaryactions;
    }

    public Set<TT_TimeTable> getTt_timetables() {
        return tt_timetables;
    }

    public void setTt_timetables(Set<TT_TimeTable> tt_timetables) {
        this.tt_timetables = tt_timetables;
    }

    public Set<Tmp_StudAttendSummary> getTmp_studattendsummaries() {
        return tmp_studattendsummaries;
    }

    public void setTmp_studattendsummaries(Set<Tmp_StudAttendSummary> tmp_studattendsummaries) {
        this.tmp_studattendsummaries = tmp_studattendsummaries;
    }

    public Set<SubjectWiseLoad> getSubjectwiseloads() {
        return subjectwiseloads;
    }

    public void setSubjectwiseloads(Set<SubjectWiseLoad> subjectwiseloads) {
        this.subjectwiseloads = subjectwiseloads;
    }

    public Set<AttendanceCutoffPercentage> getAttendancecutoffpercentages() {
        return attendancecutoffpercentages;
    }

    public void setAttendancecutoffpercentages(Set<AttendanceCutoffPercentage> attendancecutoffpercentages) {
        this.attendancecutoffpercentages = attendancecutoffpercentages;
    }

    public Set<Attendancefollowupmaster> getAttendancefollowupmaster() {
        return attendancefollowupmaster;
    }

    public void setAttendancefollowupmaster(Set<Attendancefollowupmaster> attendancefollowupmaster) {
        this.attendancefollowupmaster = attendancefollowupmaster;
    }

    public Set<StudentNotOfferSubject> getStudentnotoffersubject() {
        return studentnotoffersubject;
    }

    public void setStudentnotoffersubject(Set<StudentNotOfferSubject> studentnotoffersubject) {
        this.studentnotoffersubject = studentnotoffersubject;
    }

    //amandeep changes start
    public Date getAttendancefromdate() {
        return attendancefromdate;
    }

    public void setAttendancefromdate(Date attendancefromdate) {
        this.attendancefromdate = attendancefromdate;
    }

    public Date getAttendancetodate() {
        return attendancetodate;
    }

    public void setAttendancetodate(Date attendancetodate) {
        this.attendancetodate = attendancetodate;
    }

    public Date getCourseregistrationdatefrom() {
        return courseregistrationdatefrom;
    }

    public void setCourseregistrationdatefrom(Date courseregistrationdatefrom) {
        this.courseregistrationdatefrom = courseregistrationdatefrom;
    }

    public Date getCourseregistrationdateto() {
        return courseregistrationdateto;
    }

    public void setCourseregistrationdateto(Date courseregistrationdateto) {
        this.courseregistrationdateto = courseregistrationdateto;
    }
    //amandeep changes ends

    

    public Date getHostelallocationfrom() {
        return hostelallocationfrom;
    }

    public void setHostelallocationfrom(Date hostelallocationfrom) {
        this.hostelallocationfrom = hostelallocationfrom;
    }

    public Date getHostelallocationupto() {
        return hostelallocationupto;
    }

    public void setHostelallocationupto(Date hostelallocationupto) {
        this.hostelallocationupto = hostelallocationupto;
    }

    public String getCourseregcompleted() {
        return courseregcompleted;
    }

    public void setCourseregcompleted(String courseregcompleted) {
        this.courseregcompleted = courseregcompleted;
    }

    public String getCourseregbroadcast() {
        return courseregbroadcast;
    }

    public void setCourseregbroadcast(String courseregbroadcast) {
        this.courseregbroadcast = courseregbroadcast;
    }

    public Date getGipregfrom() {
        return gipregfrom;
    }

    public void setGipregfrom(Date gipregfrom) {
        this.gipregfrom = gipregfrom;
    }

    public Date getGipregistrationupto() {
        return gipregistrationupto;
    }

    public void setGipregistrationupto(Date gipregistrationupto) {
        this.gipregistrationupto = gipregistrationupto;
    }

    public String getGipregbroadcast() {
        return gipregbroadcast;
    }

    public void setGipregbroadcast(String gipregbroadcast) {
        this.gipregbroadcast = gipregbroadcast;
    }

    public Date getSupplregeventfrom() {
        return supplregeventfrom;
    }

    public void setSupplregeventfrom(Date supplregeventfrom) {
        this.supplregeventfrom = supplregeventfrom;
    }

    public Date getSupplregeventupto() {
        return supplregeventupto;
    }

    public void setSupplregeventupto(Date supplregeventupto) {
        this.supplregeventupto = supplregeventupto;
    }

    public byte getEvenoddflag() {
        return evenoddflag;
    }

    public void setEvenoddflag(byte evenoddflag) {
        this.evenoddflag = evenoddflag;
    }
    
    
    
}
