package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * RollNumberingSetupId generated by hbm2java
 */
public class RollNumberingSetupId  implements java.io.Serializable {


     private String instituteid;
     private String groupid;

    public RollNumberingSetupId() {
    }

    public RollNumberingSetupId(String instituteid, String groupid) {
       this.instituteid = instituteid;
       this.groupid = groupid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RollNumberingSetupId) ) return false;
		 RollNumberingSetupId castOther = ( RollNumberingSetupId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getGroupid()==castOther.getGroupid()) || ( this.getGroupid()!=null && castOther.getGroupid()!=null && this.getGroupid().equals(castOther.getGroupid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getGroupid() == null ? 0 : this.getGroupid().hashCode() );
         return result;
   }   


}


