package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RollNumberingSetup generated by hbm2java
 */
public class RollNumberingSetup  implements java.io.Serializable {


     private RollNumberingSetupId id;
     private InstituteMaster institutemaster;
     private Short codelength;
     private String prefix;
     private String suffix;
     private String institutecode;
     private String academicyear;
     private String programtype;
     private String programcode;
     private String branchcode;
     private String mm;
     private String yy;
     private Byte runningno;
     private String seqid;
     private Set<RollNumberingSetupDetail> rollnumberingsetupdetails = new HashSet<RollNumberingSetupDetail>(0);
     private Set<RollNumberingControl> rollnumberingcontrols = new HashSet<RollNumberingControl>(0);

    public RollNumberingSetup() {
    }
public RollNumberingSetup(RollNumberingSetup dto) {

       this.id =dto.getId();
       //this.institutemaster = institutemaster;
       this.codelength = dto.getCodelength();
       this.prefix =dto.getPrefix();
       this.suffix = dto.getSuffix();
       this.institutecode = dto.getInstitutecode();
       this.academicyear = dto.getAcademicyear();
       this.programtype = dto.getProgramtype();
       this.programcode = dto.getProgramcode();
       this.branchcode = dto.getBranchcode();
       this.mm = dto.getMm();
       this.yy = dto.getYy();
       this.runningno = dto.getRunningno();
       this.seqid = dto.getSeqid();
      // this.rollnumberingsetupdetails = dto.getRollnumberingsetupdetails();
      // this.rollnumberingcontrols = dto.getRollnumberingcontrols();
    }
	
    public RollNumberingSetup(RollNumberingSetupId id, InstituteMaster institutemaster, Short codelength) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.codelength = codelength;
    }
    public RollNumberingSetup(RollNumberingSetupId id, InstituteMaster institutemaster, Short codelength, String prefix, String suffix, String institutecode, String academicyear, String programtype, String programcode, String branchcode, String mm, String yy, Byte runningno, String seqid, Set<RollNumberingSetupDetail> rollnumberingsetupdetails, Set<RollNumberingControl> rollnumberingcontrols) {
       this.id = id;
       this.institutemaster = institutemaster;
       this.codelength = codelength;
       this.prefix = prefix;
       this.suffix = suffix;
       this.institutecode = institutecode;
       this.academicyear = academicyear;
       this.programtype = programtype;
       this.programcode = programcode;
       this.branchcode = branchcode;
       this.mm = mm;
       this.yy = yy;
       this.runningno = runningno;
       this.seqid = seqid;
       this.rollnumberingsetupdetails = rollnumberingsetupdetails;
       this.rollnumberingcontrols = rollnumberingcontrols;
    }
   
    public RollNumberingSetupId getId() {
        return this.id;
    }
    
    public void setId(RollNumberingSetupId id) {
        this.id = id;
    }
 
    public Short getCodelength() {
        return this.codelength;
    }
    
    public void setCodelength(Short codelength) {
        this.codelength = codelength;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public String getSuffix() {
        return this.suffix;
    }
    
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }
    public String getInstitutecode() {
        return this.institutecode;
    }
    
    public void setInstitutecode(String institutecode) {
        this.institutecode = institutecode;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    public String getProgramcode() {
        return this.programcode;
    }
    
    public void setProgramcode(String programcode) {
        this.programcode = programcode;
    }
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }
    public String getMm() {
        return this.mm;
    }
    
    public void setMm(String mm) {
        this.mm = mm;
    }
    public String getYy() {
        return this.yy;
    }
    
    public void setYy(String yy) {
        this.yy = yy;
    }
    public Byte getRunningno() {
        return this.runningno;
    }
    
    public void setRunningno(Byte runningno) {
        this.runningno = runningno;
    }
    public String getSeqid() {
        return this.seqid;
    }
    
    public void setSeqid(String seqid) {
        this.seqid = seqid;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    public String getProgramtype() {
        return programtype;
    }

    public void setProgramtype(String programtype) {
        this.programtype = programtype;
    }

    public Set<RollNumberingControl> getRollnumberingcontrols() {
        return rollnumberingcontrols;
    }

    public void setRollnumberingcontrols(Set<RollNumberingControl> rollnumberingcontrols) {
        this.rollnumberingcontrols = rollnumberingcontrols;
    }

    public Set<RollNumberingSetupDetail> getRollnumberingsetupdetails() {
        return rollnumberingsetupdetails;
    }

    public void setRollnumberingsetupdetails(Set<RollNumberingSetupDetail> rollnumberingsetupdetails) {
        this.rollnumberingsetupdetails = rollnumberingsetupdetails;
    }
  

 public String getIdStr() {
        return id.getInstituteid() + "::" + id.getGroupid();
    }


}


