package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * RoomusedformasterId generated by hbm2java
 */
public class RoomUsedForMasterId  implements java.io.Serializable {


     private String instituteid;
     private String roomusedforid;

    public RoomUsedForMasterId() {
    }

    public RoomUsedForMasterId(String instituteid, String roomusedforid) {
       this.instituteid = instituteid;
       this.roomusedforid = roomusedforid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRoomusedforid() {
        return this.roomusedforid;
    }
    
    public void setRoomusedforid(String roomusedforid) {
        this.roomusedforid = roomusedforid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RoomUsedForMasterId) ) return false;
		 RoomUsedForMasterId castOther = ( RoomUsedForMasterId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRoomusedforid()==castOther.getRoomusedforid()) || ( this.getRoomusedforid()!=null && castOther.getRoomusedforid()!=null && this.getRoomusedforid().equals(castOther.getRoomusedforid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRoomusedforid() == null ? 0 : this.getRoomusedforid().hashCode() );
         return result;
   }   


}


