package com.jilit.irp.persistence.dto;
// Generated May 6, 2011 11:20:07 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * ScholarshipCriteria generated by hbm2java
 */
public class ScholarshipSessionMaster implements java.io.Serializable {

    private String sessionid;
    private String sessioncode;
    private String sessiondesc;
    private String deactive;
    private Set<ScholarshipCriteria> scholarshipcriterias = new HashSet<ScholarshipCriteria>(0);
    private Set<ScholarshipPayment> scholarshippayments = new HashSet<ScholarshipPayment>(0);

    public ScholarshipSessionMaster() {
    }

    public ScholarshipSessionMaster(String sessioncode) {
        this.sessioncode=sessioncode;


    }

     public ScholarshipSessionMaster(String sessionid, String sessioncode) {
        this.sessionid = sessionid;
         this.sessioncode=sessioncode;


    }

    public ScholarshipSessionMaster(ScholarshipSessionMaster dto) {
        this.sessionid = dto.getSessionid();
        this.sessioncode = dto.getSessioncode();
        this.sessiondesc = dto.getSessiondesc();
        this.deactive = dto.getDeactive();
    }

     public ScholarshipSessionMaster(String sessionid,String sessioncode,String sessiondesc) {
        this.sessionid = sessionid;
        this.sessioncode = sessioncode;
        this.sessiondesc = sessiondesc;
    }

    public ScholarshipSessionMaster(ScholarshipSessionMaster dto, Boolean childReq) {
        this.sessionid = dto.getSessionid();
        this.sessioncode = dto.getSessioncode();
        this.sessiondesc = dto.getSessiondesc();
        this.deactive = dto.getDeactive();
        if (childReq) {
            if (!dto.getScholarshipcriterias().isEmpty()) {
                for (Iterator<ScholarshipCriteria> it = dto.getScholarshipcriterias().iterator(); it.hasNext();) {
                    this.scholarshipcriterias.add(new ScholarshipCriteria(it.next()));
                }
            }

        }
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<ScholarshipCriteria> getScholarshipcriterias() {
        return scholarshipcriterias;
    }

    public void setScholarshipcriterias(Set<ScholarshipCriteria> scholarshipcriterias) {
        this.scholarshipcriterias = scholarshipcriterias;
    }

    public String getSessioncode() {
        return sessioncode;
    }

    public void setSessioncode(String sessioncode) {
        this.sessioncode = sessioncode;
    }

    public String getSessiondesc() {
        return sessiondesc;
    }

    public void setSessiondesc(String sessiondesc) {
        this.sessiondesc = sessiondesc;
    }

    public String getSessionid() {
        return sessionid;
    }

    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    public Set<ScholarshipPayment> getScholarshippayments() {
        return scholarshippayments;
    }

    public void setScholarshippayments(Set<ScholarshipPayment> scholarshippayments) {
        this.scholarshippayments = scholarshippayments;
    }
    

}


