package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.HashSet;
import java.util.Set;

/**
 * Sct_IrpUserType generated by hbm2java
 */
public class Sct_IrpUserType  implements java.io.Serializable {


     private String usertype;
     private String userdescription;
     private String deactive;
     private String referenceinfo;
     private Byte seqid;
     private String loginidinstitutebased;
     private BigDecimal sessiontimeout;
     private Set<Sct_IrpUserType> approvedbymembertypes = new HashSet<Sct_IrpUserType>(0);
     private Set<Sct_IrpUserType> requestbymembertypes = new HashSet<Sct_IrpUserType>(0);
     public Sct_IrpUserType() {
    }

    public Sct_IrpUserType(String usertype, String userdescription, String deactive, String referenceinfo, Byte seqid, String loginidinstitutebased, BigDecimal sessiontimeout) {
        this.usertype = usertype;
        this.userdescription = userdescription;
        this.deactive = deactive;
        this.referenceinfo = referenceinfo;
        this.seqid = seqid;
        this.loginidinstitutebased = loginidinstitutebased;
        this.sessiontimeout = sessiontimeout;
    }

    public Sct_IrpUserType(Sct_IrpUserType dto) {
        this.usertype = dto.getUsertype();
        this.userdescription = dto.getUserdescription();
        this.deactive = dto.getDeactive();
        this.referenceinfo = dto.getReferenceinfo();
        this.seqid = dto.getSeqid();
        this.loginidinstitutebased = dto.getLoginidinstitutebased();
        this.sessiontimeout = dto.getSessiontimeout();
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getLoginidinstitutebased() {
        return loginidinstitutebased;
    }

    public void setLoginidinstitutebased(String loginidinstitutebased) {
        this.loginidinstitutebased = loginidinstitutebased;
    }

    public String getReferenceinfo() {
        return referenceinfo;
    }

    public void setReferenceinfo(String referenceinfo) {
        this.referenceinfo = referenceinfo;
    }

    public byte getSeqid() {
        return seqid;
    }

    public void setSeqid(Byte seqid) {
        this.seqid = seqid;
    }

    public String getUserdescription() {
        return userdescription;
    }

    public void setUserdescription(String userdescription) {
        this.userdescription = userdescription;
    }

    public String getUsertype() {
        return usertype;
    }

    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
    
    public BigDecimal getSessiontimeout() {
        return this.sessiontimeout;
    }

    public void setSessiontimeout(BigDecimal sessiontimeout) {
        this.sessiontimeout = sessiontimeout;
    }

    public Set<Sct_IrpUserType> getApprovedbymembertypes() {
        return approvedbymembertypes;
    }

    public void setApprovedbymembertypes(Set<Sct_IrpUserType> approvedbymembertypes) {
        this.approvedbymembertypes = approvedbymembertypes;
    }

    public Set<Sct_IrpUserType> getRequestbymembertypes() {
        return requestbymembertypes;
    }

    public void setRequestbymembertypes(Set<Sct_IrpUserType> requestbymembertypes) {
        this.requestbymembertypes = requestbymembertypes;
    }
	
}


