package com.jilit.irp.persistence.dto;
// Generated Apr 5, 2010 1:53:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Sct_kioskmarqueetextId generated by hbm2java
 */
public class Sct_KioskMarqueeTextId  implements java.io.Serializable {


     private String instituteid;
     private short sno;

    public Sct_KioskMarqueeTextId() {
    }

    public Sct_KioskMarqueeTextId(String instituteid, short sno) {
       this.instituteid = instituteid;
       this.sno = sno;
    }

    public String getInstituteid() {
        return this.instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public short getSno() {
        return this.sno;
    }

    public void setSno(short sno) {
        this.sno = sno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sct_KioskMarqueeTextId) ) return false;
		 Sct_KioskMarqueeTextId castOther = ( Sct_KioskMarqueeTextId ) other;

		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && (this.getSno()==castOther.getSno());
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + this.getSno();
         return result;
   }


}


