package com.jilit.irp.persistence.dto;
// Generated 1 May, 2012 10:26:58 AM by Hibernate Tools 3.2.1.GA



/**
 * Sct#unsuccesslogindetailId generated by hbm2java
 */
public class Sct_unsuccesslogindetailId  implements java.io.Serializable {


     private String instituteid;
     private String unqid;

    public Sct_unsuccesslogindetailId() {
    }

    public Sct_unsuccesslogindetailId(String instituteid, String unqid) {
       this.instituteid = instituteid;
       this.unqid = unqid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getUnqid() {
        return this.unqid;
    }
    
    public void setUnqid(String unqid) {
        this.unqid = unqid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sct_unsuccesslogindetailId) ) return false;
		 Sct_unsuccesslogindetailId castOther = ( Sct_unsuccesslogindetailId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getUnqid()==castOther.getUnqid()) || ( this.getUnqid()!=null && castOther.getUnqid()!=null && this.getUnqid().equals(castOther.getUnqid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getUnqid() == null ? 0 : this.getUnqid().hashCode() );
         return result;
   }   


}


