package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sct_IrpModules generated by hbm2java
 */
public class Sct_IrpModules  implements java.io.Serializable {


     private String moduleid;
     private String parentid;   
     private Sct_IrpModules sct_irpmodules;
     private String modulecode;    
     private String moduledesc1;
     private String moduledesc2;
     private String deactive;
     private Short seqid;
     private String moduletype;
     private String counsellingmodule;
     private String appliacablefor;
     public String commonmodule;
     private Set<Parameters> parameterss = new HashSet<Parameters>(0);
     private Set<Sct_IrpModules> sct_irpmoduleses = new HashSet<Sct_IrpModules>(0);
      

    public Sct_IrpModules() {
    }

    


    public Sct_IrpModules(String moduleid, String modulecode) {
        this.moduleid = moduleid;
        this.modulecode = modulecode;
    }
    public Sct_IrpModules(String moduleid, Sct_IrpModules sct_irpmodules, String modulecode, String moduledesc1, String moduledesc2, String deactive, Short seqid, String moduletype, String appliacablefor,Set parameterss, Set sct_irpmoduleses) {
       this.moduleid = moduleid;
       this.sct_irpmodules = sct_irpmodules;
       this.modulecode = modulecode;
       this.moduledesc1 = moduledesc1;
       this.moduledesc2 = moduledesc2;
       this.deactive = deactive;
       this.seqid = seqid;
       this.moduletype = moduletype;
       this.appliacablefor = appliacablefor;
       this.parameterss = parameterss;
       this.sct_irpmoduleses = sct_irpmoduleses;
      // this.sct_modulerightsmasters = sct_modulerightsmasters;
    }


    public Sct_IrpModules(Sct_IrpModules dto) {
        this.moduleid = dto.getModuleid();
        this.modulecode = dto.getModulecode();
        this.parentid = dto.getParentid();
        this.moduledesc1 = dto.getModuledesc1();
        this.moduledesc2 = dto.getModuledesc2();
        this.deactive = dto.getDeactive();
        this.seqid = dto.getSeqid();
        this.moduletype = dto.getModuletype();
        this.appliacablefor = dto.getAppliacablefor();
        this.commonmodule=dto.getCommonmodule();
    }

    public String getCommonmodule() {
        return commonmodule;
    }

    public void setCommonmodule(String commonmodule) {
        this.commonmodule = commonmodule;
    }


    public String getModuleid() {
        return this.moduleid;
    }

    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }
    public Sct_IrpModules getSct_irpmodules() {
        return this.sct_irpmodules;
    }

    public void setSct_irpmodules(Sct_IrpModules sct_irpmodules) {
        this.sct_irpmodules = sct_irpmodules;
    }
    public String getModulecode() {
        return this.modulecode;
    }

    public void setModulecode(String modulecode) {
        this.modulecode = modulecode;
    }

     public String getParentid() {
        return parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }
    
    public String getModuledesc1() {
        return this.moduledesc1;
    }

    public void setModuledesc1(String moduledesc1) {
        this.moduledesc1 = moduledesc1;
    }
    public String getModuledesc2() {
        return this.moduledesc2;
    }

    public void setModuledesc2(String moduledesc2) {
        this.moduledesc2 = moduledesc2;
    }
    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
    public Short getSeqid() {
        return this.seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }
    public String getModuletype() {
        return this.moduletype;
    }

    public void setModuletype(String moduletype) {
        this.moduletype = moduletype;
    }
    public String getAppliacablefor() {
        return this.appliacablefor;
    }

    public void setAppliacablefor(String appliacablefor) {
        this.appliacablefor = appliacablefor;
    }
    
     public Set<Parameters> getParameterss() {
        return parameterss;
    }

    public void setParameterss(Set<Parameters> parameterss) {
        this.parameterss = parameterss;
    }

     public Set<Sct_IrpModules> getSct_irpmoduleses() {
        return sct_irpmoduleses;
    }

    public void setSct_irpmoduleses(Set<Sct_IrpModules> sct_irpmoduleses) {
        this.sct_irpmoduleses = sct_irpmoduleses;
    }

    public String getCounsellingmodule() {
        return counsellingmodule;
    }

    public void setCounsellingmodule(String counsellingmodule) {
        this.counsellingmodule = counsellingmodule;
    }
    
    
}


