package com.jilit.irp.persistence.dto;
// Generated Sep 6, 2017 12:13:06 PM by Hibernate Tools 3.2.1.GA

/**
 * Sct#userrolescriterabasedId generated by hbm2java
 */
public class Sct_UserRolesCriteraBasedId  implements java.io.Serializable {


     private String userid;
     private String roleid;
     private String rightsbasedon;
     private String rightsbasedid;

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
    public String getRightsbasedon() {
        return this.rightsbasedon;
    }
    
    public void setRightsbasedon(String rightsbasedon) {
        this.rightsbasedon = rightsbasedon;
    }
    public String getRightsbasedid() {
        return this.rightsbasedid;
    }
    
    public void setRightsbasedid(String rightsbasedid) {
        this.rightsbasedid = rightsbasedid;
    }
    
    public Sct_UserRolesCriteraBasedId()
    {
        
    }
    public Sct_UserRolesCriteraBasedId(String userid,String roleid,String rightsbasedon,String rightsbasedid){
        this.userid=userid;
        this.roleid=roleid;
        this.rightsbasedon=rightsbasedon;
        this.rightsbasedid=rightsbasedid;
    }

}


