package com.jilit.irp.persistence.dto;
// Generated 17 Sep, 2016 3:22:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sdl_schedulemailtask generated by hbm2java
 */
public class Sdl_ScheduleMailTask  implements java.io.Serializable {


     private Sdl_ScheduleMailTaskId id;
     private Sdl_ScheduleTaskMaster sdl_scheduletaskmaster;
     private Sdl_SchedularMaster sdl_schedularmaster;
     private String sendername;
     private String senderdesignation;
     private String emailsubject;
     private String emailbody;
     private String toemailname;
     private String hasattachement;
     private Boolean priority;
     private Date scheduleddatetime;
     private Date actualsendingdatetime;
     private String status;
     private Date resenddate1;
     private String resendstatus;
     private Date resenddate2;
     private String deactive;

    public Sdl_ScheduleMailTask() {
    }

	
    public Sdl_ScheduleMailTask(Sdl_ScheduleMailTaskId id, Sdl_ScheduleTaskMaster sdl_scheduletaskmaster, Sdl_SchedularMaster sdl_schedularmaster) {
        this.id = id;
        this.sdl_scheduletaskmaster = sdl_scheduletaskmaster;
        this.sdl_schedularmaster = sdl_schedularmaster;
    }
    public Sdl_ScheduleMailTask(Sdl_ScheduleMailTaskId id, Sdl_ScheduleTaskMaster sdl_scheduletaskmaster, Sdl_SchedularMaster sdl_schedularmaster, String sendername, String senderdesignation, String emailsubject, String emailbody, String toemailname, String hasattachement, Boolean priority, Date scheduleddatetime, Date actualsendingdatetime, String status, Date resenddate1, String resendstatus, Date resenddate2, String deactive) {
       this.id = id;
       this.sdl_scheduletaskmaster = sdl_scheduletaskmaster;
       this.sdl_schedularmaster = sdl_schedularmaster;
       this.sendername = sendername;
       this.senderdesignation = senderdesignation;
       this.emailsubject = emailsubject;
       this.emailbody = emailbody;
       this.toemailname = toemailname;
       this.hasattachement = hasattachement;
       this.priority = priority;
       this.scheduleddatetime = scheduleddatetime;
       this.actualsendingdatetime = actualsendingdatetime;
       this.status = status;
       this.resenddate1 = resenddate1;
       this.resendstatus = resendstatus;
       this.resenddate2 = resenddate2;
       this.deactive = deactive;
    }
   
    public Sdl_ScheduleMailTaskId getId() {
        return this.id;
    }
    
    public void setId(Sdl_ScheduleMailTaskId id) {
        this.id = id;
    }
    public Sdl_ScheduleTaskMaster getSdl_scheduletaskmaster() {
        return this.sdl_scheduletaskmaster;
    }
    
    public void setSdl_scheduletaskmaster(Sdl_ScheduleTaskMaster sdl_scheduletaskmaster) {
        this.sdl_scheduletaskmaster = sdl_scheduletaskmaster;
    }

    public Sdl_SchedularMaster getSdl_schedularmaster() {
        return sdl_schedularmaster;
    }
      
    public void setSdl_schedularmaster(Sdl_SchedularMaster sdl_schedularmaster) {
        this.sdl_schedularmaster = sdl_schedularmaster;
    }
    public String getSendername() {
        return this.sendername;
    }
    
    public void setSendername(String sendername) {
        this.sendername = sendername;
    }
    public String getSenderdesignation() {
        return this.senderdesignation;
    }
    
    public void setSenderdesignation(String senderdesignation) {
        this.senderdesignation = senderdesignation;
    }
    public String getEmailsubject() {
        return this.emailsubject;
    }
    
    public void setEmailsubject(String emailsubject) {
        this.emailsubject = emailsubject;
    }
    public String getEmailbody() {
        return this.emailbody;
    }
    
    public void setEmailbody(String emailbody) {
        this.emailbody = emailbody;
    }
    public String getToemailname() {
        return this.toemailname;
    }
    
    public void setToemailname(String toemailname) {
        this.toemailname = toemailname;
    }
    public String getHasattachement() {
        return this.hasattachement;
    }
    
    public void setHasattachement(String hasattachement) {
        this.hasattachement = hasattachement;
    }
    public Boolean getPriority() {
        return this.priority;
    }
    
    public void setPriority(Boolean priority) {
        this.priority = priority;
    }
    public Date getScheduleddatetime() {
        return this.scheduleddatetime;
    }
    
    public void setScheduleddatetime(Date scheduleddatetime) {
        this.scheduleddatetime = scheduleddatetime;
    }
    public Date getActualsendingdatetime() {
        return this.actualsendingdatetime;
    }
    
    public void setActualsendingdatetime(Date actualsendingdatetime) {
        this.actualsendingdatetime = actualsendingdatetime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getResenddate1() {
        return this.resenddate1;
    }
    
    public void setResenddate1(Date resenddate1) {
        this.resenddate1 = resenddate1;
    }
    public String getResendstatus() {
        return this.resendstatus;
    }
    
    public void setResendstatus(String resendstatus) {
        this.resendstatus = resendstatus;
    }
    public Date getResenddate2() {
        return this.resenddate2;
    }
    
    public void setResenddate2(Date resenddate2) {
        this.resenddate2 = resenddate2;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
}


