package com.jilit.irp.persistence.dto;
// Generated 17 Sep, 2016 3:22:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Sdl_schedulemailattachementId generated by hbm2java
 */
public class Sdl_ScheduleMailAttachementId  implements java.io.Serializable {


     private String schedularid;
     private String taskid;
     private String senderemailid;
     private short attachementslno;

    public Sdl_ScheduleMailAttachementId() {
    }

    public Sdl_ScheduleMailAttachementId(String schedularid, String taskid, String senderemailid, short attachementslno) {
       this.schedularid = schedularid;
       this.taskid = taskid;
       this.senderemailid = senderemailid;
       this.attachementslno = attachementslno;
    }
   
    public String getSchedularid() {
        return this.schedularid;
    }
    
    public void setSchedularid(String schedularid) {
        this.schedularid = schedularid;
    }
    public String getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(String taskid) {
        this.taskid = taskid;
    }
    public String getSenderemailid() {
        return this.senderemailid;
    }
    
    public void setSenderemailid(String senderemailid) {
        this.senderemailid = senderemailid;
    }
    public short getAttachementslno() {
        return this.attachementslno;
    }
    
    public void setAttachementslno(short attachementslno) {
        this.attachementslno = attachementslno;
    }

}


