package com.jilit.irp.persistence.dto;
// Generated Jul 17, 2014 2:37:41 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentadmissioncategoryId generated by hbm2java
 */
public class StudentAdmissionCategoryId  implements java.io.Serializable {


     private String instituteid;
     private String admittedcategoryid;

    public StudentAdmissionCategoryId() {
    }

    public StudentAdmissionCategoryId(String instituteid, String admittedcategoryid) {
       this.instituteid = instituteid;
       this.admittedcategoryid = admittedcategoryid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getAdmittedcategoryid() {
        return this.admittedcategoryid;
    }
    
    public void setAdmittedcategoryid(String admittedcategoryid) {
        this.admittedcategoryid = admittedcategoryid;
    }


  }


