package com.jilit.irp.persistence.dto;
// Generated Nov 24, 2014 11:51:19 AM by Hibernate Tools 3.2.1.GA



/**
 * Studentallowforexam generated by hbm2java
 */
public class StudentAllowForExam  implements java.io.Serializable {


     private StudentAllowForExamId id;
     private SubjectMaster subjectmaster;
     private StudentMaster studentmaster;
     private RegistrationMaster registrationmaster;
     private String enrollmentno;
     private String name;
     private String programid;
     private String branchid;
     private Byte stynumber;
     private String sectionid;
     private String subsectionid;
     private String subjectcode;
     private String subjectdesc;
     private String attendanceinpercentage;
     private String allowforexam;
     private String remarks;
     private String debarremarks;


    public StudentAllowForExam() {
    }

    public StudentAllowForExam(StudentAllowForExam dto){
       this.allowforexam=dto.getAllowforexam();
       this.attendanceinpercentage=dto.getAttendanceinpercentage();
       this.enrollmentno=dto.getEnrollmentno();
       this.name=dto.getName();
       this.programid=dto.getProgramid();
       this.branchid=dto.getBranchid();
       this.stynumber=dto.getStynumber();
       this.sectionid=dto.getSectionid();
       this.subsectionid=dto.getSubsectionid();
       this.subjectcode=dto.getSubjectcode();
       this.remarks=dto.getRemarks();
       this.subjectdesc=dto.getSubjectdesc();
       this.id=dto.getId();
       this.debarremarks = dto.getDebarremarks();
    }


    public StudentAllowForExam(StudentAllowForExamId id, SubjectMaster subjectmaster, StudentMaster studentmaster, RegistrationMaster registrationmaster, String enrollmentno, String name) {
        this.id = id;
        this.subjectmaster = subjectmaster;
        this.studentmaster = studentmaster;
        this.registrationmaster = registrationmaster;
        this.enrollmentno = enrollmentno;
        this.name = name;
    }

    public StudentAllowForExam(StudentAllowForExamId id, SubjectMaster subjectmaster, StudentMaster studentmaster, RegistrationMaster registrationmaster, String enrollmentno, String name, String programid, String branchid, Byte stynumber, String sectionid, String subsectionid, String subjectcode, String subjectdesc, String attendanceinpercentage, String allowforexam, String remarks) {
        this.id = id;
        this.subjectmaster = subjectmaster;
        this.studentmaster = studentmaster;
        this.registrationmaster = registrationmaster;
        this.enrollmentno = enrollmentno;
        this.name = name;
        this.programid = programid;
        this.branchid = branchid;
        this.stynumber = stynumber;
        this.sectionid = sectionid;
        this.subsectionid = subsectionid;
        this.subjectcode = subjectcode;
        this.subjectdesc = subjectdesc;
        this.attendanceinpercentage = attendanceinpercentage;
        this.allowforexam = allowforexam;
        this.remarks = remarks;
    }


    public StudentAllowForExamId getId() {
        return this.id;
    }

    public String getIdStr() {
        return id.getInstituteid()+":"+id.getRegistrationid()+":"+id.getStudentid()+":"+id.getSubjectid();
    }

    public void setId(StudentAllowForExamId id) {
        this.id = id;
    }

    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    public String getEnrollmentno() {
        return this.enrollmentno;
    }

    public void setEnrollmentno(String enrollmentno) {
        this.enrollmentno = enrollmentno;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getProgramid() {
        return this.programid;
    }

    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getBranchid() {
        return this.branchid;
    }

    public void setBranchid(String branchid) {
        this.branchid = branchid;
    }
    public Byte getStynumber() {
        return this.stynumber;
    }

    public void setStynumber(Byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getSectionid() {
        return this.sectionid;
    }

    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }
    public String getSubsectionid() {
        return this.subsectionid;
    }

    public void setSubsectionid(String subsectionid) {
        this.subsectionid = subsectionid;
    }
    public String getSubjectcode() {
        return this.subjectcode;
    }

    public void setSubjectcode(String subjectcode) {
        this.subjectcode = subjectcode;
    }
    public String getSubjectdesc() {
        return this.subjectdesc;
    }

    public void setSubjectdesc(String subjectdesc) {
        this.subjectdesc = subjectdesc;
    }
    public String getAttendanceinpercentage() {
        return this.attendanceinpercentage;
    }

    public void setAttendanceinpercentage(String attendanceinpercentage) {
        this.attendanceinpercentage = attendanceinpercentage;
    }
    public String getAllowforexam() {
        return this.allowforexam;
    }

    public void setAllowforexam(String allowforexam) {
        this.allowforexam = allowforexam;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDebarremarks() {
        return debarremarks;
    }

    public void setDebarremarks(String debarremarks) {
        this.debarremarks = debarremarks;
    }
}


