package com.jilit.irp.persistence.dto;
// Generated Dec 24, 2015 12:04:24 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Studentnotoffersubject generated by hbm2java
 */
public class StudentNotOfferSubject  implements java.io.Serializable {


     private StudentNotOfferSubjectId id;
     private Academicyear academicyear;
     private ProgramMaster programmaster;
     private SubjectMaster subjectmaster;
     private SectionMaster sectionmaster;
     private RegistrationMaster registrationmaster;
     private StudentMaster studentmaster;
     private byte stynumber;
     private String acadyear;
     private String programid;
     private String sectionid;
     private String registered;
     private Date reregistrationdate;
     private String entryby;
     private Date entrydate;
     private String remarks;
     private String deactive;
     private String basketid;
     private String reregistrationid;

    public String getReregistrationid() {
        return reregistrationid;
    }

    public void setReregistrationid(String reregistrationid) {
        this.reregistrationid = reregistrationid;
    }

    public StudentNotOfferSubject() {
    }

	
    public StudentNotOfferSubject(StudentNotOfferSubjectId id, Academicyear academicyear, ProgramMaster programmaster, SubjectMaster subjectmaster, SectionMaster sectionmaster, RegistrationMaster registrationmaster, StudentMaster studentmaster, byte stynumber, String basketid) {
        this.id = id;
        this.academicyear = academicyear;
        this.programmaster = programmaster;
        this.subjectmaster = subjectmaster;
        this.sectionmaster = sectionmaster;
        this.registrationmaster = registrationmaster;
        this.studentmaster = studentmaster;
        this.stynumber = stynumber;
        this.basketid = basketid;
    }
    public StudentNotOfferSubject(StudentNotOfferSubjectId id, Academicyear academicyear, ProgramMaster programmaster, SubjectMaster subjectmaster, SectionMaster sectionmaster, RegistrationMaster registrationmaster, StudentMaster studentmaster,byte stynumber, String basketid, String registered, Date reregistrationdate, String entryby, Date entrydate, String remarks, String deactive) {
       this.id = id;
       this.academicyear = academicyear;
       this.programmaster = programmaster;
       this.subjectmaster = subjectmaster;
       this.sectionmaster = sectionmaster;
       this.registrationmaster = registrationmaster;
       this.studentmaster = studentmaster;
       this.stynumber = stynumber;
       this.basketid = basketid;
       this.registered = registered;
       this.reregistrationdate = reregistrationdate;
       this.entryby = entryby;
       this.entrydate = entrydate;
       this.remarks = remarks;
       this.deactive = deactive;
    }

     public StudentNotOfferSubject(StudentNotOfferSubjectId id, Academicyear academicyear, ProgramMaster programmaster, SubjectMaster subjectmaster, String acadyear, SectionMaster sectionmaster, RegistrationMaster registrationmaster, StudentMaster studentmaster,byte stynumber, String basketid, String registered, Date reregistrationdate, String entryby, Date entrydate, String remarks, String deactive) {
       this.id = id;
       this.academicyear = academicyear;
       this.programmaster = programmaster;
       this.subjectmaster = subjectmaster;
       this.acadyear = acadyear;
       this.sectionmaster = sectionmaster;
       this.registrationmaster = registrationmaster;
       this.studentmaster = studentmaster;
       this.stynumber = stynumber;
       this.basketid = basketid;
       this.registered = registered;
       this.reregistrationdate = reregistrationdate;
       this.entryby = entryby;
       this.entrydate = entrydate;
       this.remarks = remarks;
       this.deactive = deactive;
    }

   
    public StudentNotOfferSubjectId getId() {
        return this.id;
    }
    
    public void setId(StudentNotOfferSubjectId id) {
        this.id = id;
    }

     public String getSectionid() {
        return sectionid;
    }

    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }

    public String getProgramid() {
        return programid;
    }

    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }

      public String getAcadyear() {
        return acadyear;
    }

    public void setAcadyear(String acadyear) {
        this.acadyear = acadyear;
    }
    
    public ProgramMaster getProgrammaster() {
        return this.programmaster;
    }
    
    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }
    public SubjectMaster getSubjectmaster() {
        return this.subjectmaster;
    }
    
    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }
    public SectionMaster getSectionmaster() {
        return this.sectionmaster;
    }
    
    public void setSectionmaster(SectionMaster sectionmaster) {
        this.sectionmaster = sectionmaster;
    }
    public RegistrationMaster registrationmaster() {
        return this.registrationmaster;
    }
    
    public StudentMaster getStudentmaster() {
        return this.studentmaster;
    }
    
    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }
    public byte getStynumber() {
        return this.stynumber;
    }
    
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getBasketid() {
        return this.basketid;
    }
    
    public void setBasketid(String basketid) {
        this.basketid = basketid;
    }
    public String getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(String registered) {
        this.registered = registered;
    }
    public Date getReregistrationdate() {
        return this.reregistrationdate;
    }
    
    public void setReregistrationdate(Date reregistrationdate) {
        this.reregistrationdate = reregistrationdate;
    }
    public String getEntryby() {
        return this.entryby;
    }
    
    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }




}


