package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * StudentIntractionDetailId generated by hbm2java
 */
public class StudentIntractionDetailId  implements java.io.Serializable {


     private String instituteid;
     private String refno;

    public StudentIntractionDetailId() {
    }

    public StudentIntractionDetailId(String instituteid, String refno) {
       this.instituteid = instituteid;
       this.refno = refno;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRefno() {
        return this.refno;
    }
    
    public void setRefno(String refno) {
        this.refno = refno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentIntractionDetailId) ) return false;
		 StudentIntractionDetailId castOther = ( StudentIntractionDetailId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRefno()==castOther.getRefno()) || ( this.getRefno()!=null && castOther.getRefno()!=null && this.getRefno().equals(castOther.getRefno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRefno() == null ? 0 : this.getRefno().hashCode() );
         return result;
   }   


}


