package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentSubjectChoiceMaster generated by hbm2java
 */
public class StudentSubjectChoiceMaster  implements java.io.Serializable {


     private StudentSubjectChoiceMasterId id;
     private StudentRegistration studentregistration;
     //private SubjectMaster subjectmaster;
     private SubjectMaster subjectmasterByStudentsubjectmasterFk4;
     private SubjectMaster subjectmasterByStudentsubjectchoicemasterFk3;
     private StyType stytype;
     private String stytypeid;
     private String basketid;
     private Byte choice;
    // private String subsectionid;
     private String subjectrunning;
     private String customfinalized;
     private String deactive;
     private String equivalentsubjectid;
     private String openelective;
     private String supplimentryregistered;
     private String supplimentryregisteredby;
     private Date supplimentryregistereddate;
     private String part;
     private String gradeid;
     private String reregtype;
     private BigDecimal regfeeamount;
     private String auditsubject;
    private String subjecttype;
    private String subjecttypeid;
     private Set<StudentSubjectChoiceDetail> studentsubjectchoicedetails = new HashSet<StudentSubjectChoiceDetail>(0);



    public StudentSubjectChoiceMaster() {
    }

    public StudentSubjectChoiceMaster(StudentSubjectChoiceMaster dto) {
        this.id=dto.getId();
        this.stytype=dto.getStytype();
        this.choice=dto.getChoice();
        //this.subsectionid=dto.getSubsectionid();
        this.subjectrunning=dto.getSubjectrunning();
        this.customfinalized=dto.getCustomfinalized();
        this.deactive=dto.getDeactive();
        this.equivalentsubjectid=dto.getEquivalentsubjectid();
        this.openelective=dto.getOpenelective();
        this.supplimentryregistered=dto.getSupplimentryregistered();
        this.supplimentryregisteredby=dto.getSupplimentryregisteredby();
        this.supplimentryregistereddate=dto.getSupplimentryregistereddate();
    }


    public StudentSubjectChoiceMaster(StudentSubjectChoiceMasterId id, StudentRegistration studentregistration, StyType stytype) {
        this.id = id;
        this.studentregistration = studentregistration;
        this.stytype = stytype;
    }
    public StudentSubjectChoiceMaster(StudentSubjectChoiceMasterId id, StudentRegistration studentregistration, StyType stytype, Byte choice, String subsectionid, String subjectrunning, String customfinalized, String deactive, Set studentsubjectchoicedetails) {
       this.id = id;
       this.studentregistration = studentregistration;
       this.stytype = stytype;
       this.choice = choice;
//       this.subsectionid = subsectionid;
       this.subjectrunning = subjectrunning;
       this.customfinalized = customfinalized;
       this.deactive = deactive;
       this.studentsubjectchoicedetails = studentsubjectchoicedetails;
    }

    public StudentSubjectChoiceMasterId getId() {
        return this.id;
    }

    public void setId(StudentSubjectChoiceMasterId id) {
        this.id = id;
    }
    public StudentRegistration getStudentregistration() {
        return this.studentregistration;
    }

    public void setStudentregistration(StudentRegistration studentregistration) {
        this.studentregistration = studentregistration;
    }
    public StyType getStytype() {
        return this.stytype;
    }

    public void setStytype(StyType stytype) {
        this.stytype = stytype;
    }
    public Byte getChoice() {
        return this.choice;
    }

    public void setChoice(Byte choice) {
        this.choice = choice;
    }
//    public String getSubsectionid() {
//        return this.subsectionid;
//    }
//
//    public void setSubsectionid(String subsectionid) {
//        this.subsectionid = subsectionid;
//    }
    public String getSubjectrunning() {
        return this.subjectrunning;
    }

    public void setSubjectrunning(String subjectrunning) {
        this.subjectrunning = subjectrunning;
    }
    public String getCustomfinalized() {
        return this.customfinalized;
    }

    public void setCustomfinalized(String customfinalized) {
        this.customfinalized = customfinalized;
    }
    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }


    public String getStytypeid() {
        return stytypeid;
    }

    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }


    public String getBasketid() {
        return basketid;
    }

    public void setBasketid(String basketid) {
        this.basketid = basketid;
    }

    public SubjectMaster getSubjectmasterByStudentsubjectchoicemasterFk3() {
        return subjectmasterByStudentsubjectchoicemasterFk3;
    }

    public void setSubjectmasterByStudentsubjectchoicemasterFk3(SubjectMaster subjectmasterByStudentsubjectchoicemasterFk3) {
        this.subjectmasterByStudentsubjectchoicemasterFk3 = subjectmasterByStudentsubjectchoicemasterFk3;
    }

    public SubjectMaster getSubjectmasterByStudentsubjectmasterFk4() {
        return subjectmasterByStudentsubjectmasterFk4;
    }

    public void setSubjectmasterByStudentsubjectmasterFk4(SubjectMaster subjectmasterByStudentsubjectmasterFk4) {
        this.subjectmasterByStudentsubjectmasterFk4 = subjectmasterByStudentsubjectmasterFk4;
    }

    public String getEquivalentsubjectid() {
        return equivalentsubjectid;
    }

    public void setEquivalentsubjectid(String equivalentsubjectid) {
        this.equivalentsubjectid = equivalentsubjectid;
    }

    public Set<StudentSubjectChoiceDetail> getStudentsubjectchoicedetails() {
        return studentsubjectchoicedetails;
    }

    public void setStudentsubjectchoicedetails(Set<StudentSubjectChoiceDetail> studentsubjectchoicedetails) {
        this.studentsubjectchoicedetails = studentsubjectchoicedetails;
    }

    public String getOpenelective() {
        return openelective;
    }

    public void setOpenelective(String openelective) {
        this.openelective = openelective;
    }
    public String getIdStr() {
        return id.getInstituteid()+"::"+id.getRegistrationid()+"::"+id.getSubjectid();
    }
//     public String getIdStr() {
//        return id.getInstituteid()+"::"+id.getRegistrationid()+"::"+id.getStudentid()+"::"+id.getSubjectid();
//    }


    public String getSupplimentryregistered() {
        return supplimentryregistered;
    }

    public void setSupplimentryregistered(String supplimentryregistered) {
        this.supplimentryregistered = supplimentryregistered;
    }

    public String getSupplimentryregisteredby() {
        return supplimentryregisteredby;
    }

    public void setSupplimentryregisteredby(String supplimentryregisteredby) {
        this.supplimentryregisteredby = supplimentryregisteredby;
    }

    public Date getSupplimentryregistereddate() {
        return supplimentryregistereddate;
    }

    public void setSupplimentryregistereddate(Date supplimentryregistereddate) {
        this.supplimentryregistereddate = supplimentryregistereddate;
    }

    public String getGradeid() {
        return gradeid;
    }

    public void setGradeid(String gradeid) {
        this.gradeid = gradeid;
    }

    public String getPart() {
        return part;
    }

    public void setPart(String part) {
        this.part = part;
    }

    public String getReregtype() {
        return reregtype;
    }

    public void setReregtype(String reregtype) {
        this.reregtype = reregtype;
    }

    public BigDecimal getRegfeeamount() {
        return regfeeamount;
    }

    public void setRegfeeamount(BigDecimal regfeeamount) {
        this.regfeeamount = regfeeamount;
    }

    public String getAuditsubject() {
        return auditsubject;
    }

    public void setAuditsubject(String auditsubject) {
        this.auditsubject = auditsubject;
    }
  
    public String getSubjecttype() {
        return subjecttype;
    }

    public void setSubjecttype(String subjecttype) {
        this.subjecttype = subjecttype;
    }

    public String getSubjecttypeid() {
        return subjecttypeid;
    }

    public void setSubjecttypeid(String subjecttypeid) {
        this.subjecttypeid = subjecttypeid;
    }

}
