package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentsubjectchoicedetailId generated by hbm2java
 */
public class StudentSubjectChoiceDetailId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String studentid;
     private byte stynumber;
     private String subjectid;
     private String subjectcomponentid;

    public StudentSubjectChoiceDetailId() {
    }

    public StudentSubjectChoiceDetailId(String instituteid, String registrationid, String studentid,byte stynumber, String subjectid, String subjectcomponentid) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.studentid = studentid;
       this.stynumber = stynumber;
       this.subjectid = subjectid;
       this.subjectcomponentid = subjectcomponentid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public byte getStynumber() {
        return this.stynumber;
    }
    
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }
    public String getSubjectcomponentid() {
        return this.subjectcomponentid;
    }
    
    public void setSubjectcomponentid(String subjectcomponentid) {
        this.subjectcomponentid = subjectcomponentid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentSubjectChoiceDetailId) ) return false;
		 StudentSubjectChoiceDetailId castOther = ( StudentSubjectChoiceDetailId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && (this.getStynumber()==castOther.getStynumber())
 && ( (this.getSubjectid()==castOther.getSubjectid()) || ( this.getSubjectid()!=null && castOther.getSubjectid()!=null && this.getSubjectid().equals(castOther.getSubjectid()) ) )
 && ( (this.getSubjectcomponentid()==castOther.getSubjectcomponentid()) || ( this.getSubjectcomponentid()!=null && castOther.getSubjectcomponentid()!=null && this.getSubjectcomponentid().equals(castOther.getSubjectcomponentid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + this.getStynumber();
         result = 37 * result + ( getSubjectid() == null ? 0 : this.getSubjectid().hashCode() );
         result = 37 * result + ( getSubjectcomponentid() == null ? 0 : this.getSubjectcomponentid().hashCode() );
         return result;
   }

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

   
}


