package com.jilit.irp.persistence.dto;
// Generated Jul 17, 2014 2:37:41 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * Studentadmissionsubcategory generated by hbm2java
 */
public class StudentAdmissionSubCategory  implements java.io.Serializable {


     private StudentAdmissionSubCategoryId id;  
     private StudentAdmissionCategory studentadmissioncategory;
     private String admittedsubcategorycode;
     private String admittedsubcategorydesc;
     private String deactive;
     private Short seqid;
     private Set<StudentMaster> studentmasters = new HashSet<StudentMaster>(0);


    public StudentAdmissionSubCategory() {
    }
    
    public StudentAdmissionSubCategory(StudentAdmissionSubCategory dto) {
       this.id= dto.getId();
     //  this.studentadmissioncategory = dto.getStudentadmissioncategory();
       this.admittedsubcategorycode = dto.getAdmittedsubcategorycode();
       this.admittedsubcategorydesc = dto.getAdmittedsubcategorydesc();
       this.deactive = dto.getDeactive();
       this.seqid = dto.getSeqid();
    }
	
    public StudentAdmissionSubCategory(StudentAdmissionSubCategoryId id, StudentAdmissionCategory studentadmissioncategory) {
        this.id = id;
        this.studentadmissioncategory = studentadmissioncategory;
    }
    
    public StudentAdmissionSubCategory(StudentAdmissionSubCategoryId id, StudentAdmissionCategory studentadmissioncategory, String admittedsubcategorycode, String admittedsubcategorydesc, String deactive, Short seqid) {
       this.id = id;
       this.studentadmissioncategory = studentadmissioncategory;
       this.admittedsubcategorycode = admittedsubcategorycode;
       this.admittedsubcategorydesc = admittedsubcategorydesc;
       this.deactive = deactive;
       this.seqid = seqid;
    }

    public String getAdmittedsubcategorycode() {
        return admittedsubcategorycode;
    }

    public void setAdmittedsubcategorycode(String admittedsubcategorycode) {
        this.admittedsubcategorycode = admittedsubcategorycode;
    }

    public String getAdmittedsubcategorydesc() {
        return admittedsubcategorydesc;
    }

    public void setAdmittedsubcategorydesc(String admittedsubcategorydesc) {
        this.admittedsubcategorydesc = admittedsubcategorydesc;
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public StudentAdmissionSubCategoryId getId() {
        return id;
    }

    public void setId(StudentAdmissionSubCategoryId id) {
        this.id = id;
    }

    public Short getSeqid() {
        return seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }

    public StudentAdmissionCategory getStudentadmissioncategory() {
        return studentadmissioncategory;
    }

    public void setStudentadmissioncategory(StudentAdmissionCategory studentadmissioncategory) {
        this.studentadmissioncategory = studentadmissioncategory;
    }

    public Set getStudentmasters() {
        return studentmasters;
    }

    public void setStudentmasters(Set studentmasters) {
        this.studentmasters = studentmasters;
    }

    public String getIdString() {
        return this.id.getInstituteid() + ":" + this.id.getAdmittedcategoryid() + ":" + this.id.getAdmittedsubcategoryid();
    }
    
}


