package com.jilit.irp.persistence.dto;
// Generated 1 Oct, 2011 6:05:03 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentcertificateslnoId generated by hbm2java
 */
public class StudentCertificateSlnoId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String academicyear;
     private String programid;
     private String branchid;
     private byte stynumber;
     private String stytypeid;
     private String studentid;
     private String certificateid;

    public StudentCertificateSlnoId() {
    }

    public StudentCertificateSlnoId(String instituteid, String registrationid, String academicyear, String programid, String branchid, byte stynumber, String stytypeid, String studentid, String certificateid) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.academicyear = academicyear;
       this.programid = programid;
       this.branchid = branchid;
       this.stynumber = stynumber;
       this.stytypeid = stytypeid;
       this.studentid = studentid;
       this.certificateid = certificateid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
     
    public byte getStynumber() {
        return this.stynumber;
    }
    
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getStytypeid() {
        return this.stytypeid;
    }
    
    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }
    public String getCertificateid() {
        return this.certificateid;
    }
    
    public void setCertificateid(String certificateid) {
        this.certificateid = certificateid;
    }

    public String getBranchid() {
        return branchid;
    }

    public void setBranchid(String branchid) {
        this.branchid = branchid;
    }
    

  

}


