package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentIntractionDetail generated by hbm2java
 */
public class StudentIntractionDetail  implements java.io.Serializable {


     private StudentIntractionDetailId id;
     private StudentMaster studentmaster;
     private Date intractiondate;
     private String intractionwith;
     private String staffid;
     private String loginid;
     private String relatedto;
     private String studentcomment;
     private String intractioncomment;
     private String remarks;
     private String deactive;
     private Set<StudentIntractionRefDetail> studentintractionrefdetails = new HashSet<StudentIntractionRefDetail>(0);

    public StudentIntractionDetail() {
    }

	
    public StudentIntractionDetail(StudentIntractionDetailId id, StudentMaster studentmaster, Date intractiondate, String intractionwith, String staffid) {
        this.id = id;
        this.studentmaster = studentmaster;
        this.intractiondate = intractiondate;
        this.intractionwith = intractionwith;
        this.staffid = staffid;
    }
    public StudentIntractionDetail(StudentIntractionDetailId id, StudentMaster studentmaster, Date intractiondate, String intractionwith, String staffid, String loginid, String relatedto, String studentcomment, String intractioncomment, String remarks, String deactive, Set<StudentIntractionRefDetail> studentintractionrefdetails) {
       this.id = id;
       this.studentmaster = studentmaster;
       this.intractiondate = intractiondate;
       this.intractionwith = intractionwith;
       this.staffid = staffid;
       this.loginid = loginid;
       this.relatedto = relatedto;
       this.studentcomment = studentcomment;
       this.intractioncomment = intractioncomment;
       this.remarks = remarks;
       this.deactive = deactive;
       this.studentintractionrefdetails = studentintractionrefdetails;
    }
   
    public StudentIntractionDetailId getId() {
        return this.id;
    }
    
    public void setId(StudentIntractionDetailId id) {
        this.id = id;
    }
  
    public Date getIntractiondate() {
        return this.intractiondate;
    }
    
    public void setIntractiondate(Date intractiondate) {
        this.intractiondate = intractiondate;
    }
    public String getIntractionwith() {
        return this.intractionwith;
    }
    
    public void setIntractionwith(String intractionwith) {
        this.intractionwith = intractionwith;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }
    public String getRelatedto() {
        return this.relatedto;
    }
    
    public void setRelatedto(String relatedto) {
        this.relatedto = relatedto;
    }
    public String getStudentcomment() {
        return this.studentcomment;
    }
    
    public void setStudentcomment(String studentcomment) {
        this.studentcomment = studentcomment;
    }
    public String getIntractioncomment() {
        return this.intractioncomment;
    }
    
    public void setIntractioncomment(String intractioncomment) {
        this.intractioncomment = intractioncomment;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public Set<StudentIntractionRefDetail> getStudentintractionrefdetails() {
        return studentintractionrefdetails;
    }

    public void setStudentintractionrefdetails(Set<StudentIntractionRefDetail> studentintractionrefdetails) {
        this.studentintractionrefdetails = studentintractionrefdetails;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }
   



}


