package com.jilit.irp.persistence.dto;
// Generated Feb 14, 2015 2:20:13 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentattendancesummaryId generated by hbm2java
 */
public class StudentattendancesummaryId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String studentid;
     private String subjectid;
     private String subjectcomponentid;
     private byte stynumber;
     private String stytypeid;

    public StudentattendancesummaryId() {
    }

    public StudentattendancesummaryId(String instituteid, String registrationid, String studentid, String subjectid, String subjectcomponentid, byte stynumber, String stytypeid) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.studentid = studentid;
       this.subjectid = subjectid;
       this.subjectcomponentid = subjectcomponentid;
       this.stynumber = stynumber;
       this.stytypeid = stytypeid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }
    public String getSubjectcomponentid() {
        return this.subjectcomponentid;
    }
    
    public void setSubjectcomponentid(String subjectcomponentid) {
        this.subjectcomponentid = subjectcomponentid;
    }
    public byte getStynumber() {
        return this.stynumber;
    }
    
    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }
    public String getStytypeid() {
        return this.stytypeid;
    }
    
    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentattendancesummaryId) ) return false;
		 StudentattendancesummaryId castOther = ( StudentattendancesummaryId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getRegistrationid()==castOther.getRegistrationid()) || ( this.getRegistrationid()!=null && castOther.getRegistrationid()!=null && this.getRegistrationid().equals(castOther.getRegistrationid()) ) )
 && ( (this.getStudentid()==castOther.getStudentid()) || ( this.getStudentid()!=null && castOther.getStudentid()!=null && this.getStudentid().equals(castOther.getStudentid()) ) )
 && ( (this.getSubjectid()==castOther.getSubjectid()) || ( this.getSubjectid()!=null && castOther.getSubjectid()!=null && this.getSubjectid().equals(castOther.getSubjectid()) ) )
 && ( (this.getSubjectcomponentid()==castOther.getSubjectcomponentid()) || ( this.getSubjectcomponentid()!=null && castOther.getSubjectcomponentid()!=null && this.getSubjectcomponentid().equals(castOther.getSubjectcomponentid()) ) )
 && (this.getStynumber()==castOther.getStynumber())
 && ( (this.getStytypeid()==castOther.getStytypeid()) || ( this.getStytypeid()!=null && castOther.getStytypeid()!=null && this.getStytypeid().equals(castOther.getStytypeid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getRegistrationid() == null ? 0 : this.getRegistrationid().hashCode() );
         result = 37 * result + ( getStudentid() == null ? 0 : this.getStudentid().hashCode() );
         result = 37 * result + ( getSubjectid() == null ? 0 : this.getSubjectid().hashCode() );
         result = 37 * result + ( getSubjectcomponentid() == null ? 0 : this.getSubjectcomponentid().hashCode() );
         result = 37 * result + this.getStynumber();
         result = 37 * result + ( getStytypeid() == null ? 0 : this.getStytypeid().hashCode() );
         return result;
   }   


}


