package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * StudentIntractionRefDetail generated by hbm2java
 */
public class StudentIntractionRefDetail  implements java.io.Serializable {


     private StudentIntractionRefDetailId id;
     private StudentIntractionDetail studentintractiondetail;

    public StudentIntractionRefDetail() {
    }

    public StudentIntractionRefDetail(StudentIntractionRefDetailId id, StudentIntractionDetail studentintractiondetail) {
       this.id = id;
       this.studentintractiondetail = studentintractiondetail;
    }
   
    public StudentIntractionRefDetailId getId() {
        return this.id;
    }
    
    public void setId(StudentIntractionRefDetailId id) {
        this.id = id;
    }

    public StudentIntractionDetail getStudentintractiondetail() {
        return studentintractiondetail;
    }

    public void setStudentintractiondetail(StudentIntractionDetail studentintractiondetail) {
        this.studentintractiondetail = studentintractiondetail;
    }
  




}


