package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentRegistration generated by hbm2java
 */
public class StudentRegistration implements java.io.Serializable {

    private StudentRegistrationId id;
    private RegistrationMaster registrationmaster;
    private HostelType hosteltype;
    private StudentMaster studentmaster;
    private StyType stytype;
    private StudentQuota studentquota;
    private String stytypeid;
    private String quotaid;
    private byte stynumber;
    private String regallow;
    private String regallowuser;
    private Date regallowdate;
    private String hostelallow;
    private String hostelallowuser;
    private Date hostelallowdate;
    private String feespaid;
    private String feespaiduser;
    private Date feespaiddate;
    private String subjecttagged;
    private String regconfirmation;
    private String regconfirmationuser;
    private Date regconfirmatiodate;
    private String hostelconfirmation;
    private String hostelconfirmationuser;
    private Date hostelconfirmationdate;
    private String fullpaid;
    private String fullpaiduser;
    private Date fullpaiddate;
    private String fullpaidremarks;
    private Date preventfrom;
    private Date preventto;
    private String preventfreezed;
    private String prfreezedby;
    private Date prfreezeddate;
    private String sstpopulated;
    private String remarks;
    private String prsubjstaffpreffreezed;
    private String prsubjstaffprefby;
    private Date prsubjstaffprefdate;
    private String institutecopysubmitted;
    private String copysubmitteduser;
    private Date copysubmitiondate;
    private String instelectivefreezed;
    private Date instelectivefreezingdate;
    private String instelectivefreezedby;
    private String academicregistrationflag;
    private Date academicregistrationdate;
    private String academicregistrationby;
    private String attendancedone;
    private Date attendancedate;
    private String attendanceby;
    private String feepaymentmode;
    private String hosteltypeid;
    private String supplimentryfeepaid;
    private String supplimentoryfeepaidby;
    private Date supplimentoryfeepaiddate;
    private Date elegibilityfeedate;
    private String elegibilityfeeapplicable;
    private String allowforfeepay;
    private String docverification;
    private String allowforsubjectchoice;
    private String transportallow;
    private Set<StudentRegistration_info> studentregistration_infos = new HashSet<StudentRegistration_info>(0);
    private Set<PRStudentSubjectChoiceCount> prstudentsubjectchoicecounts = new HashSet<PRStudentSubjectChoiceCount>(0);
    private Set<StudentSubjectChoiceMaster> studentsubjectchoicemasters = new HashSet<StudentSubjectChoiceMaster>(0);
    private Set<StudentCertificateSlno> studentcertificateslnos = new HashSet<StudentCertificateSlno>(0);
    private Set<NotEligibleForRegistration> noteligibleforregistrations = new HashSet<NotEligibleForRegistration>(0);
    private Set<StudentYearBackDetail> studentyearbackdetails = new HashSet<StudentYearBackDetail>(0);
    private Set<RegCoordinatorTagging> regcoordinatortaggings = new HashSet<RegCoordinatorTagging>(0);

    public StudentRegistration() {
    }

    public StudentRegistration(StudentRegistration dto) {
        this.id = dto.getId();

        this.stytypeid = dto.getStytypeid();
        this.stynumber = dto.getStynumber();
        this.regallow = dto.getRegallow();
        this.regallowuser = dto.getRegallowuser();
        this.regallowdate = dto.getRegallowdate();
        this.hostelallow = dto.getHostelallow();
        this.hostelallowuser = dto.getHostelallowuser();
        this.hostelallowdate = dto.getHostelallowdate();
        this.feespaid = dto.getFeespaid();
        this.feespaiduser = dto.getFeespaiduser();
        this.feespaiddate = dto.getFeespaiddate();
        this.subjecttagged = dto.getSubjecttagged();
        this.regconfirmation = dto.getRegconfirmation();
        this.regconfirmationuser = dto.getRegconfirmationuser();
        this.regconfirmatiodate = dto.getRegconfirmatiodate();
        this.hostelconfirmation = dto.getHostelconfirmation();
        this.hostelconfirmationuser = dto.getHostelconfirmationuser();
        this.hostelconfirmationdate = dto.getHostelconfirmationdate();
        this.fullpaid = dto.getFullpaid();
        this.fullpaiduser = dto.getFullpaiduser();
        this.fullpaiddate = dto.getFullpaiddate();
        this.fullpaidremarks = dto.getFullpaidremarks();
        this.preventfrom = dto.getPreventfrom();
        this.preventto = dto.getPreventto();
        this.preventfreezed = dto.getPreventfreezed();
        this.prfreezedby = dto.getPrfreezedby();
        this.prfreezeddate = dto.getPrfreezeddate();
        this.sstpopulated = dto.getSstpopulated();
        this.remarks = dto.getRemarks();
        this.prsubjstaffpreffreezed = dto.getPrsubjstaffpreffreezed();
        this.prsubjstaffprefby = dto.getPrsubjstaffprefby();
        this.prsubjstaffprefdate = dto.getPrsubjstaffprefdate();
        this.institutecopysubmitted = dto.getInstitutecopysubmitted();
        this.instelectivefreezed = dto.getInstelectivefreezed();
        this.instelectivefreezingdate = dto.getInstelectivefreezingdate();
        this.instelectivefreezedby = dto.getInstelectivefreezedby();
        this.academicregistrationby = dto.getAcademicregistrationby();
        this.academicregistrationdate = dto.getAttendancedate();
        this.academicregistrationflag = dto.getAcademicregistrationflag();
        this.attendanceby = dto.getAttendanceby();
        this.attendancedate = dto.getAttendancedate();
        this.attendancedone = dto.getAttendancedone();
        this.quotaid = dto.getQuotaid();
        this.supplimentryfeepaid = dto.getSupplimentryfeepaid();
        this.supplimentoryfeepaidby = dto.getSupplimentoryfeepaidby();
        this.supplimentoryfeepaiddate = dto.getSupplimentoryfeepaiddate();
        //this.elegibilityfeedate=dto.getElegibilityfeedate();
        //this.elegibilityfeeapplicable=dto.getElegibilityfeeapplicable();
    }

    public StudentRegistration(StudentRegistrationId id, RegistrationMaster registrationmaster, StudentMaster studentmaster, StyType stytype, byte stynumber) {
        this.id = id;
        this.registrationmaster = registrationmaster;
        this.studentmaster = studentmaster;
        this.stytype = stytype;
        this.stynumber = stynumber;
    }

    public String getFeespaid() {
        return feespaid;
    }

    public void setFeespaid(String feespaid) {
        this.feespaid = feespaid;
    }

    public Date getFeespaiddate() {
        return feespaiddate;
    }

    public void setFeespaiddate(Date feespaiddate) {
        this.feespaiddate = feespaiddate;
    }

    public String getFeespaiduser() {
        return feespaiduser;
    }

    public void setFeespaiduser(String feespaiduser) {
        this.feespaiduser = feespaiduser;
    }

    public String getFullpaid() {
        return fullpaid;
    }

    public void setFullpaid(String fullpaid) {
        this.fullpaid = fullpaid;
    }

    public Date getFullpaiddate() {
        return fullpaiddate;
    }

    public void setFullpaiddate(Date fullpaiddate) {
        this.fullpaiddate = fullpaiddate;
    }

    public String getFullpaidremarks() {
        return fullpaidremarks;
    }

    public void setFullpaidremarks(String fullpaidremarks) {
        this.fullpaidremarks = fullpaidremarks;
    }

    public String getFullpaiduser() {
        return fullpaiduser;
    }

    public void setFullpaiduser(String fullpaiduser) {
        this.fullpaiduser = fullpaiduser;
    }

    public String getHostelallow() {
        return hostelallow;
    }

    public void setHostelallow(String hostelallow) {
        this.hostelallow = hostelallow;
    }

    public Date getHostelallowdate() {
        return hostelallowdate;
    }

    public void setHostelallowdate(Date hostelallowdate) {
        this.hostelallowdate = hostelallowdate;
    }

    public String getHostelallowuser() {
        return hostelallowuser;
    }

    public void setHostelallowuser(String hostelallowuser) {
        this.hostelallowuser = hostelallowuser;
    }

    public String getHostelconfirmation() {
        return hostelconfirmation;
    }

    public void setHostelconfirmation(String hostelconfirmation) {
        this.hostelconfirmation = hostelconfirmation;
    }

    public Date getHostelconfirmationdate() {
        return hostelconfirmationdate;
    }

    public void setHostelconfirmationdate(Date hostelconfirmationdate) {
        this.hostelconfirmationdate = hostelconfirmationdate;
    }

    public String getHostelconfirmationuser() {
        return hostelconfirmationuser;
    }

    public void setHostelconfirmationuser(String hostelconfirmationuser) {
        this.hostelconfirmationuser = hostelconfirmationuser;
    }

    public HostelType getHosteltype() {
        return hosteltype;
    }

    public void setHosteltype(HostelType hosteltype) {
        this.hosteltype = hosteltype;
    }

    public StudentRegistrationId getId() {
        return id;
    }

    public void setId(StudentRegistrationId id) {
        this.id = id;
    }

    public String getPreventfreezed() {
        return preventfreezed;
    }

    public void setPreventfreezed(String preventfreezed) {
        this.preventfreezed = preventfreezed;
    }

    public Date getPreventfrom() {
        return preventfrom;
    }

    public void setPreventfrom(Date preventfrom) {
        this.preventfrom = preventfrom;
    }

    public Date getPreventto() {
        return preventto;
    }

    public void setPreventto(Date preventto) {
        this.preventto = preventto;
    }

    public String getPrfreezedby() {
        return prfreezedby;
    }

    public void setPrfreezedby(String prfreezedby) {
        this.prfreezedby = prfreezedby;
    }

    public Date getPrfreezeddate() {
        return prfreezeddate;
    }

    public void setPrfreezeddate(Date prfreezeddate) {
        this.prfreezeddate = prfreezeddate;
    }

    public String getRegallow() {
        return regallow;
    }

    public void setRegallow(String regallow) {
        this.regallow = regallow;
    }

    public Date getRegallowdate() {
        return regallowdate;
    }

    public void setRegallowdate(Date regallowdate) {
        this.regallowdate = regallowdate;
    }

    public String getRegallowuser() {
        return regallowuser;
    }

    public void setRegallowuser(String regallowuser) {
        this.regallowuser = regallowuser;
    }

    public Date getRegconfirmatiodate() {
        return regconfirmatiodate;
    }

    public void setRegconfirmatiodate(Date regconfirmatiodate) {
        this.regconfirmatiodate = regconfirmatiodate;
    }

    public String getRegconfirmation() {
        return regconfirmation;
    }

    public void setRegconfirmation(String regconfirmation) {
        this.regconfirmation = regconfirmation;
    }

    public String getRegconfirmationuser() {
        return regconfirmationuser;
    }

    public void setRegconfirmationuser(String regconfirmationuser) {
        this.regconfirmationuser = regconfirmationuser;
    }

    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getPrsubjstaffprefby() {
        return prsubjstaffprefby;
    }

    public void setPrsubjstaffprefby(String prsubjstaffprefby) {
        this.prsubjstaffprefby = prsubjstaffprefby;
    }

    public Date getPrsubjstaffprefdate() {
        return prsubjstaffprefdate;
    }

    public void setPrsubjstaffprefdate(Date prsubjstaffprefdate) {
        this.prsubjstaffprefdate = prsubjstaffprefdate;
    }

    public String getPrsubjstaffpreffreezed() {
        return prsubjstaffpreffreezed;
    }

    public void setPrsubjstaffpreffreezed(String prsubjstaffpreffreezed) {
        this.prsubjstaffpreffreezed = prsubjstaffpreffreezed;
    }

    public String getSstpopulated() {
        return sstpopulated;
    }

    public void setSstpopulated(String sstpopulated) {
        this.sstpopulated = sstpopulated;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }

    public byte getStynumber() {
        return stynumber;
    }

    public void setStynumber(byte stynumber) {
        this.stynumber = stynumber;
    }

    public StyType getStytype() {
        return stytype;
    }

    public void setStytype(StyType stytype) {
        this.stytype = stytype;
    }

    public StudentQuota getStudentquota() {
        return studentquota;
    }

    public void setStudentquota(StudentQuota studentquota) {
        this.studentquota = studentquota;
    }

    public String getSubjecttagged() {
        return subjecttagged;
    }

    public void setSubjecttagged(String subjecttagged) {
        this.subjecttagged = subjecttagged;
    }

    public String getStytypeid() {
        return stytypeid;
    }

    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }

    public String getQuotaid() {
        return quotaid;
    }

    public void setQuotaid(String quotaid) {
        this.quotaid = quotaid;
    }

    public String getHosteltypeid() {
        return hosteltypeid;
    }

    public void setHosteltypeid(String hosteltypeid) {
        this.hosteltypeid = hosteltypeid;
    }

    public Set<StudentRegistration_info> getStudentregistration_infos() {
        return studentregistration_infos;
    }

    public void setStudentregistration_infos(Set<StudentRegistration_info> studentregistration_infos) {
        this.studentregistration_infos = studentregistration_infos;
    }

    public String getInstitutecopysubmitted() {
        return institutecopysubmitted;
    }

    public void setInstitutecopysubmitted(String institutecopysubmitted) {
        this.institutecopysubmitted = institutecopysubmitted;
    }

    /**
     * @return the prstudentsubjectchoicecounts
     */
    public Set<PRStudentSubjectChoiceCount> getPrstudentsubjectchoicecounts() {
        return prstudentsubjectchoicecounts;
    }

    /**
     * @return the studentsubjectchoicemasters
     */
    public Set<StudentSubjectChoiceMaster> getStudentsubjectchoicemasters() {
        return studentsubjectchoicemasters;
    }

    /**
     * @param prstudentsubjectchoicecounts the prstudentsubjectchoicecounts to
     * set
     */
    public void setPrstudentsubjectchoicecounts(Set<PRStudentSubjectChoiceCount> prstudentsubjectchoicecounts) {
        this.prstudentsubjectchoicecounts = prstudentsubjectchoicecounts;
    }

    /**
     * @param studentsubjectchoicemasters the studentsubjectchoicemasters to set
     */
    public void setStudentsubjectchoicemasters(Set<StudentSubjectChoiceMaster> studentsubjectchoicemasters) {
        this.studentsubjectchoicemasters = studentsubjectchoicemasters;
    }

    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid();
    }

    public Date getCopysubmitiondate() {
        return copysubmitiondate;
    }

    public void setCopysubmitiondate(Date copysubmitiondate) {
        this.copysubmitiondate = copysubmitiondate;
    }

    public String getCopysubmitteduser() {
        return copysubmitteduser;
    }

    public void setCopysubmitteduser(String copysubmitteduser) {
        this.copysubmitteduser = copysubmitteduser;
    }

    public String getInstelectivefreezed() {
        return instelectivefreezed;
    }

    public void setInstelectivefreezed(String instelectivefreezed) {
        this.instelectivefreezed = instelectivefreezed;
    }

    public String getInstelectivefreezedby() {
        return instelectivefreezedby;
    }

    public void setInstelectivefreezedby(String instelectivefreezedby) {
        this.instelectivefreezedby = instelectivefreezedby;
    }

    public Date getInstelectivefreezingdate() {
        return instelectivefreezingdate;
    }

    public void setInstelectivefreezingdate(Date instelectivefreezingdate) {
        this.instelectivefreezingdate = instelectivefreezingdate;
    }

    public String getAcademicregistrationflag() {
        return academicregistrationflag;
    }

    public void setAcademicregistrationflag(String academicregistrationflag) {
        this.academicregistrationflag = academicregistrationflag;
    }

    public String getAcademicregistrationby() {
        return academicregistrationby;
    }

    public void setAcademicregistrationby(String academicregistrationby) {
        this.academicregistrationby = academicregistrationby;
    }

    public Date getAcademicregistrationdate() {
        return academicregistrationdate;
    }

    public void setAcademicregistrationdate(Date academicregistrationdate) {
        this.academicregistrationdate = academicregistrationdate;
    }

    public String getAttendanceby() {
        return attendanceby;
    }

    public void setAttendanceby(String attendanceby) {
        this.attendanceby = attendanceby;
    }

    public Date getAttendancedate() {
        return attendancedate;
    }

    public void setAttendancedate(Date attendancedate) {
        this.attendancedate = attendancedate;
    }

    public String getAttendancedone() {
        return attendancedone;
    }

    public void setAttendancedone(String attendancedone) {
        this.attendancedone = attendancedone;
    }

    public String getFeepaymentmode() {
        return feepaymentmode;
    }

    public void setFeepaymentmode(String feepaymentmode) {
        this.feepaymentmode = feepaymentmode;
    }

    public Set<StudentCertificateSlno> getStudentcertificateslnos() {
        return studentcertificateslnos;
    }

    public void setStudentcertificateslnos(Set<StudentCertificateSlno> studentcertificateslnos) {
        this.studentcertificateslnos = studentcertificateslnos;
    }

    public Set<NotEligibleForRegistration> getNoteligibleforregistrations() {
        return noteligibleforregistrations;
    }

    public void setNoteligibleforregistrations(Set<NotEligibleForRegistration> noteligibleforregistrations) {
        this.noteligibleforregistrations = noteligibleforregistrations;
    }

    public Set<StudentYearBackDetail> getStudentyearbackdetails() {
        return studentyearbackdetails;
    }

    public void setStudentyearbackdetails(Set<StudentYearBackDetail> studentyearbackdetails) {
        this.studentyearbackdetails = studentyearbackdetails;
    }

    public String getSupplimentoryfeepaidby() {
        return supplimentoryfeepaidby;
    }

    public void setSupplimentoryfeepaidby(String supplimentoryfeepaidby) {
        this.supplimentoryfeepaidby = supplimentoryfeepaidby;
    }

    public Date getSupplimentoryfeepaiddate() {
        return supplimentoryfeepaiddate;
    }

    public void setSupplimentoryfeepaiddate(Date supplimentoryfeepaiddate) {
        this.supplimentoryfeepaiddate = supplimentoryfeepaiddate;
    }

    public String getSupplimentryfeepaid() {
        return supplimentryfeepaid;
    }

    public void setSupplimentryfeepaid(String supplimentryfeepaid) {
        this.supplimentryfeepaid = supplimentryfeepaid;
    }

    public Set<RegCoordinatorTagging> getRegcoordinatortaggings() {
        return regcoordinatortaggings;
    }

    public void setRegcoordinatortaggings(Set<RegCoordinatorTagging> regcoordinatortaggings) {
        this.regcoordinatortaggings = regcoordinatortaggings;
    }

    public String getElegibilityfeeapplicable() {
        return elegibilityfeeapplicable;
    }

    public void setElegibilityfeeapplicable(String elegibilityfeeapplicable) {
        this.elegibilityfeeapplicable = elegibilityfeeapplicable;
    }

    public Date getElegibilityfeedate() {
        return elegibilityfeedate;
    }

    public void setElegibilityfeedate(Date elegibilityfeedate) {
        this.elegibilityfeedate = elegibilityfeedate;
    }

    public String getAllowforfeepay() {
        return allowforfeepay;
    }

    public void setAllowforfeepay(String allowforfeepay) {
        this.allowforfeepay = allowforfeepay;
    }

    public String getDocverification() {
        return docverification;
    }

    public void setDocverification(String docverification) {
        this.docverification = docverification;
    }

    public String getAllowforsubjectchoice() {
        return allowforsubjectchoice;
    }

    public void setAllowforsubjectchoice(String allowforsubjectchoice) {
        this.allowforsubjectchoice = allowforsubjectchoice;
    }

    public String getTransportallow() {
        return transportallow;
    }

    public void setTransportallow(String transportallow) {
        this.transportallow = transportallow;
    }
   
    
    
}
