package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA


import org.apache.commons.beanutils.BeanUtils;
import java.util.Date;

/**
 * StudentHostelDetail generated by hbm2java
 */
public class StudentHostelDetail  implements java.io.Serializable {
    
     private StudentHostelDetailId id;
     private HostelMaster hostelmaster;          
     private StudentMaster studentmaster;
     private RegistrationMaster registrationmaster;
     private HostelRoomBedMaster hostelroombedmaster;
     private Date allotedtilldate;
     private Date allotedfromdate;
     private Integer allotedbedno;
     private String allotedroomno;
     private String remarks;
     private Date hostellefton;
     private String roomid;
     private String bedid;



    public StudentHostelDetail() {
    }

    public StudentHostelDetail(StudentHostelDetail dto) {
       this.id=dto.getId();              
       this.allotedtilldate = dto.getAllotedtilldate();
       this.allotedbedno = dto.getAllotedbedno();
       this.allotedroomno = dto.getAllotedroomno();
       this.remarks = dto.getRemarks();
       this.hostellefton = dto.getHostellefton();
       this.roomid = dto.getRoomid();
       this.bedid = dto.getBedid();

      
    }

    public StudentHostelDetail(StudentHostelDetailId id, HostelMaster hostelmaster, StudentMaster studentmaster, RegistrationMaster registrationmaster, Date dateofallotement ) {
        this.id = id;
        this.hostelmaster = hostelmaster;        
        this.studentmaster = studentmaster;
        this.registrationmaster = registrationmaster;        
        
       
    }
    public StudentHostelDetail(StudentHostelDetailId id, HostelMaster hostelmaster, StudentMaster studentmaster, RegistrationMaster registrationmaster, Date allotedfromdate, Date allotedtilldate, Integer allotedbedno, String allotedroomno, String remarks, Date hostellefton )
    {
       this.id = id;
       this.hostelmaster = hostelmaster;       
       this.studentmaster = studentmaster;
       this.registrationmaster = registrationmaster;       
       this.allotedtilldate = allotedtilldate;
       this.allotedbedno = allotedbedno;
       this.allotedroomno = allotedroomno;
       this.remarks = remarks;
       this.hostellefton = hostellefton;

    }



    public void setId(StudentHostelDetailId id) {
        this.id = id;
    }

    public StudentHostelDetailId getId() {
        return this.id;
    }

    public Date getAllotedtilldate() {
        return this.allotedtilldate;
    }

    public void setAllotedtilldate(Date allotedtilldate) {
        this.allotedtilldate = allotedtilldate;
    }
    public Integer getAllotedbedno() {
        return this.allotedbedno;
    }

    public void setAllotedbedno(Integer allotedbedno) {
        this.allotedbedno = allotedbedno;
    }
    public String getAllotedroomno() {
        return this.allotedroomno;
    }

    public void setAllotedroomno(String allotedroomno) {
        this.allotedroomno = allotedroomno;
    }
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Date getHostellefton() {
        return this.hostellefton;
    }

    public void setHostellefton(Date hostellefton) {
        this.hostellefton = hostellefton;
    }

    public HostelMaster getHostelmaster() {
        return hostelmaster;
    }

    public void setHostelmaster(HostelMaster hostelmaster) {
        this.hostelmaster = hostelmaster;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }

    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

//    public void setAsid(ASObject id) {
//        if (this.id == null) {
//            this.id = new StudentHostelDetailId();
//        }
//        try {
//            BeanUtils.copyProperties(this.id, id);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    /**
     * @return the stydesc
     */


     
     public String getIdStr() {
        return (id.getInstituteid() + "::" +id.getRegistrationid()+ "::" +id.getHostelid()+ "::" +id.getDateofallotement()+"::"+id.getStudentid());
    }

    public Date getAllotedfromdate() {
        return allotedfromdate;
    }

    public void setAllotedfromdate(Date allotedfromdate) {
        this.allotedfromdate = allotedfromdate;
    }

    public String getBedid() {
        return bedid;
    }

    public void setBedid(String bedid) {
        this.bedid = bedid;
    }

    public String getRoomid() {
        return roomid;
    }

    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    public HostelRoomBedMaster getHostelroombedmaster() {
        return hostelroombedmaster;
    }

    public void setHostelroombedmaster(HostelRoomBedMaster hostelroombedmaster) {
        this.hostelroombedmaster = hostelroombedmaster;
    }
    


}