package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA



/**
 * StudentInDetailId generated by hbm2java
 */
public class StudentInDetailId  implements java.io.Serializable {


     private String instituteid;
     private String studentid;

    public StudentInDetailId() {
    }

    public StudentInDetailId(String instituteid, String studentid) {
       this.instituteid = instituteid;
       this.studentid = studentid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentInDetailId) ) return false;
		 StudentInDetailId castOther = ( StudentInDetailId ) other; 
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getStudentid()==castOther.getStudentid()) || ( this.getStudentid()!=null && castOther.getStudentid()!=null && this.getStudentid().equals(castOther.getStudentid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getStudentid() == null ? 0 : this.getStudentid().hashCode() );
         return result;
   }   


}


