package com.jilit.irp.persistence.dto;
// Generated 5 Nov, 2013 4:13:13 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Studentqlyboardmaster generated by hbm2java
 */
public class StudentQlyBoardMaster implements java.io.Serializable {

    private String boardid;
    private String boardcode;
    private String boardname;
    private Short seqid;
    private String deactive;
    private String boarduniv;
    private Set<StudentQualification> studentqualifications = new HashSet<StudentQualification>(0);

    public StudentQlyBoardMaster() {
    }

    public StudentQlyBoardMaster(StudentQlyBoardMaster dto) {

        this.boardid = dto.getBoardid();
        this.boardcode = dto.getBoardcode();
        this.boardname = dto.getBoardname();
        this.seqid = dto.getSeqid();
        this.deactive = dto.getDeactive();
        this.boarduniv = dto.getBoarduniv();
    }

    public StudentQlyBoardMaster(String boardid, String boardcode, String boardname) {
        this.boardid = boardid;
        this.boardcode = boardcode;
        this.boardname = boardname;
    }

    public StudentQlyBoardMaster(String boardid, String boardcode, String boardname, Short seqid, String deactive, Set studentqualifications) {
        this.boardid = boardid;
        this.boardcode = boardcode;
        this.boardname = boardname;
        this.seqid = seqid;
        this.deactive = deactive;
        this.studentqualifications = studentqualifications;
    }

    public String getBoardid() {
        return this.boardid;
    }

    public void setBoardid(String boardid) {
        this.boardid = boardid;
    }

    public String getBoardcode() {
        return this.boardcode;
    }

    public void setBoardcode(String boardcode) {
        this.boardcode = boardcode;
    }

    public String getBoardname() {
        return this.boardname;
    }

    public void setBoardname(String boardname) {
        this.boardname = boardname;
    }

    public Short getSeqid() {
        return this.seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getBoarduniv() {
        return boarduniv;
    }

    public void setBoarduniv(String boarduniv) {
        this.boarduniv = boarduniv;
    }

    public Set<StudentQualification> getStudentqualifications() {
        return studentqualifications;
    }

    public void setStudentqualifications(Set<StudentQualification> studentqualifications) {
        this.studentqualifications = studentqualifications;
    }
}


