package com.jilit.irp.persistence.dto;
// Generated Feb 14, 2015 2:20:13 PM by Hibernate Tools 3.2.1.GA



/**
 * Studentattendancesummary generated by hbm2java
 */
public class Studentattendancesummary  implements java.io.Serializable {


     private StudentattendancesummaryId id;
     private StudentMaster studentmaster;
     private SubjectMaster subjectmaster;
     private Short totalclasses;
     private Short totalpresent;
     private Short totalleave;
     private Short totalactivity;

    public Studentattendancesummary() {
    }

	
    public Studentattendancesummary(StudentattendancesummaryId id) {
        this.id = id;
    }
    public Studentattendancesummary(StudentattendancesummaryId id, Short totalclasses, Short totalpresent, Short totalleave, Short totalactivity) {
       this.id = id;
       this.totalclasses = totalclasses;
       this.totalpresent = totalpresent;
       this.totalleave = totalleave;
       this.totalactivity = totalactivity;
    }
   
    public StudentattendancesummaryId getId() {
        return this.id;
    }
    
    public void setId(StudentattendancesummaryId id) {
        this.id = id;
    }
    public Short getTotalclasses() {
        return this.totalclasses;
    }
    
    public void setTotalclasses(Short totalclasses) {
        this.totalclasses = totalclasses;
    }
    public Short getTotalpresent() {
        return this.totalpresent;
    }
    
    public void setTotalpresent(Short totalpresent) {
        this.totalpresent = totalpresent;
    }
    public Short getTotalleave() {
        return this.totalleave;
    }
    
    public void setTotalleave(Short totalleave) {
        this.totalleave = totalleave;
    }
    public Short getTotalactivity() {
        return this.totalactivity;
    }
    
    public void setTotalactivity(Short totalactivity) {
        this.totalactivity = totalactivity;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    




}


