package com.jilit.irp.persistence.dto;
// Generated 7 Oct, 2011 11:34:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Studentcertificatesetupdetail generated by hbm2java
 */
public class StudentCertificateSetupDetail  implements java.io.Serializable {


     private StudentCertificateSetupDetailId id;
     private ProgramMaster programmaster;
     private Academicyear academicyear;
     private StudentCertificateMaster studentcertificatemaster;
     private BranchMaster branchmaster;
     private String deactive;

    public StudentCertificateSetupDetail() {
    }

    public StudentCertificateSetupDetail(StudentCertificateSetupDetailId id, ProgramMaster programmaster, Academicyear academicyear, StudentCertificateMaster studentcertificatemaster, BranchMaster branchmaster, String deactive) {
       this.id = id;
       this.programmaster = programmaster;
       this.academicyear = academicyear;
       this.studentcertificatemaster = studentcertificatemaster;
       this.branchmaster = branchmaster;
       this.deactive = deactive;
    }
   
    public StudentCertificateSetupDetailId getId() {
        return this.id;
    }
    
    public void setId(StudentCertificateSetupDetailId id) {
        this.id = id;
    }

    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }
    public StudentCertificateMaster getStudentcertificatemaster() {
        return this.studentcertificatemaster;
    }
    
    public void setStudentcertificatemaster(StudentCertificateMaster studentcertificatemaster) {
        this.studentcertificatemaster = studentcertificatemaster;
    }

    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public BranchMaster getBranchmaster() {
        return branchmaster;
    }

    public void setBranchmaster(BranchMaster branchmaster) {
        this.branchmaster = branchmaster;
    }

    public ProgramMaster getProgrammaster() {
        return programmaster;
    }

    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }

    public String getIdStr() {
        return (id.getInstituteid() +"::"+id.getCertificateid() + "::" + id.getAcademicyear() + "::" + id.getProgramid() + "::" + id.getBranchid());
    }
}


