package com.jilit.irp.persistence.dto;
// Generated 1 Oct, 2011 6:05:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Studentcertificateslno generated by hbm2java
 */
public class StudentCertificateSlno  implements java.io.Serializable {


     private StudentCertificateSlnoId id;
     private ProgramMaster programmaster;
     private BranchMaster branchmaster;
     private Academicyear academicyear;
     private StudentCertificateMaster studentcertificatemaster;
     private StudentRegistration studentregistration;
     private String certificateno;
     private Date certificateissuedate;
     private String certificateissueby;
     private Byte certificateissuecount;
     private String deactive;

    public StudentCertificateSlno() {
    }

    public StudentCertificateSlno(StudentCertificateSlno dto) {
        this.id=dto.getId();
        this.certificateno=dto.getCertificateno();
        this.certificateissuedate=dto.getCertificateissuedate();
        this.certificateissueby=dto.getCertificateissueby();
        this.certificateissuecount=dto.getCertificateissuecount();
        this.deactive=dto.getDeactive();
    }

	
    public StudentCertificateSlno(StudentCertificateSlnoId id, ProgramMaster programmaster, Academicyear academicyear, StudentCertificateMaster studentcertificatemaster, StudentRegistration studentregistration, String certificateno) {
        this.id = id;
        this.programmaster = programmaster;
        this.academicyear = academicyear;
        this.studentcertificatemaster = studentcertificatemaster;
        this.studentregistration = studentregistration;
        this.certificateno = certificateno;
    }
    public StudentCertificateSlno(StudentCertificateSlnoId id, ProgramMaster programmaster, Academicyear academicyear, StudentCertificateMaster studentcertificatemaster, StudentRegistration studentregistration, String certificateno, Date certificateissuedate, String certificateissueby, Byte certificateissuecount, String deactive) {
       this.id = id;
       this.programmaster = programmaster;
       this.academicyear = academicyear;
       this.studentcertificatemaster = studentcertificatemaster;
       this.studentregistration = studentregistration;
       this.certificateno = certificateno;
       this.certificateissuedate = certificateissuedate;
       this.certificateissueby = certificateissueby;
       this.certificateissuecount = certificateissuecount;
       this.deactive = deactive;
    }
   
    public StudentCertificateSlnoId getId() {
        return this.id;
    }
    
    public void setId(StudentCertificateSlnoId id) {
        this.id = id;
    }
    public ProgramMaster getProgrammaster() {
        return this.programmaster;
    }
    
    public void setProgrammaster(ProgramMaster programmaster) {
        this.programmaster = programmaster;
    }
    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }
    public StudentCertificateMaster getStudentcertificatemaster() {
        return this.studentcertificatemaster;
    }
    
    public void setStudentcertificatemaster(StudentCertificateMaster studentcertificatemaster) {
        this.studentcertificatemaster = studentcertificatemaster;
    }
    public StudentRegistration getStudentregistration() {
        return this.studentregistration;
    }
    
    public void setStudentregistration(StudentRegistration studentregistration) {
        this.studentregistration = studentregistration;
    }
    public String getCertificateno() {
        return this.certificateno;
    }
    
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno;
    }
    public Date getCertificateissuedate() {
        return this.certificateissuedate;
    }
    
    public void setCertificateissuedate(Date certificateissuedate) {
        this.certificateissuedate = certificateissuedate;
    }
    public String getCertificateissueby() {
        return this.certificateissueby;
    }
    
    public void setCertificateissueby(String certificateissueby) {
        this.certificateissueby = certificateissueby;
    }
    public Byte getCertificateissuecount() {
        return this.certificateissuecount;
    }
    
    public void setCertificateissuecount(Byte certificateissuecount) {
        this.certificateissuecount = certificateissuecount;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
    public BranchMaster getBranchmaster() {
        return branchmaster;
    }

    public void setBranchmaster(BranchMaster branchmaster) {
        this.branchmaster = branchmaster;
    }


     public String getIdStr() {
            return (id.getInstituteid() + "::" + id.getRegistrationid() + "::" + id.getAcademicyear() + "::" + id.getProgramid() + "::" + id.getBranchid() + "::" + id.getStynumber() + "::" + id.getStytypeid() + "::" + id.getStudentid() + "::" + id.getRegistrationid());
        }
}


