package com.jilit.irp.persistence.dto;
// Generated Jul 17, 2014 2:37:41 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Studentattendancecategory generated by hbm2java
 */
public class StudentAttendanceCategory  implements java.io.Serializable, Comparable<StudentAttendanceCategory> {


     private StudentAttendanceCategoryId id;
     private InstituteMaster institutemaster;
     private String attcategorycode;
     private String attcategorydesc;
     private BigDecimal attfromrange;
     private BigDecimal atttorange;
     private String attdeatinedflag;
     private String deactive;
     private String entryby;
     private Date entrydate;

    public StudentAttendanceCategory() {
    }

       public StudentAttendanceCategory(StudentAttendanceCategory dto) {

        this.id = dto.getId();
        this.attcategorycode = dto.getAttcategorycode();
        this.attcategorydesc = dto.getAttcategorydesc();
        this.attfromrange = dto.getAttfromrange();
        this.atttorange = dto.getAtttorange();
        this.attdeatinedflag = dto.getAttdeatinedflag();
        this.entryby = dto.getEntryby();
        this.entrydate = dto.getEntrydate();
        this.deactive = dto.getDeactive();

    }
	
    public StudentAttendanceCategory(StudentAttendanceCategoryId id, InstituteMaster institutemaster, String attcategorycode, String attcategorydesc, BigDecimal attfromrange, BigDecimal atttorange) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.attcategorycode = attcategorycode;
        this.attcategorydesc = attcategorydesc;
        this.attfromrange = attfromrange;
        this.atttorange = atttorange;
    }
    public StudentAttendanceCategory(StudentAttendanceCategoryId id, InstituteMaster institutemaster, String attcategorycode, String attcategorydesc, BigDecimal attfromrange, BigDecimal atttorange, String attdeatinedflag, String deactive, String entryby, Date entrydate) {
       this.id = id;
       this.institutemaster = institutemaster;
       this.attcategorycode = attcategorycode;
       this.attcategorydesc = attcategorydesc;
       this.attfromrange = attfromrange;
       this.atttorange = atttorange;
       this.attdeatinedflag = attdeatinedflag;
       this.deactive = deactive;
       this.entryby = entryby;
       this.entrydate = entrydate;
    }

    public String getAttcategorycode() {
        return attcategorycode;
    }

    public void setAttcategorycode(String attcategorycode) {
        this.attcategorycode = attcategorycode;
    }

    public String getAttcategorydesc() {
        return attcategorydesc;
    }

    public void setAttcategorydesc(String attcategorydesc) {
        this.attcategorydesc = attcategorydesc;
    }

    public String getAttdeatinedflag() {
        return attdeatinedflag;
    }

    public void setAttdeatinedflag(String attdeatinedflag) {
        this.attdeatinedflag = attdeatinedflag;
    }

    public BigDecimal getAttfromrange() {
        return attfromrange;
    }

    public void setAttfromrange(BigDecimal attfromrange) {
        this.attfromrange = attfromrange;
    }

    public BigDecimal getAtttorange() {
        return atttorange;
    }

    public void setAtttorange(BigDecimal atttorange) {
        this.atttorange = atttorange;
    }

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public String getEntryby() {
        return entryby;
    }

    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public StudentAttendanceCategoryId getId() {
        return id;
    }

    public void setId(StudentAttendanceCategoryId id) {
        this.id = id;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {           
        this.institutemaster = institutemaster;
    }
    public String getIdStr(){
        return id.getInstituteid()+":"+id.getAttcategoryid();
    }

    public int compareTo(StudentAttendanceCategory obj) {
        
        //return  (this.attcategorycode.compareTo(obj.getAttcategorycode()));
        int i=0;
        if(this.atttorange.compareTo(obj.getAtttorange())==1)
            i=1;
        else
             if(this.atttorange.compareTo(obj.getAtttorange())==-1)
                 i=-1;
             else
                 i=0;
        return i;


          
    }


}


