package com.jilit.irp.persistence.dto;
// Generated 5 Nov, 2013 4:13:13 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentyearbackdetailId generated by hbm2java
 */
public class StudentYearBackDetailId  implements java.io.Serializable {


     private String instituteid;
     private String registrationid;
     private String studentid;
     private String typeofreason;
     private byte fromstynumber;
     private String previousacademicyear;

    public StudentYearBackDetailId() {
    }

    public StudentYearBackDetailId(String instituteid, String registrationid, String studentid, String typeofreason, byte fromstynumber, String previousacademicyear) {
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.studentid = studentid;
       this.typeofreason = typeofreason;
       this.fromstynumber = fromstynumber;
       this.previousacademicyear = previousacademicyear;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }
    public String getTypeofreason() {
        return this.typeofreason;
    }
    
    public void setTypeofreason(String typeofreason) {
        this.typeofreason = typeofreason;
    }
    public byte getFromstynumber() {
        return this.fromstynumber;
    }
    
    public void setFromstynumber(byte fromstynumber) {
        this.fromstynumber = fromstynumber;
    }
    public String getPreviousacademicyear() {
        return this.previousacademicyear;
    }
    
    public void setPreviousacademicyear(String previousacademicyear) {
        this.previousacademicyear = previousacademicyear;
    }


   

}


