    package com.jilit.irp.persistence.dto;
// Generated Sep 12, 2009 11:04:12 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * StyType generated by hbm2java
 */
public class StyType implements java.io.Serializable {

    private StyTypeId id;
    private InstituteMaster institutemaster;
    private String stytype;
    private String stytypedesc;
    private Short seqid;
    private String etod;
    private String deactive;
    
    private Set<StudentHostelDetail> studenthosteldetails = new HashSet<StudentHostelDetail>(0);

    private Set<PRSubjectFinalizationCriteria> prsubjectfinalizationcriterias = new HashSet<PRSubjectFinalizationCriteria>(0);
    private Set<StudentRegistration> studentregistrations = new HashSet<StudentRegistration>(0);
    private Set<StudentRegistration_info> studentregistration_infos = new HashSet<StudentRegistration_info>(0);
    private Set<StudentSubjectChoiceMaster> studentsubjectchoicemasters = new HashSet<StudentSubjectChoiceMaster>(0);
    private Set<FacultySubjectTagging> facultysubjecttaggings = new HashSet<FacultySubjectTagging>(0);
    private Set<StudentPreviousAttendence> studentpreviousattendences = new HashSet<StudentPreviousAttendence>(0);
    private Set<TT_TimeTableAllocationDetail> tt_timetableallocationdetails = new HashSet<TT_TimeTableAllocationDetail>(0);
    private Set<TT_SuspendedSlotsDetail> tt_suspendedslotsdetails = new HashSet<TT_SuspendedSlotsDetail>(0);
    private Set<Tmp_StudAttendSummary> tmp_studattendsummaries = new HashSet<Tmp_StudAttendSummary>(0);


    public StyType(StyType dto) {
        this.id = dto.getId();
        this.stytype = dto.getStytype();
        this.stytypedesc = dto.getStytypedesc();
        this.seqid = dto.getSeqid();
        this.etod = dto.getEtod();
        this.deactive = dto.getDeactive();
    }

    public StyType(StyType dto, boolean childReqd) {
        this.id = dto.getId();
        this.stytype = dto.getStytype();
        this.stytypedesc = dto.getStytypedesc();
        this.seqid = dto.getSeqid();
        this.etod = dto.getEtod();
        this.deactive = dto.getDeactive();
    }

    public StyType() {
    }

    public StyType(StyTypeId id, InstituteMaster institutemaster, String stytype, String stytypedesc) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.stytype = stytype;
        this.stytypedesc = stytypedesc;
    }

    public StyType(StyTypeId id, InstituteMaster institutemaster, String stytype, String stytypedesc, Short seqid, String etod, String deactive, Set<StudentHostelDetail> studenthosteldetails) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.stytype = stytype;
        this.stytypedesc = stytypedesc;
        this.seqid = seqid;
        this.etod = etod;
        this.deactive = deactive;
        this.studenthosteldetails = studenthosteldetails;
    }

    public StyType(StyTypeId id, String stytype, String stytypedesc) {
        this.id = id;
        this.stytype = stytype;
        this.stytypedesc = stytypedesc;
    }
   public StyType(StyTypeId id, String stytype, String stytypedesc, String deactive) {
        this.id = id;
        this.stytype = stytype;
        this.stytypedesc = stytypedesc;
        this.deactive = deactive;
    }
    public StyTypeId getId() {
        return this.id;
    }

    public void setId(StyTypeId id) {
        this.id = id;
    }

    public String getStytype() {
        return stytype;
    }

    public void setStytype(String stytype) {
        this.stytype = stytype;
    }

    public String getStytypedesc() {
        return stytypedesc;
    }

    public void setStytypedesc(String stytypedesc) {
        this.stytypedesc = stytypedesc;
    }

    public Short getSeqid() {
        return this.seqid;
    }

    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }

    public String getEtod() {
        return this.etod;
    }

    public String getIdStr() {
        return id.getInstituteid() + ":" + id.getStytypeid();
    }

    public void setEtod(String etod) {
        this.etod = etod;
    }

    public String getDeactive() {
        return this.deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public InstituteMaster getInstitutemaster() {
        return institutemaster;
    }

    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }

    public Set<StudentHostelDetail> getStudenthosteldetails() {
        return studenthosteldetails;
    }

    public void setStudenthosteldetails(Set<StudentHostelDetail> studenthosteldetails) {
        this.studenthosteldetails = studenthosteldetails;
    }

    public Set<PRSubjectFinalizationCriteria> getPrsubjectfinalizationcriterias() {
        return prsubjectfinalizationcriterias;
    }

    public void setPrsubjectfinalizationcriterias(Set<PRSubjectFinalizationCriteria> prsubjectfinalizationcriterias) {
        this.prsubjectfinalizationcriterias = prsubjectfinalizationcriterias;
    }

    public Set<StudentRegistration_info> getStudentregistration_infos() {
        return studentregistration_infos;
    }

    public void setStudentregistration_infos(Set<StudentRegistration_info> studentregistration_infos) {
        this.studentregistration_infos = studentregistration_infos;
    }

    public Set<StudentRegistration> getStudentregistrations() {
        return studentregistrations;
    }

    public void setStudentregistrations(Set<StudentRegistration> studentregistrations) {
        this.studentregistrations = studentregistrations;
    }

    public Set<StudentSubjectChoiceMaster> getStudentsubjectchoicemasters() {
        return studentsubjectchoicemasters;
    }

    public void setStudentsubjectchoicemasters(Set<StudentSubjectChoiceMaster> studentsubjectchoicemasters) {
        this.studentsubjectchoicemasters = studentsubjectchoicemasters;
    }

   

    public Set<FacultySubjectTagging> getFacultysubjecttaggings() {
        return facultysubjecttaggings;
    }

    public void setFacultysubjecttaggings(Set<FacultySubjectTagging> facultysubjecttaggings) {
        this.facultysubjecttaggings = facultysubjecttaggings;
    }

    public Set<StudentPreviousAttendence> getStudentpreviousattendences() {
        return studentpreviousattendences;
    }

    public void setStudentpreviousattendences(Set<StudentPreviousAttendence> studentpreviousattendences) {
        this.studentpreviousattendences = studentpreviousattendences;
    }

    public Set<TT_TimeTableAllocationDetail> getTt_timetableallocationdetails() {
        return tt_timetableallocationdetails;
    }

    public void setTt_timetableallocationdetails(Set<TT_TimeTableAllocationDetail> tt_timetableallocationdetails) {
        this.tt_timetableallocationdetails = tt_timetableallocationdetails;
    }

    public Set<TT_SuspendedSlotsDetail> getTt_suspendedslotsdetails() {
        return tt_suspendedslotsdetails;
    }

    public void setTt_suspendedslotsdetails(Set<TT_SuspendedSlotsDetail> tt_suspendedslotsdetails) {
        this.tt_suspendedslotsdetails = tt_suspendedslotsdetails;
    }

    public Set<Tmp_StudAttendSummary> getTmp_studattendsummaries() {
        return tmp_studattendsummaries;
    }

    public void setTmp_studattendsummaries(Set<Tmp_StudAttendSummary> tmp_studattendsummaries) {
        this.tmp_studattendsummaries = tmp_studattendsummaries;
    }


}


