package com.jilit.irp.persistence.dto;
// Generated May 12, 2010 11:54:58 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * SubjectForCommonLoadId generated by hbm2java
 */
public class SubjectForCommonLoad implements java.io.Serializable {

    private SubjectForCommonLoadId id;
    private SubjectMaster subjectmaster;
    private RegistrationMaster registrationmaster;
    private String status;
    private String entryby;
    private Date entrydate;

    public SubjectForCommonLoad() {
    }

    public SubjectForCommonLoadId getId() {
        return id;
    }

    public void setId(SubjectForCommonLoadId id) {
        this.id = id;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }

    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getEntryby() {
        return entryby;
    }

    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    
}
