package com.jilit.irp.persistence.dto;
// Generated Dec 19, 2009 12:17:52 PM by Hibernate Tools 3.2.1.GA



/**
 * SubjectmasterId generated by hbm2java
 */
public class SubjectMasterId  implements java.io.Serializable {


     private String instituteid;
     private String subjectid;

    public SubjectMasterId() {
    }

    

    public SubjectMasterId(String instituteid, String subjectid) {
       this.instituteid = instituteid;
       this.subjectid = subjectid;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubjectMasterId) ) return false;
		 SubjectMasterId castOther = ( SubjectMasterId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getSubjectid()==castOther.getSubjectid()) || ( this.getSubjectid()!=null && castOther.getSubjectid()!=null && this.getSubjectid().equals(castOther.getSubjectid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getSubjectid() == null ? 0 : this.getSubjectid().hashCode() );
         return result;
   }   


}


