package com.jilit.irp.persistence.dto;
// Generated May 24, 2014 5:24:41 PM by Hibernate Tools 3.2.1.GA


import com.jilit.irp.persistence.dto.DepartmentMaster;
import com.jilit.irp.persistence.dto.RoomTypeMaster;
import com.jilit.irp.persistence.dto.SubjectMaster;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Teachingloaddistribution generated by hbm2java
 */
public class TeachingLoadDistribution  implements java.io.Serializable {


     private String tlid;
     private RoomTypeMaster roomtypemaster;
     private SubjectMaster subjectmaster;
     private DepartmentMaster departmentmaster;
     private String registrationid;
     private String subjectid;
     private String instituteid;
     private String runningdepartmentid;
     private String reqroomtype;
     private String status;
     private String entryby;
     private Date entrydate;
     private String approvedby;
     private Date approveddate;
     private String approveremarks;
     private String deactive;
     private BigDecimal nooftutclass;
     private String electivesubectionalloted;
     private BigDecimal noofelectiveclass;
     private Set teachingloaddetails = new HashSet(0);

    public TeachingLoadDistribution() {
    }

	
    public TeachingLoadDistribution(String tlid, RoomTypeMaster roomtypemaster, SubjectMaster subjectmaster, DepartmentMaster departmentmaster, String registrationid) {
        this.tlid = tlid;
        this.roomtypemaster = roomtypemaster;
        this.subjectmaster = subjectmaster;
        this.departmentmaster = departmentmaster;
        this.registrationid = registrationid;
    }
    public TeachingLoadDistribution(String tlid, RoomTypeMaster roomtypemaster, SubjectMaster subjectmaster, DepartmentMaster departmentmaster, String registrationid,String subjectid,String instituteid,String runningdepartmentid,String reqroomtype, String status, String entryby, Date entrydate, String approvedby, Date approveddate, String approveremarks, String deactive, Set teachingloaddetails) {
       this.tlid = tlid;
       this.roomtypemaster = roomtypemaster;
       this.subjectmaster = subjectmaster;
       this.departmentmaster = departmentmaster;
       this.registrationid = registrationid;
       this.subjectid = subjectid;
       this.subjectid = instituteid;
       this.runningdepartmentid = runningdepartmentid;
       this.reqroomtype = reqroomtype;
       this.status = status;
       this.entryby = entryby;
       this.entrydate = entrydate;
       this.approvedby = approvedby;
       this.approveddate = approveddate;
       this.approveremarks = approveremarks;
       this.deactive = deactive;
       this.teachingloaddetails = teachingloaddetails;
    }
   
    public String getTlid() {
        return this.tlid;
    }

    public void setTlid(String tlid) {
        this.tlid = tlid;
    }

    public DepartmentMaster getDepartmentmaster() {
        return departmentmaster;
    }

    public void setDepartmentmaster(DepartmentMaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }

    public RoomTypeMaster getRoomtypemaster() {
        return roomtypemaster;
    }

    public void setRoomtypemaster(RoomTypeMaster roomtypemaster) {
        this.roomtypemaster = roomtypemaster;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }
   
    public String getSubjectid() {
        return subjectid;
    }

    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }


    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getEntryby() {
        return this.entryby;
    }
    
    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public String getApprovedby() {
        return this.approvedby;
    }
    
    public void setApprovedby(String approvedby) {
        this.approvedby = approvedby;
    }
    public Date getApproveddate() {
        return this.approveddate;
    }
    
    public void setApproveddate(Date approveddate) {
        this.approveddate = approveddate;
    }
    public String getApproveremarks() {
        return this.approveremarks;
    }
    
    public void setApproveremarks(String approveremarks) {
        this.approveremarks = approveremarks;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
    public Set getTeachingloaddetails() {
        return this.teachingloaddetails;
    }

    public String getInstituteid() {
        return instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }

    public String getReqroomtype() {
        return reqroomtype;
    }

    public void setReqroomtype(String reqroomtype) {
        this.reqroomtype = reqroomtype;
    }

    public String getRunningdepartmentid() {
        return runningdepartmentid;
    }

    public void setRunningdepartmentid(String runningdepartmentid) {
        this.runningdepartmentid = runningdepartmentid;
    }

    
    public void setTeachingloaddetails(Set teachingloaddetails) {
        this.teachingloaddetails = teachingloaddetails;
    }

    public BigDecimal getNooftutclass() {
        return nooftutclass;
    }

    public void setNooftutclass(BigDecimal nooftutclass) {
        this.nooftutclass = nooftutclass;
    }

    public String getElectivesubectionalloted() {
            return electivesubectionalloted;
        }

    public void setElectivesubectionalloted(String electivesubectionalloted) {
        this.electivesubectionalloted = electivesubectionalloted;
    }

    public BigDecimal getNoofelectiveclass() {
        return noofelectiveclass;
    }

    public void setNoofelectiveclass(BigDecimal noofelectiveclass) {
        this.noofelectiveclass = noofelectiveclass;
    }

    
}


