package com.jilit.irp.persistence.dto;
// Generated Jul 22, 2010 1:32:15 PM by Hibernate Tools 3.2.1.GA

/**
 * Temp_DefaulterInPrereg generated by hbm2java
 */
public class Temp_DefaulterInPrereg  implements java.io.Serializable {


     private Temp_DefaulterInPreRegId id;
     private StudentMaster studentmaster;
     private RegistrationMaster registrationmaster;
     private String reason;

    public Temp_DefaulterInPrereg() {
    }

	
    public Temp_DefaulterInPrereg(Temp_DefaulterInPreRegId id, StudentMaster studentmaster, RegistrationMaster registrationmaster) {
        this.id = id;
        this.studentmaster = studentmaster;
        this.registrationmaster = registrationmaster;
    }
    public Temp_DefaulterInPrereg(Temp_DefaulterInPreRegId id, StudentMaster studentmaster, RegistrationMaster registrationmaster, String reason) {
       this.id = id;
       this.studentmaster = studentmaster;
       this.registrationmaster = registrationmaster;
       this.reason = reason;
    }
   
    public Temp_DefaulterInPreRegId getId() {
        return this.id;
    }
    
    public void setId(Temp_DefaulterInPreRegId id) {
        this.id = id;
    }
    public StudentMaster getStudentmaster() {
        return this.studentmaster;
    }
    
    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }
    public RegistrationMaster getRegistrationmaster() {
        return this.registrationmaster;
    }
    
    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


