package com.jilit.irp.persistence.dto;
// Generated Jul 15, 2014 3:54:49 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tmp_studattendsummary generated by hbm2java
 */
public class Tmp_StudAttendSummary  implements java.io.Serializable {


     private Tmp_StudAttendSummaryId id;
     private SubjectMaster subjectmaster;
     private StyType stytype;
     private StudentMaster studentmaster;
     private RegistrationMaster registrationmaster;
     private String studentname;
     private String enrollmentno;
     private String subjectcode;
     private String subject;
     private Byte stynumber;
     private String stytypeid;
     private String stytypecode;
     private Set tmp_studattendsummarydetails = new HashSet(0);

    public Tmp_StudAttendSummary() {
    }


    public Tmp_StudAttendSummary(Tmp_StudAttendSummaryId id, SubjectMaster subjectmaster, StyType stytype, StudentMaster studentmaster, RegistrationMaster registrationmaster) {
        this.id = id;
        this.subjectmaster = subjectmaster;
        this.stytype = stytype;
        this.studentmaster = studentmaster;
        this.registrationmaster = registrationmaster;
    }
    public Tmp_StudAttendSummary(Tmp_StudAttendSummaryId id, SubjectMaster subjectmaster, StyType stytype, StudentMaster studentmaster, RegistrationMaster registrationmaster, String studentname, String enrollmentno, String subjectcode, String subject, Byte stynumber, String stytypeid, String stytypecode) {
       this.id = id;
       this.subjectmaster = subjectmaster;
       this.stytype = stytype;
       this.studentmaster = studentmaster;
       this.registrationmaster = registrationmaster;
       this.studentname = studentname;
       this.enrollmentno = enrollmentno;
       this.subjectcode = subjectcode;
       this.subject = subject;
       this.stynumber = stynumber;
       this.stytypeid = stytypeid;
       this.stytypecode = stytypecode;

    }

    public String getEnrollmentno() {
        return enrollmentno;
    }

    public void setEnrollmentno(String enrollmentno) {
        this.enrollmentno = enrollmentno;
    }

    public Tmp_StudAttendSummaryId getId() {
        return id;
    }

    public void setId(Tmp_StudAttendSummaryId id) {
        this.id = id;
    }


    public RegistrationMaster getRegistrationmaster() {
        return registrationmaster;
    }

    public void setRegistrationmaster(RegistrationMaster registrationmaster) {
        this.registrationmaster = registrationmaster;
    }

    public StudentMaster getStudentmaster() {
        return studentmaster;
    }

    public void setStudentmaster(StudentMaster studentmaster) {
        this.studentmaster = studentmaster;
    }

    public String getStudentname() {
        return studentname;
    }

    public void setStudentname(String studentname) {
        this.studentname = studentname;
    }

    public Byte getStynumber() {
        return stynumber;
    }

    public void setStynumber(Byte stynumber) {
        this.stynumber = stynumber;
    }

    public StyType getStytype() {
        return stytype;
    }

    public String getStytypeid() {
        return stytypeid;
    }

    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }



    public void setStytype(StyType stytype) {
        this.stytype = stytype;
    }

    public String getStytypecode() {
        return stytypecode;
    }

    public void setStytypecode(String stytypecode) {
        this.stytypecode = stytypecode;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getSubjectcode() {
        return subjectcode;
    }

    public void setSubjectcode(String subjectcode) {
        this.subjectcode = subjectcode;
    }

    public SubjectMaster getSubjectmaster() {
        return subjectmaster;
    }

    public void setSubjectmaster(SubjectMaster subjectmaster) {
        this.subjectmaster = subjectmaster;
    }


    public Set getTmp_studattendsummarydetails() {
        return tmp_studattendsummarydetails;
    }

    public void setTmp_studattendsummarydetails(Set tmp_studattendsummarydetails) {
        this.tmp_studattendsummarydetails = tmp_studattendsummarydetails;
    }




}


