package com.jilit.irp.persistence.dto;
// Generated 7 Feb, 2014 4:28:12 PM by Hibernate Tools 3.2.1.GA



/**
 * Tt#multifacultyteachingloadId generated by hbm2java
 */
public class TT_MultiFacultyTeachingLoadId  implements java.io.Serializable {


     private String tttransid;
     private String instituteid;
     private String registrationid;
     private String stafftype;
     private String staffid;

    public TT_MultiFacultyTeachingLoadId() {
    }

    public TT_MultiFacultyTeachingLoadId(String tttransid, String instituteid, String registrationid, String stafftype, String staffid) {
       this.tttransid = tttransid;
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.stafftype = stafftype;
       this.staffid = staffid;
    }
   
    public String getTttransid() {
        return this.tttransid;
    }
    
    public void setTttransid(String tttransid) {
        this.tttransid = tttransid;
    }
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getStafftype() {
        return this.stafftype;
    }
    
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }



}


