package com.jilit.irp.persistence.dto;
// Generated 7 Feb, 2014 4:28:12 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Tt#multifacultyteachingload generated by hbm2java
 */
public class TT_MultiFacultyTeachingLoad  implements java.io.Serializable {


     private TT_MultiFacultyTeachingLoadId id;
     
     private TT_TimeTableAllocation tt_timetableallocation;
     private BigDecimal noofhours;
     private BigDecimal classinaweek;
     private String deactive;

    public TT_MultiFacultyTeachingLoad() {
    }

	
    public TT_MultiFacultyTeachingLoad(TT_MultiFacultyTeachingLoadId id, TT_TimeTableAllocation tt_timetableallocation, BigDecimal noofhours, BigDecimal classinaweek) {
        this.id = id;
      
        this.tt_timetableallocation = tt_timetableallocation;
        this.noofhours = noofhours;
        this.classinaweek = classinaweek;
    }
    public TT_MultiFacultyTeachingLoad(TT_MultiFacultyTeachingLoadId id,  TT_TimeTableAllocation tt_timetableallocation, BigDecimal noofhours, BigDecimal classinaweek, String deactive)
    {
       this.id = id;
       
       this.tt_timetableallocation = tt_timetableallocation;
       this.noofhours = noofhours;
       this.classinaweek = classinaweek;
       this.deactive = deactive;
    }
   
    
    public BigDecimal getNoofhours() {
        return this.noofhours;
    }
    
    public void setNoofhours(BigDecimal noofhours) {
        this.noofhours = noofhours;
    }
    public BigDecimal getClassinaweek() {
        return this.classinaweek;
    }
    
    public void setClassinaweek(BigDecimal classinaweek) {
        this.classinaweek = classinaweek;
    }
    

    public String getDeactive() {
        return deactive;
    }

    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }

    public TT_MultiFacultyTeachingLoadId getId() {
        return id;
    }

    public void setId(TT_MultiFacultyTeachingLoadId id) {
        this.id = id;
    }

   
    public TT_TimeTableAllocation getTt_timetableallocation() {
        return tt_timetableallocation;
    }

    public void setTt_timetableallocation(TT_TimeTableAllocation tt_timetableallocation) {
        this.tt_timetableallocation = tt_timetableallocation;
    }

   


}


