package com.jilit.irp.persistence.dto;
// Generated Feb 20, 2017 11:03:02 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tt_schattendancelogdetail generated by hbm2java
 */
public class Tt_schattendancelogdetail  implements java.io.Serializable {


     private Tt_schattendancelogdetailId id;
     private Tt_schattendancelogmaster tt_schattendancelogmaster;
     private String stafftype;
     private String staffid;
     private String staffname;
     private String subjectid;
     private String subjectcode;
     private String subjectname;
     private String subjectcomponentid;
     private String subjectcomponentdesc;
     private Date attendancedate;
     private String allocationday;
     private String slotid;
     private String fromtime;
     private String totime;
     private String status;
     private String newstafftype;
     private String newstaffid;
     private String newstaffname;
     private String newsubjectid;
     private String newsubjectcode;
     private String newsubjectname;
     private String newsubjectcomponentid;
     private String newsubjectcomponentdesc;
     private Date newattendancedate;
     private String newallocationday;
     private String newslotid;
     private String newfromtime;
     private String newtotime;
     private String newstatus;

    public Tt_schattendancelogdetail() {
    }


    public Tt_schattendancelogdetail(Tt_schattendancelogdetailId id, Tt_schattendancelogmaster tt_schattendancelogmaster) {
        this.id = id;
        this.tt_schattendancelogmaster = tt_schattendancelogmaster;
    }
    public Tt_schattendancelogdetail(Tt_schattendancelogdetailId id, Tt_schattendancelogmaster tt_schattendancelogmaster, String stafftype, String staffid, String staffname, String subjectid, String subjectcode, String subjectname, String subjectcomponentid, String subjectcomponentdesc, Date attendancedate, String allocationday, String slotid, String fromtime, String totime, String status, String newstafftype, String newstaffid, String newstaffname, String newsubjectid, String newsubjectcode, String newsubjectname, String newsubjectcomponentid, String newsubjectcomponentdesc, Date newattendancedate, String newallocationday, String newslotid, String newfromtime, String newtotime, String newstatus) {
       this.id = id;
       this.tt_schattendancelogmaster = tt_schattendancelogmaster;
       this.stafftype = stafftype;
       this.staffid = staffid;
       this.staffname = staffname;
       this.subjectid = subjectid;
       this.subjectcode = subjectcode;
       this.subjectname = subjectname;
       this.subjectcomponentid = subjectcomponentid;
       this.subjectcomponentdesc = subjectcomponentdesc;
       this.attendancedate = attendancedate;
       this.allocationday = allocationday;
       this.slotid = slotid;
       this.fromtime = fromtime;
       this.totime = totime;
       this.status = status;
       this.newstafftype = newstafftype;
       this.newstaffid = newstaffid;
       this.newstaffname = newstaffname;
       this.newsubjectid = newsubjectid;
       this.newsubjectcode = newsubjectcode;
       this.newsubjectname = newsubjectname;
       this.newsubjectcomponentid = newsubjectcomponentid;
       this.newsubjectcomponentdesc = newsubjectcomponentdesc;
       this.newattendancedate = newattendancedate;
       this.newallocationday = newallocationday;
       this.newslotid = newslotid;
       this.newfromtime = newfromtime;
       this.newtotime = newtotime;
       this.newstatus = newstatus;
    }

    public Tt_schattendancelogdetailId getId() {
        return this.id;
    }

    public void setId(Tt_schattendancelogdetailId id) {
        this.id = id;
    }
    public Tt_schattendancelogmaster getTt_schattendancelogmaster() {
        return this.tt_schattendancelogmaster;
    }

    public void setTt_schattendancelogmaster(Tt_schattendancelogmaster tt_schattendancelogmaster) {
        this.tt_schattendancelogmaster = tt_schattendancelogmaster;
    }
    public String getStafftype() {
        return this.stafftype;
    }

    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }
    public String getStaffid() {
        return this.staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getStaffname() {
        return this.staffname;
    }

    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }
    public String getSubjectid() {
        return this.subjectid;
    }

    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }
    public String getSubjectcode() {
        return this.subjectcode;
    }

    public void setSubjectcode(String subjectcode) {
        this.subjectcode = subjectcode;
    }
    public String getSubjectname() {
        return this.subjectname;
    }

    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }
    public String getSubjectcomponentid() {
        return this.subjectcomponentid;
    }

    public void setSubjectcomponentid(String subjectcomponentid) {
        this.subjectcomponentid = subjectcomponentid;
    }
    public String getSubjectcomponentdesc() {
        return this.subjectcomponentdesc;
    }

    public void setSubjectcomponentdesc(String subjectcomponentdesc) {
        this.subjectcomponentdesc = subjectcomponentdesc;
    }
    public Date getAttendancedate() {
        return this.attendancedate;
    }

    public void setAttendancedate(Date attendancedate) {
        this.attendancedate = attendancedate;
    }
    public String getAllocationday() {
        return this.allocationday;
    }

    public void setAllocationday(String allocationday) {
        this.allocationday = allocationday;
    }
    public String getSlotid() {
        return this.slotid;
    }

    public void setSlotid(String slotid) {
        this.slotid = slotid;
    }
    public String getFromtime() {
        return this.fromtime;
    }

    public void setFromtime(String fromtime) {
        this.fromtime = fromtime;
    }
    public String getTotime() {
        return this.totime;
    }

    public void setTotime(String totime) {
        this.totime = totime;
    }
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    public String getNewstafftype() {
        return this.newstafftype;
    }

    public void setNewstafftype(String newstafftype) {
        this.newstafftype = newstafftype;
    }
    public String getNewstaffid() {
        return this.newstaffid;
    }

    public void setNewstaffid(String newstaffid) {
        this.newstaffid = newstaffid;
    }
    public String getNewstaffname() {
        return this.newstaffname;
    }

    public void setNewstaffname(String newstaffname) {
        this.newstaffname = newstaffname;
    }
    public String getNewsubjectid() {
        return this.newsubjectid;
    }

    public void setNewsubjectid(String newsubjectid) {
        this.newsubjectid = newsubjectid;
    }
    public String getNewsubjectcode() {
        return this.newsubjectcode;
    }

    public void setNewsubjectcode(String newsubjectcode) {
        this.newsubjectcode = newsubjectcode;
    }
    public String getNewsubjectname() {
        return this.newsubjectname;
    }

    public void setNewsubjectname(String newsubjectname) {
        this.newsubjectname = newsubjectname;
    }
    public String getNewsubjectcomponentid() {
        return this.newsubjectcomponentid;
    }

    public void setNewsubjectcomponentid(String newsubjectcomponentid) {
        this.newsubjectcomponentid = newsubjectcomponentid;
    }
    public String getNewsubjectcomponentdesc() {
        return this.newsubjectcomponentdesc;
    }

    public void setNewsubjectcomponentdesc(String newsubjectcomponentdesc) {
        this.newsubjectcomponentdesc = newsubjectcomponentdesc;
    }
    public Date getNewattendancedate() {
        return this.newattendancedate;
    }

    public void setNewattendancedate(Date newattendancedate) {
        this.newattendancedate = newattendancedate;
    }
    public String getNewallocationday() {
        return this.newallocationday;
    }

    public void setNewallocationday(String newallocationday) {
        this.newallocationday = newallocationday;
    }
    public String getNewslotid() {
        return this.newslotid;
    }

    public void setNewslotid(String newslotid) {
        this.newslotid = newslotid;
    }
    public String getNewfromtime() {
        return this.newfromtime;
    }

    public void setNewfromtime(String newfromtime) {
        this.newfromtime = newfromtime;
    }
    public String getNewtotime() {
        return this.newtotime;
    }

    public void setNewtotime(String newtotime) {
        this.newtotime = newtotime;
    }
    public String getNewstatus() {
        return this.newstatus;
    }

    public void setNewstatus(String newstatus) {
        this.newstatus = newstatus;
    }




}


