package com.jilit.irp.persistence.dto;
// Generated Feb 20, 2017 11:03:02 AM by Hibernate Tools 3.2.1.GA



/**
 * Tt#schattendancelogdetailId generated by hbm2java
 */
public class Tt_schattendancelogdetailId  implements java.io.Serializable {


     private String attlogid;
     private int slno;
     private String tttransid;

    public Tt_schattendancelogdetailId() {
    }

    public Tt_schattendancelogdetailId(String attlogid, int slno, String tttransid) {
       this.attlogid = attlogid;
       this.slno = slno;
       this.tttransid = tttransid;
    }

    public String getAttlogid() {
        return this.attlogid;
    }

    public void setAttlogid(String attlogid) {
        this.attlogid = attlogid;
    }
    public int getSlno() {
        return this.slno;
    }

    public void setSlno(int slno) {
        this.slno = slno;
    }
    public String getTttransid() {
        return this.tttransid;
    }

    public void setTttransid(String tttransid) {
        this.tttransid = tttransid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Tt_schattendancelogdetailId) ) return false;
		 Tt_schattendancelogdetailId castOther = ( Tt_schattendancelogdetailId ) other;

		 return ( (this.getAttlogid()==castOther.getAttlogid()) || ( this.getAttlogid()!=null && castOther.getAttlogid()!=null && this.getAttlogid().equals(castOther.getAttlogid()) ) )
 && (this.getSlno()==castOther.getSlno())
 && ( (this.getTttransid()==castOther.getTttransid()) || ( this.getTttransid()!=null && castOther.getTttransid()!=null && this.getTttransid().equals(castOther.getTttransid()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAttlogid() == null ? 0 : this.getAttlogid().hashCode() );
         result = 37 * result + this.getSlno();
         result = 37 * result + ( getTttransid() == null ? 0 : this.getTttransid().hashCode() );
         return result;
   }


}


