package com.jilit.irp.persistence.dto;
// Generated 7 Feb, 2014 4:28:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tt_slotmaster generated by hbm2java
 */
public class TT_SlotMaster  implements java.io.Serializable {


     private TT_SlotMasterId id;
     private TT_ApplicableDays tt_applicabledays;
     private byte slotno;
     private String slotcode;
     private String starttime;
     private String endtime;
     private String slotduration;
     private String deactive;
     private String entryby;
     private Date entrydate;
     private Set tt_timetableallocations = new HashSet(0);
     private Set tt_programwiseslots = new HashSet(0);

    public TT_SlotMaster() {
    }

	public TT_SlotMaster(TT_SlotMaster dto) {
       this.id = dto.getId();
       this.slotno = dto.getSlotno();
       this.slotcode = dto.getSlotcode();
       this.starttime = dto.getStarttime();
       this.endtime = dto.getEndtime();
       this.slotduration = dto.getSlotduration();
       this.deactive = dto.getDeactive();
       this.entryby = dto.getEntryby();
       this.entrydate = dto.getEntrydate();
       
    }

    public TT_SlotMaster(TT_SlotMasterId id, TT_ApplicableDays tt_applicabledays, byte slotno, String slotcode, String starttime, String endtime) {
        this.id = id;
        this.tt_applicabledays = tt_applicabledays;
        this.slotno = slotno;
        this.slotcode = slotcode;
        this.starttime = starttime;
        this.endtime = endtime;
    }
    public TT_SlotMaster(TT_SlotMasterId id, TT_ApplicableDays tt_applicabledays, byte slotno, String slotcode, String starttime, String endtime, String deactive, String entryby, Date entrydate, Set tt_timetableallocations, Set tt_programwiseslots) {
       this.id = id;
       this.tt_applicabledays = tt_applicabledays;
       this.slotno = slotno;
       this.slotcode = slotcode;
       this.starttime = starttime;
       this.endtime = endtime;
       this.deactive = deactive;
       this.entryby = entryby;
       this.entrydate = entrydate;
       this.tt_timetableallocations = tt_timetableallocations;
       this.tt_programwiseslots = tt_programwiseslots;
    }
   
    
     
    public byte getSlotno() {
        return this.slotno;
    }
    
    public void setSlotno(byte slotno) {
        this.slotno = slotno;
    }
    public String getSlotcode() {
        return this.slotcode;
    }
    
    public void setSlotcode(String slotcode) {
        this.slotcode = slotcode;
    }
    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }
    public String getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
    public String getEntryby() {
        return this.entryby;
    }
    
    public void setEntryby(String entryby) {
        this.entryby = entryby;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }    

    public TT_ApplicableDays getTt_applicabledays() {
        return tt_applicabledays;
    }

    public void setTt_applicabledays(TT_ApplicableDays tt_applicabledays) {
        this.tt_applicabledays = tt_applicabledays;
    }

    public Set getTt_programwiseslots() {
        return tt_programwiseslots;
    }

    public void setTt_programwiseslots(Set tt_programwiseslots) {
        this.tt_programwiseslots = tt_programwiseslots;
    }

    public Set getTt_timetableallocations() {
        return tt_timetableallocations;
    }

    public void setTt_timetableallocations(Set tt_timetableallocations) {
        this.tt_timetableallocations = tt_timetableallocations;
    }

    public TT_SlotMasterId getId() {
        return id;
    }

    public void setId(TT_SlotMasterId id) {
        this.id = id;
    }

    public String getIdStr() {
        return id.getInstituteid() + "::" + id.getRegistrationid()+"::"+id.getSlotid();
    }

    public String getSlotduration() {
        return slotduration;
    }

    public void setSlotduration(String slotduration) {
        this.slotduration = slotduration;
    }

    

    


}


