package com.jilit.irp.persistence.dto;
// Generated 7 Feb, 2014 4:28:12 PM by Hibernate Tools 3.2.1.GA

/**
 * Tt#timetableallocationId generated by hbm2java
 */
public class TT_TimeTableAllocationId implements java.io.Serializable {

    private String tttransid;
    private String registrationid;
    private String instituteid;

    public TT_TimeTableAllocationId() {
    }

    public TT_TimeTableAllocationId(String tttransid, String registrationid) {
        this.tttransid = tttransid;
        this.registrationid = registrationid;
    }

    public String getTttransid() {
        return this.tttransid;
    }

    public void setTttransid(String tttransid) {
        this.tttransid = tttransid;
    }

    public String getRegistrationid() {
        return this.registrationid;
    }

    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }

    public String getInstituteid() {
        return instituteid;
    }

    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }

}
