package com.jilit.irp.persistence.dto;
// Generated 7 Feb, 2014 4:28:12 PM by Hibernate Tools 3.2.1.GA



/**
 * Tt#timetableallocationdetailId generated by hbm2java
 */
public class TT_TimeTableAllocationDetailId  implements java.io.Serializable {


     private String tttransid;
     private String instituteid;
     private String registrationid;
     private String academicyear;
     private String programid;
     private String sectionid;
     private String subsectionid;
     private int stynumber;
     private String stytypeid;

    public TT_TimeTableAllocationDetailId() {
    }

    public TT_TimeTableAllocationDetailId(String tttransid, String instituteid, String registrationid, String academicyear, String programid, String sectionid, String subsectionid, int stynumber, String stytypeid ) {
       this.tttransid = tttransid;
       this.instituteid = instituteid;
       this.registrationid = registrationid;
       this.academicyear = academicyear;
       this.programid = programid;
       this.sectionid = sectionid;
       this.subsectionid = subsectionid;
       this.stynumber = stynumber;
       this.stytypeid = stytypeid;
    }
   
    public String getTttransid() {
        return this.tttransid;
    }
    
    public void setTttransid(String tttransid) {
        this.tttransid = tttransid;
    }
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }
    public String getProgramid() {
        return this.programid;
    }
    
    public void setProgramid(String programid) {
        this.programid = programid;
    }
    public String getSectionid() {
        return this.sectionid;
    }
    
    public void setSectionid(String sectionid) {
        this.sectionid = sectionid;
    }

    public int getStynumber() {
        return stynumber;
    }

    public void setStynumber(int stynumber) {
        this.stynumber = stynumber;
    }

    public String getStytypeid() {
        return stytypeid;
    }

    public void setStytypeid(String stytypeid) {
        this.stytypeid = stytypeid;
    }

    public String getSubsectionid() {
        return subsectionid;
    }

    public void setSubsectionid(String subsectionid) {
        this.subsectionid = subsectionid;
    }


  


}


