package com.jilit.irp.persistence.dto;
// Generated 7 Oct, 2011 3:51:57 PM by Hibernate Tools 3.2.1.GA



/**
 * UserintractiondetailId generated by hbm2java
 */
public class UserIntractionDetailId  implements java.io.Serializable {


     private String instituteid;
     private String refno;

    public UserIntractionDetailId() {
    }

    public UserIntractionDetailId(String instituteid, String refno) {
       this.instituteid = instituteid;
       this.refno = refno;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getRefno() {
        return this.refno;
    }
    
    public void setRefno(String refno) {
        this.refno = refno;
    }

}


