package com.jilit.irp.persistence.dto;
// Generated 5 Jun, 2012 6:27:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * VacationdatesId generated by hbm2java
 */
public class VacationDatesId  implements java.io.Serializable {


     private String instituteid;
     private String vacationid;
     private Date fromdate;

    public VacationDatesId() {
    }

    public VacationDatesId(String instituteid, String vacationid, Date fromdate) {
       this.instituteid = instituteid;
       this.vacationid = vacationid;
       this.fromdate = fromdate;
    }
   
    public String getInstituteid() {
        return this.instituteid;
    }
    
    public void setInstituteid(String instituteid) {
        this.instituteid = instituteid;
    }
    public String getVacationid() {
        return this.vacationid;
    }
    
    public void setVacationid(String vacationid) {
        this.vacationid = vacationid;
    }
    public Date getFromdate() {
        return this.fromdate;
    }
    
    public void setFromdate(Date fromdate) {
        this.fromdate = fromdate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VacationDatesId) ) return false;
		 VacationDatesId castOther = ( VacationDatesId ) other;
         
		 return ( (this.getInstituteid()==castOther.getInstituteid()) || ( this.getInstituteid()!=null && castOther.getInstituteid()!=null && this.getInstituteid().equals(castOther.getInstituteid()) ) )
 && ( (this.getVacationid()==castOther.getVacationid()) || ( this.getVacationid()!=null && castOther.getVacationid()!=null && this.getVacationid().equals(castOther.getVacationid()) ) )
 && ( (this.getFromdate()==castOther.getFromdate()) || ( this.getFromdate()!=null && castOther.getFromdate()!=null && this.getFromdate().equals(castOther.getFromdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInstituteid() == null ? 0 : this.getInstituteid().hashCode() );
         result = 37 * result + ( getVacationid() == null ? 0 : this.getVacationid().hashCode() );
         result = 37 * result + ( getFromdate() == null ? 0 : this.getFromdate().hashCode() );
         return result;
   }   


}


