package com.jilit.irp.persistence.dto;
// Generated 5 Jun, 2012 6:27:14 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vacationmaster generated by hbm2java
 */
public class VacationMaster  implements java.io.Serializable {


     private VacationMasterId id; 
     private InstituteMaster institutemaster;
     private String vacationcode;
     private String vacationdesc;
     private BigDecimal onevacationdayequealto;
     private Short seqid;
     private String deactive;
     private String transfertoleaveid;

     private Set<VacationDates> vacationdateses = new HashSet<VacationDates>(0);

    public VacationMaster() {
    }

	
    public VacationMaster(VacationMasterId id, InstituteMaster institutemaster, String vacationcode, String vacationdesc) {
        this.id = id;
        this.institutemaster = institutemaster;
        this.vacationcode = vacationcode;
        this.vacationdesc = vacationdesc;
    }
     public VacationMaster(VacationMasterId id, String vacationcode, String vacationdesc) {
        this.id = id;
        this.vacationcode = vacationcode;
        this.vacationdesc = vacationdesc;
    }
    public VacationMaster(VacationMasterId id, InstituteMaster institutemaster, String vacationcode, String vacationdesc, BigDecimal onevacationdayequealto, Short seqid, String deactive,  Set vacationdateses ) {
       this.id = id;
      
       this.institutemaster = institutemaster;
       this.vacationcode = vacationcode;
       this.vacationdesc = vacationdesc;
       this.onevacationdayequealto = onevacationdayequealto;
       this.seqid = seqid;
       this.deactive = deactive;

       this.vacationdateses = vacationdateses;
    }
   
    public VacationMasterId getId() {
        return this.id;
    }
    
    public void setId(VacationMasterId id) {
        this.id = id;
    }

    public InstituteMaster getInstitutemaster() {
        return this.institutemaster;
    }
    
    public void setInstitutemaster(InstituteMaster institutemaster) {
        this.institutemaster = institutemaster;
    }
    public String getVacationcode() {
        return this.vacationcode;
    }
    
    public void setVacationcode(String vacationcode) {
        this.vacationcode = vacationcode;
    }
    public String getVacationdesc() {
        return this.vacationdesc;
    }
    
    public void setVacationdesc(String vacationdesc) {
        this.vacationdesc = vacationdesc;
    }
    public BigDecimal getOnevacationdayequealto() {
        return this.onevacationdayequealto;
    }
    
    public void setOnevacationdayequealto(BigDecimal onevacationdayequealto) {
        this.onevacationdayequealto = onevacationdayequealto;
    }
    public Short getSeqid() {
        return this.seqid;
    }
    
    public void setSeqid(Short seqid) {
        this.seqid = seqid;
    }
    public String getDeactive() {
        return this.deactive;
    }
    
    public void setDeactive(String deactive) {
        this.deactive = deactive;
    }
    
    
    public String getTransfertoleaveid() {
        return transfertoleaveid;
    }

    public void setTransfertoleaveid(String transfertoleaveid) {
        this.transfertoleaveid = transfertoleaveid;
    }



    public Set<VacationDates> getVacationdateses() {
        return vacationdateses;
    }

    public void setVacationdateses(Set<VacationDates> vacationdateses) {
        this.vacationdateses = vacationdateses;
    }



    public String getIdStr(){
        return (id.getInstituteid()+"::"+id.getVacationid());
    }

    



    
}


